import { createHash } from "node:crypto";
import type { AiBuilderSession, BusinessContextCategory, BusinessContextEntry, GeneratedFaqEntry } from "../contracts";
import { websiteFactIdentity, websiteFactReviewIdentity, websiteFactFingerprint, type PersistedWebsiteKnowledge, type WebsiteKnowledgeFact } from "../knowledge/websiteKnowledge";
import { BUSINESS_MEMORY_SCHEMA_VERSION } from "./contracts";
import type { AssertionAuthority, BusinessAssertion, BusinessEntity, BusinessEntityType, BusinessMemory, BusinessMemoryConflict, BusinessMemoryMissingInformation, BusinessRelationship, Confidence, EntityMergeContract, EvidenceRecord, KnowledgeSource, KnowledgeSourceOrigin, ReviewState } from "./contracts";

export type BuildBusinessMemoryInput = {
  session: AiBuilderSession;
  websiteKnowledge: PersistedWebsiteKnowledge | null | undefined;
  /** Reviewed decisions supplied by the caller; this mapper never creates them. */
  entityMerges?: EntityMergeContract[];
};

type LegacyAssertion = { kind: "context" | "faq" | "website"; legacyEntryId: string | null; identity: string; entityIdentity: string; entityType: BusinessEntityType; name: string; alias: string; value: string; tags: string[]; confidence: Confidence; reviewState: ReviewState; source: Omit<KnowledgeSource, "id">; authority: AssertionAuthority; evidence: Array<{ url: string | null; excerpt: string }>; createdAt: string; updatedAt: string; faqSourceEntryIds: string[] };

function normalizeText(value: unknown): string { return String(value ?? "").replace(/\s+/g, " ").trim(); }
function normalizedIdentity(value: unknown): string { return normalizeText(value).toLowerCase(); }
function stableId(prefix: string, values: readonly string[]): string { return `${prefix}_${createHash("sha256").update(values.map(normalizedIdentity).join("\u0000")).digest("hex")}`; }
function compare(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
function sortedUnique(values: readonly string[]): string[] { return Array.from(new Set(values.map(normalizeText).filter(Boolean))).sort(compare); }
function sortById<T extends { id: string }>(values: T[]): T[] { return values.sort((a, b) => compare(a.id, b.id)); }
function earliest(values: readonly string[]): string { return values.slice().sort(compare)[0] ?? ""; }
function latest(values: readonly string[]): string { return values.slice().sort(compare).at(-1) ?? ""; }

function knowledgeSourceOrigin(entry: BusinessContextEntry): KnowledgeSourceOrigin { if (entry.source.sourceType === "user_edit" || entry.metadata.userEdited) return "user_edit"; if (entry.source.sourceType === "website") return "website"; if (entry.source.sourceType === "generated_qa") return "generated_qa"; return "manual_intake"; }
function entityTypeForCategory(category: BusinessContextCategory): BusinessEntityType { return ({ business_profile: "business", audience: "customer_segment", service: "service", pricing: "pricing_concept", policy: "policy", process: "process", differentiator: "differentiator", faq: "faq", behavior_rule: "other", prohibited_claim: "other" } as Record<BusinessContextCategory, BusinessEntityType>)[category]; }
function websiteEntityType(category: string): BusinessEntityType { return ({ company_overview: "general_knowledge", mission_value_proposition: "general_knowledge", business_identity: "business", industry: "general_knowledge", product: "product", service: "service", feature_capability: "service", pricing: "pricing_concept", pricing_plan: "pricing_concept", customer: "customer_segment", customer_segment: "customer_segment", industry_served: "customer_segment", primary_use_case: "general_knowledge", integration: "general_knowledge", ai_automation: "general_knowledge", technical_capability: "general_knowledge", security_compliance: "policy", certification: "general_knowledge", support_onboarding: "process", partnership: "general_knowledge", location: "location", location_service_area: "location", contact: "contact_method", contact_information: "contact_method", brand_voice_terminology: "general_knowledge", policy: "policy", process: "process", faq: "faq", differentiator: "differentiator", competitive_differentiator: "differentiator", guarantee: "guarantee", additional_business_knowledge: "general_knowledge" } as Record<string, BusinessEntityType>)[category] ?? "other"; }
function confidenceScore(level: Confidence["level"]): number { return level === "high" ? .9 : level === "medium" ? .7 : .5; }
function intakeLabel(session: AiBuilderSession, id: string): string | null { return session.intakeBlocks.find((block) => block.id === id)?.label ?? null; }

function contextAssertion(session: AiBuilderSession, entry: BusinessContextEntry, websiteFact: WebsiteKnowledgeFact | undefined, knowledge: PersistedWebsiteKnowledge | null | undefined): LegacyAssertion {
  const origin = knowledgeSourceOrigin(entry); const evidence = websiteFact?.evidence.map((item) => ({ url: item.url, excerpt: item.excerpt })) ?? (normalizeText(entry.source.excerpt) ? [{ url: entry.source.sourceUrl ?? null, excerpt: entry.source.excerpt }] : []);
  return { kind: "context", legacyEntryId: entry.id, identity: entry.id, entityIdentity: `${origin === "website" ? "website-restored" : "context"}:${websiteFact?.category ?? entry.category}:${normalizedIdentity(entry.title)}`, entityType: websiteFact ? websiteEntityType(websiteFact.category) : entityTypeForCategory(entry.category), name: normalizeText(entry.title), alias: normalizeText(entry.title), value: normalizeText(entry.content), tags: sortedUnique(entry.metadata.tags), confidence: { level: entry.confidence, score: entry.confidenceScore }, reviewState: entry.status, authority: entry.status === "corrected" ? "corrected" : entry.metadata.userEdited ? "confirmed" : origin === "generated_qa" ? "generated" : origin === "website" ? "observed" : "provided", source: { origin, sourceEntryId: entry.id, intakeBlockId: entry.source.intakeBlockId || null, url: entry.source.sourceUrl ?? null, label: intakeLabel(session, entry.source.intakeBlockId), capturedAt: entry.createdAt, crawlAttemptId: origin === "website" ? knowledge?.current_crawl_attempt_id ?? null : null, importedAt: origin === "website" ? knowledge?.imported_at ?? null : undefined }, evidence, createdAt: entry.createdAt, updatedAt: entry.updatedAt, faqSourceEntryIds: [] };
}
function faqAssertion(entry: GeneratedFaqEntry): LegacyAssertion { return { kind: "faq", legacyEntryId: entry.id, identity: entry.id, entityIdentity: `faq:${entry.id}`, entityType: "faq", name: normalizeText(entry.question), alias: normalizeText(entry.question), value: normalizeText(entry.answer), tags: ["faq"], confidence: { level: entry.confidence, score: entry.confidenceScore }, reviewState: entry.status, authority: entry.status === "corrected" ? "corrected" : "generated", source: { origin: "generated_qa", sourceEntryId: entry.id, intakeBlockId: null, url: null, label: "Generated FAQ", capturedAt: entry.createdAt, crawlAttemptId: null }, evidence: [], createdAt: entry.createdAt, updatedAt: entry.updatedAt, faqSourceEntryIds: sortedUnique(entry.sourceEntryIds) }; }
function websiteAssertions(projectId: string, knowledge: PersistedWebsiteKnowledge | null | undefined, restoredEntryIds: ReadonlySet<string>): LegacyAssertion[] { if (!knowledge) return []; const capturedAt = knowledge.imported_at ?? ""; const occurrences = new Map<string, number>(); return knowledge.knowledge.facts.filter((fact) => !restoredEntryIds.has(websiteFactIdentity(fact)) && !restoredEntryIds.has(websiteFactReviewIdentity(projectId, fact))).map((fact) => ({ fact, fingerprint: websiteFactFingerprint(fact) })).sort((a, b) => compare(a.fingerprint, b.fingerprint)).map(({ fact, fingerprint }) => { const occurrence = occurrences.get(fingerprint) ?? 0; occurrences.set(fingerprint, occurrence + 1); const identity = stableId("website_fact", [fingerprint, String(occurrence)]); return { kind: "website", legacyEntryId: null, identity, entityIdentity: `website:${fact.category}:${normalizedIdentity(fact.title)}`, entityType: websiteEntityType(fact.category), name: normalizeText(fact.title), alias: normalizeText(fact.title), value: normalizeText(fact.value), tags: [fact.category], confidence: { level: fact.confidence, score: confidenceScore(fact.confidence) }, reviewState: "proposed", authority: "observed", source: { origin: "website", sourceEntryId: null, intakeBlockId: "website_knowledge", url: knowledge.resolved_url ?? knowledge.requested_url, label: knowledge.resolved_url ?? knowledge.requested_url, capturedAt, crawlAttemptId: knowledge.current_crawl_attempt_id, importedAt: knowledge.imported_at, pageType: null }, evidence: fact.evidence.map((item) => ({ url: item.url, excerpt: item.excerpt })), createdAt: capturedAt, updatedAt: capturedAt, faqSourceEntryIds: [] }; }); }
function aliasPriority(detail: LegacyAssertion): number { const reviewed = detail.reviewState === "approved" || detail.reviewState === "corrected"; return reviewed && detail.source.origin === "user_edit" ? 0 : reviewed && detail.source.origin === "manual_intake" ? 1 : reviewed ? 2 : 3; }
function aggregateAliases(details: LegacyAssertion[]): string[] { const choices = new Map<string, { value: string; priority: number }>(); for (const detail of details) { const value = normalizeText(detail.alias); const key = normalizedIdentity(value); const candidate = { value, priority: aliasPriority(detail) }; const current = choices.get(key); if (key && (!current || candidate.priority < current.priority || candidate.priority === current.priority && compare(candidate.value, current.value) < 0)) choices.set(key, candidate); } return Array.from(choices.values()).map((item) => item.value).sort(compare); }
function preferredName(details: LegacyAssertion[]): string { return details.map((detail) => ({ value: normalizeText(detail.alias), priority: aliasPriority(detail) })).filter((item) => item.value).sort((a, b) => a.priority - b.priority || compare(a.value, b.value))[0]?.value ?? aggregateAliases(details)[0] ?? ""; }
function sortedMerges(merges: readonly EntityMergeContract[] | undefined): EntityMergeContract[] | undefined { return merges?.length ? merges.map((merge) => ({ ...merge, mergedEntityIds: sortedUnique(merge.mergedEntityIds), approvedAliases: sortedUnique(merge.approvedAliases) })).sort((a, b) => compare(`${a.canonicalEntityId}\0${a.mergedAt}`, `${b.canonicalEntityId}\0${b.mergedAt}`)) : undefined; }

/** Builds an isolated, deterministic projection and performs no production reads or writes. */
export function buildBusinessMemory(input: BuildBusinessMemoryInput): BusinessMemory {
  const factByRestoredId = new Map(input.websiteKnowledge?.knowledge.facts.flatMap((fact) => [[websiteFactIdentity(fact), fact] as const, [websiteFactReviewIdentity(input.session.id, fact), fact] as const]) ?? []); const restoredIds = new Set(input.session.contextEntries.filter((entry) => factByRestoredId.has(entry.id)).map((entry) => entry.id));
  const legacy = [...input.session.contextEntries.map((entry) => contextAssertion(input.session, entry, factByRestoredId.get(entry.id), input.websiteKnowledge)), ...input.session.faqEntries.map(faqAssertion), ...websiteAssertions(input.session.id, input.websiteKnowledge, restoredIds)].sort((a, b) => compare(`${a.kind}:${a.identity}`, `${b.kind}:${b.identity}`));
  const sources = new Map<string, KnowledgeSource>(); const evidence = new Map<string, EvidenceRecord>(); const assertions: BusinessAssertion[] = []; const details = new Map<string, LegacyAssertion>(); const entityByLegacy = new Map<string, string>(); const assertionByLegacy = new Map<string, string>();
  for (const item of legacy) { const entityId = stableId("business_entity", [input.session.id, item.entityType, item.entityIdentity]); const assertionId = stableId("business_assertion", [input.session.id, item.kind, item.identity]); if (item.legacyEntryId) { entityByLegacy.set(item.legacyEntryId, entityId); assertionByLegacy.set(item.legacyEntryId, assertionId); } const sourceIds: string[] = []; const evidenceIds: string[] = []; const variants = item.evidence.length ? item.evidence.map((record) => ({ ...item.source, url: record.url ?? item.source.url })) : [item.source]; for (const source of variants) { const pageType = input.websiteKnowledge?.pages.find((page) => page.url === source.url)?.pageType ?? source.pageType ?? null; const sourceRecord = { ...source, pageType }; const sourceId = stableId("knowledge_source", [input.session.id, assertionId, sourceRecord.origin, sourceRecord.sourceEntryId ?? "", sourceRecord.intakeBlockId ?? "", sourceRecord.url ?? "", sourceRecord.label ?? "", sourceRecord.crawlAttemptId ?? "", sourceRecord.capturedAt, sourceRecord.importedAt ?? "", pageType ?? ""]); sourceIds.push(sourceId); sources.set(sourceId, { id: sourceId, ...sourceRecord }); } for (const record of item.evidence) { const sourceId = sourceIds[variants.findIndex((source) => (source.url ?? "") === (record.url ?? item.source.url ?? ""))]; const evidenceId = stableId("evidence", [sourceId, record.url ?? "", record.excerpt, item.createdAt]); evidenceIds.push(evidenceId); evidence.set(evidenceId, { id: evidenceId, sourceId, excerpt: normalizeText(record.excerpt), url: record.url, capturedAt: item.createdAt }); } assertions.push({ id: assertionId, entityId, value: item.value, confidence: item.confidence, reviewState: item.reviewState, authority: item.authority, sourceIds: sortedUnique(sourceIds), evidenceIds: sortedUnique(evidenceIds), tags: sortedUnique(item.tags), legacyEntryId: item.legacyEntryId, createdAt: item.createdAt, updatedAt: item.updatedAt }); details.set(assertionId, item); }
  const owned = new Map<string, BusinessAssertion[]>(); for (const assertion of assertions) owned.set(assertion.entityId, [...(owned.get(assertion.entityId) ?? []), assertion]);
  const entities: BusinessEntity[] = Array.from(owned.entries()).map(([id, items]) => { const assertionDetails = items.map((item) => details.get(item.id)!); return { id, type: assertionDetails[0].entityType, name: preferredName(assertionDetails), aliases: aggregateAliases(assertionDetails), tags: sortedUnique(items.flatMap((item) => item.tags)), assertionIds: sortById(items.slice()).map((item) => item.id), sourceIds: sortedUnique(items.flatMap((item) => item.sourceIds)), evidenceIds: sortedUnique(items.flatMap((item) => item.evidenceIds)), createdAt: earliest(items.map((item) => item.createdAt)), updatedAt: latest(items.map((item) => item.updatedAt)) }; });
  const relationships: BusinessRelationship[] = legacy.flatMap((item) => item.kind !== "faq" || !item.legacyEntryId ? [] : item.faqSourceEntryIds.flatMap((sourceEntryId) => { const fromEntityId = entityByLegacy.get(sourceEntryId); const fromAssertionId = assertionByLegacy.get(sourceEntryId); const toEntityId = entityByLegacy.get(item.legacyEntryId!); const toAssertionId = assertionByLegacy.get(item.legacyEntryId!); return fromEntityId && fromAssertionId && toEntityId && toAssertionId ? [{ id: stableId("business_relationship", ["supports", fromEntityId, toEntityId, sourceEntryId, item.legacyEntryId!]), type: "supports", fromEntityId, toEntityId, fromAssertionId, toAssertionId, sourceEntryIds: [sourceEntryId], reviewState: item.reviewState, createdAt: item.createdAt, updatedAt: item.updatedAt }] : []; }));
  const relatedFor = (text: string) => assertions.filter((assertion) => normalizedIdentity(assertion.value) === normalizedIdentity(text) || normalizedIdentity(details.get(assertion.id)?.name) === normalizedIdentity(text));
  const conflicts: BusinessMemoryConflict[] = input.session.conflicts.map((conflict) => { const related = [...relatedFor(conflict.firstStatement), ...relatedFor(conflict.secondStatement)]; const relatedAssertions = sortById(Array.from(new Map(related.map((item) => [item.id, item])).values())); return { id: stableId("business_memory_conflict", [input.session.id, conflict.id]), projectId: input.session.id, topic: conflict.topic, conflictingStatements: sortedUnique([conflict.firstStatement, conflict.secondStatement]), relatedEntityIds: sortedUnique(relatedAssertions.map((item) => item.entityId)), relatedAssertionIds: relatedAssertions.map((item) => item.id), sourceIds: sortedUnique(relatedAssertions.flatMap((item) => item.sourceIds)), evidenceIds: sortedUnique(relatedAssertions.flatMap((item) => item.evidenceIds)), suggestedClarificationQuestion: conflict.suggestedQuestion, resolved: conflict.resolved, resolution: conflict.resolution ?? null, createdAt: input.session.createdAt, updatedAt: input.session.updatedAt }; });
  const missingInformation: BusinessMemoryMissingInformation[] = input.session.missingInformation.map((item) => ({ id: stableId("business_memory_missing_information", [input.session.id, item.id]), projectId: input.session.id, topic: item.topic, reason: item.reason, suggestedQuestion: item.suggestedQuestion, relatedEntityTypes: [], relatedEntityIds: [], relatedAssertionIds: [], resolved: item.resolved, createdAt: input.session.createdAt, updatedAt: input.session.updatedAt }));
  const assistantSource = input.session.assistantConfiguration as typeof input.session.assistantConfiguration & { behaviorRules?: string[]; prohibitedClaims?: string[] }; const assistant = { ...assistantSource, escalationInstructions: [...assistantSource.escalationInstructions], ...(assistantSource.behaviorRules ? { behaviorRules: [...assistantSource.behaviorRules] } : {}), ...(assistantSource.prohibitedClaims ? { prohibitedClaims: [...assistantSource.prohibitedClaims] } : {}) };
  const entityMerges = sortedMerges(input.entityMerges); return { id: stableId("business_memory", [input.session.id]), schemaVersion: BUSINESS_MEMORY_SCHEMA_VERSION, projectId: input.session.id, assistant, entities: sortById(entities), assertions: sortById(assertions), relationships: sortById(relationships), sources: sortById(Array.from(sources.values())), evidence: sortById(Array.from(evidence.values())), conflicts: sortById(conflicts), missingInformation: sortById(missingInformation), ...(entityMerges ? { entityMerges } : {}), createdAt: input.session.createdAt, updatedAt: latest([input.session.updatedAt, input.websiteKnowledge?.imported_at ?? "", ...assertions.map((item) => item.updatedAt)]) };
}
