import assert from "node:assert/strict";
import test from "node:test";
import { retrieveStructuredCanonicalKnowledge } from "./structuredCanonicalRetrieval";
import type { AssistantProjection } from "../assistant-projection/contracts";

const item = (id: string, entityType: "service" | "pricing_concept" | "policy" | "faq", title: string, value: string, overrides = {}) => ({ id, entityId: `entity-${id}`, assertionId: `assertion-${id}`, entityType, title, value, aliases: [], tags: [], confidence: { level: "high" as const, score: .9 }, authority: "confirmed" as const, reviewState: "approved" as const, evidenceIds: [], sourceIds: [], ...overrides });
function projection(): AssistantProjection { const service = item("service", "service", "Website Design", "We build websites", { aliases: ["web design"] }); const price = item("price", "pricing_concept", "Website pricing", "Packages begin at $100"); const policy = item("policy", "policy", "Refund policy", "Deposits are non-refundable"); const faq = { ...item("faq", "faq", "How much does a website cost?", "Website packages begin at $100"), question: "How much does a website cost?", answer: "Website packages begin at $100" }; return { projectId: "p", businessMemoryFingerprint: "business_memory_abcdef0123456789abcdef01", projectionVersion: 1, schemaVersion: 1, identity: { status: "resolved", canonicalEntityId: "business", businessName: "Acme Studio", aliases: ["Acme"], mergedEntityIds: [], redirectedEntityIds: [], contactEntityIds: [] }, assistant: { name: "A", purpose: "Help", tone: "warm", responseStyle: "brief", primaryAudience: null, escalationInstructions: [] }, services: [service], pricing: [price], policies: [policy], faqs: [faq], restrictions: [{ id: "restriction", type: "prohibited_claim", instruction: "Do not promise guaranteed rankings.", relatedEntityIds: [], relatedAssertionIds: [], evidenceIds: [], sourceIds: [], reviewState: "approved" }], relationships: [{ id: "rel", type: "has_pricing", sourceEntityId: service.entityId, targetEntityId: price.entityId, sourceAssertionId: service.assertionId, targetAssertionId: price.assertionId, sourceEntryIds: ["entry"], sourceIds: [], evidenceIds: [], reviewState: "approved" }], sources: [], evidence: [], missingInformation: [] }; }

test("structured retrieval reads validated Assistant Projection directly and recognizes canonical categories", () => { const result = retrieveStructuredCanonicalKnowledge(projection(), "Website Design"); assert.equal(result.items[0].projectionItemId, "service"); assert.equal(result.items[0].assertionId, "assertion-service"); assert.equal(result.items[0].entityId, "entity-service"); assert.equal(result.engineVersion, "10A.1"); });
test("aliases, pricing, policy, FAQ, restrictions, and relationship support rank deterministically", () => { assert.equal(retrieveStructuredCanonicalKnowledge(projection(), "web design").items[0].projectionItemId, "service"); assert.equal(retrieveStructuredCanonicalKnowledge(projection(), "What is the website price?").items[0].category, "pricing"); assert.equal(retrieveStructuredCanonicalKnowledge(projection(), "What is your refund policy?").items[0].category, "policy"); assert.equal(retrieveStructuredCanonicalKnowledge(projection(), "How much does a website cost?").items[0].category, "faq"); const related = retrieveStructuredCanonicalKnowledge(projection(), "Website Design"); assert.ok(related.items.some(x => x.relationshipIds.includes("rel"))); assert.equal(retrieveStructuredCanonicalKnowledge(projection(), "What claims are prohibited?").items[0].category, "restriction"); });
test("invalid non-authoritative projection content fails closed", () => { const invalid = projection(); invalid.services[0].reviewState = "proposed" as never; assert.throws(() => retrieveStructuredCanonicalKnowledge(invalid, "website"), /non_authoritative/); });
test("direct evidence is retained and boosts an otherwise equal item", () => { const p = projection(); p.sources = [{ id: "source", origin: "manual_intake", url: null, label: null, capturedAt: "2026-07-20T00:00:00.000Z", crawlAttemptId: null }]; p.evidence = [{ id: "evidence", canonicalSourceId: "source", sourceUrl: null, excerpt: "Website design", capturedAt: "2026-07-20T00:00:00.000Z" }]; p.services[0].evidenceIds = ["evidence"]; p.services[0].sourceIds = ["source"]; const result = retrieveStructuredCanonicalKnowledge(p, "build websites"); assert.deepEqual(result.items[0].evidenceIds, ["evidence"]); assert.deepEqual(result.sources.map(x => x.id), ["source"]); });
