import type { AssistantProjection, AssistantProjectionEvidence, AssistantProjectionRelationship, AssistantProjectionSource, AssistantProjectionTextKnowledgeItem } from "../assistant-projection/contracts";
import { validateAssistantProjectionRuntime } from "../assistant-projection/validation";

export const STRUCTURED_RETRIEVAL_ENGINE_VERSION = "10A.3";
export const STRUCTURED_RETRIEVAL_LIMITS = { directMatches: 8, relationshipExpansions: 4, evidence: 12, sources: 12, total: 12 } as const;
export const STRUCTURED_RETRIEVAL_WEIGHTS = { term: 8, exactTitle: 40, alias: 32, intent: 40, faqQuestion: 28, authority: { corrected: 18, confirmed: 14, provided: 10, observed: 7, generated: 2 }, confidence: 12, directEvidence: 10, sourceQuality: 8, recency: 4, relationship: 9, restriction: 24, correctedPrecedence: 50 } as const;
type Category = "identity" | "service" | "product" | "pricing" | "policy" | "faq" | "restriction" | "missing_information";
type SelectedItem = AssistantProjectionTextKnowledgeItem | AssistantProjection["restrictions"][number];
type IdentityItem = { kind: "identity"; canonicalEntityId: string | null; businessName: string | null; aliases: string[]; status: AssistantProjection["identity"]["status"] };
type MissingItem = AssistantProjection["missingInformation"][number];
export type RetrievalQueryAnalysis = { normalizedTerms: string[]; exactPhrases: string[]; intent: "general" | "service" | "product" | "pricing" | "policy" | "restriction" | "relationship" | "missing_information"; entityOrAliasTerms: string[] };
export type StructuredCanonicalRetrievalItem = { category: Category; item: SelectedItem | IdentityItem | MissingItem; projectionItemId: string; assertionId: string | null; entityId: string | null; predecessorAssertionId: string | null; evidenceIds: string[]; sourceIds: string[]; provenance: AssistantProjectionTextKnowledgeItem["provenance"] | null; score: number; factors: Record<string, number>; relationshipIds: string[]; relatedAssertionIds: string[]; relatedEntityIds: string[]; direct: boolean };
export type StructuredCanonicalRetrievalResult = { engineVersion: typeof STRUCTURED_RETRIEVAL_ENGINE_VERSION; query: RetrievalQueryAnalysis; items: StructuredCanonicalRetrievalItem[]; evidence: AssistantProjectionEvidence[]; sources: AssistantProjectionSource[]; relationships: AssistantProjectionRelationship[]; diagnostics: { retrievalDurationMs: number; totalCandidateCount: number; directCandidateCount: number; relationshipCandidateCount: number; relationshipExpansionCount: number; evidenceSelectedCount: number; sourceSelectedCount: number; selectedDirectCount: number; selectedRelatedCount: number; selectedCategoryCounts: Record<string, number>; topScoreBands: number[] } };
const tokens = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().split(/\s+/).filter(Boolean);
const quality: Record<string, number> = { user_edit: 1, manual_intake: .85, website: .75, imported_data: .55, generated_qa: .35, generated: .2, system: .1 };
const phraseMatch = (query: string, value: string) => { const q = query.toLowerCase().trim(), v = value.toLowerCase().trim(); const qt = tokens(q), vt = tokens(v); return !!q && (q === v || q.includes(v) || v.includes(q) || (vt.length > 1 && vt.every(t => qt.includes(t))) || (qt.length > 1 && qt.every(t => vt.includes(t)))); };
function analyze(message: string, projection: AssistantProjection): RetrievalQueryAnalysis { const lower = message.toLowerCase(), normalizedTerms = tokens(message), exactPhrases = [lower.trim()].filter(Boolean); const intent = /unknown|unavailable|missing|not (known|available)|don.t have/.test(lower) ? "missing_information" : /price|pricing|cost|fee|quote|rate/.test(lower) ? "pricing" : /policy|refund|cancel|privacy|terms/.test(lower) ? "policy" : /cannot|can.t|prohibit|restriction|allowed/.test(lower) ? "restriction" : /related|relationship|connect|include/.test(lower) ? "relationship" : /product|item|catalog/.test(lower) ? "product" : /service|offer|provide/.test(lower) ? "service" : "general"; const names = [projection.identity.businessName, ...projection.identity.aliases, ...projection.services.flatMap(x => [x.title, ...x.aliases]), ...projection.products.flatMap(x => [x.title, ...x.aliases]), ...projection.pricing.flatMap(x => [x.title, ...x.aliases])].filter((x): x is string => Boolean(x)); return { normalizedTerms, exactPhrases, intent, entityOrAliasTerms: names.filter(name => phraseMatch(lower, name)) }; }
function sourceScore(ids: string[], sources: Map<string, AssistantProjectionSource>) { return Math.max(0, ...ids.map(id => quality[sources.get(id)?.origin ?? ""] ?? 0)) * STRUCTURED_RETRIEVAL_WEIGHTS.sourceQuality; }
function boundedRecency(dates: (string | undefined)[]) { const valid = dates.map(x => x ? Date.parse(x) : NaN).filter(Number.isFinite); if (!valid.length) return 0; return Math.max(0, 1 - Math.max(0, Date.now() - Math.max(...valid)) / (365 * 86400000)) * STRUCTURED_RETRIEVAL_WEIGHTS.recency; }
function recency(evidenceIds: string[], sourceIds: string[], evidence: Map<string, AssistantProjectionEvidence>, sources: Map<string, AssistantProjectionSource>, correction?: string | null) { return Math.min(STRUCTURED_RETRIEVAL_WEIGHTS.recency, boundedRecency(evidenceIds.map(id => evidence.get(id)?.capturedAt)) + boundedRecency(sourceIds.map(id => sources.get(id)?.capturedAt)) + boundedRecency(correction ? [correction] : [])); }
function categoryFor(item: AssistantProjectionTextKnowledgeItem): Category { return item.entityType === "product" ? "product" : item.entityType === "pricing_concept" ? "pricing" : item.entityType as Category; }
function scoreText(text: string, query: RetrievalQueryAnalysis) { return query.normalizedTerms.filter(t => text.toLowerCase().includes(t)).length * STRUCTURED_RETRIEVAL_WEIGHTS.term; }
function scoreItem(item: AssistantProjectionTextKnowledgeItem, query: RetrievalQueryAnalysis, evidence: Map<string, AssistantProjectionEvidence>, sources: Map<string, AssistantProjectionSource>) { const factors: Record<string, number> = {}; const text = `${item.title} ${item.value} ${item.aliases.join(" ")} ${item.tags.join(" ")}`; const relevance = scoreText(text, query); if (relevance) factors.textualRelevance = relevance; if (query.exactPhrases.some(x => x === item.title.toLowerCase())) factors.exactTitle = STRUCTURED_RETRIEVAL_WEIGHTS.exactTitle; if (item.aliases.some(a => phraseMatch(query.exactPhrases[0] ?? "", a))) factors.alias = STRUCTURED_RETRIEVAL_WEIGHTS.alias; if ((query.intent === "pricing" && item.entityType === "pricing_concept") || (query.intent === "policy" && item.entityType === "policy") || (query.intent === "service" && item.entityType === "service") || (query.intent === "product" && item.entityType === "product")) factors.intent = STRUCTURED_RETRIEVAL_WEIGHTS.intent; if (item.entityType === "faq" && relevance >= 16) factors.faqQuestion = STRUCTURED_RETRIEVAL_WEIGHTS.faqQuestion; factors.authority = STRUCTURED_RETRIEVAL_WEIGHTS.authority[item.authority]; factors.confidence = item.confidence.score * STRUCTURED_RETRIEVAL_WEIGHTS.confidence; if (item.evidenceIds.length) factors.directEvidence = STRUCTURED_RETRIEVAL_WEIGHTS.directEvidence; factors.sourceQuality = sourceScore(item.sourceIds, sources); factors.recency = recency(item.evidenceIds, item.sourceIds, evidence, sources, item.provenance?.correctedAt); return { score: Object.values(factors).reduce((a,b)=>a+b,0), factors }; }
function canonicalItem(category: Category, item: SelectedItem, score: number, factors: Record<string, number>, direct: boolean, relationshipIds: string[] = []): StructuredCanonicalRetrievalItem { const text = "assertionId" in item; return { category, item, projectionItemId: item.id, assertionId: text ? item.assertionId : item.relatedAssertionIds[0] ?? null, entityId: text ? item.entityId : item.relatedEntityIds[0] ?? null, predecessorAssertionId: text ? item.predecessorAssertionId ?? null : null, evidenceIds: [...item.evidenceIds], sourceIds: [...item.sourceIds], provenance: text ? item.provenance ?? null : null, score, factors, relationshipIds, relatedAssertionIds: text ? [item.assertionId] : [...item.relatedAssertionIds], relatedEntityIds: text ? [item.entityId] : [...item.relatedEntityIds], direct }; }
const order = (a: StructuredCanonicalRetrievalItem,b: StructuredCanonicalRetrievalItem) => b.score-a.score || Number(b.direct)-Number(a.direct) || a.projectionItemId.localeCompare(b.projectionItemId);
export function retrieveStructuredCanonicalKnowledge(projection: AssistantProjection, message: string): StructuredCanonicalRetrievalResult { const started = Date.now(); validateAssistantProjectionRuntime(projection); const query=analyze(message,projection), evidence=new Map(projection.evidence.map(x=>[x.id,x])), sources=new Map(projection.sources.map(x=>[x.id,x])); const textItems=[...projection.services,...projection.products,...projection.pricing,...projection.policies,...projection.faqs]; const direct=textItems.map(i=>{const s=scoreItem(i,query,evidence,sources);return canonicalItem(categoryFor(i),i,s.score,s.factors,true)}).filter(x=>x.factors.exactTitle||x.factors.alias||x.factors.intent||x.factors.faqQuestion||(x.factors.textualRelevance??0)>=16);
 for(const r of projection.restrictions){ const instructionMatch=scoreText(r.instruction,query); const exactInstruction=query.exactPhrases.some(x=>phraseMatch(x,r.instruction)); const linked=direct.some(x=>r.relatedEntityIds.includes(x.entityId ?? "")||r.relatedAssertionIds.includes(x.assertionId ?? "")); const relevance=instructionMatch+(exactInstruction?STRUCTURED_RETRIEVAL_WEIGHTS.exactTitle:0)+(linked?STRUCTURED_RETRIEVAL_WEIGHTS.relationship:0); if(relevance>0) direct.push(canonicalItem("restriction",r,relevance+sourceScore(r.sourceIds,sources)+(r.evidenceIds.length?10:0)+(query.intent==="restriction"?STRUCTURED_RETRIEVAL_WEIGHTS.restriction:0),{textualRelevance:instructionMatch,...(exactInstruction?{exactInstruction:STRUCTURED_RETRIEVAL_WEIGHTS.exactTitle}:{}),...(linked?{relatedKnowledge:STRUCTURED_RETRIEVAL_WEIGHTS.relationship}:{}),...(query.intent==="restriction"?{restrictionIntent:STRUCTURED_RETRIEVAL_WEIGHTS.restriction}:{})},true));}
 if(projection.identity.businessName && [projection.identity.businessName,...projection.identity.aliases].some(n=>phraseMatch(message,n))) direct.push({category:"identity",item:{kind:"identity",canonicalEntityId:projection.identity.canonicalEntityId,businessName:projection.identity.businessName,aliases:[...projection.identity.aliases],status:projection.identity.status},projectionItemId:"identity",assertionId:null,entityId:projection.identity.canonicalEntityId,predecessorAssertionId:null,evidenceIds:[],sourceIds:[],provenance:null,score:40,factors:{entityMatch:40},relationshipIds:[],relatedAssertionIds:[],relatedEntityIds:projection.identity.canonicalEntityId?[projection.identity.canonicalEntityId]:[],direct:true});
 for(const m of projection.missingInformation.filter(m=>!m.resolved && (query.intent==="missing_information" || scoreText(`${m.topic} ${m.reason}`,query)>=8))) direct.push({category:"missing_information",item:m,projectionItemId:m.id,assertionId:null,entityId:m.relatedEntityIds[0]??null,predecessorAssertionId:null,evidenceIds:[],sourceIds:[],provenance:null,score:scoreText(`${m.topic} ${m.reason}`,query)+20,factors:{missingInformation:20},relationshipIds:[],relatedAssertionIds:[...m.relatedAssertionIds],relatedEntityIds:[...m.relatedEntityIds],direct:true});
 const corrected=new Set(textItems.filter(i=>i.reviewState==="corrected"&&i.predecessorAssertionId).map(i=>i.predecessorAssertionId!)); for(const x of direct) if(x.item && "reviewState" in x.item && x.item.reviewState==="corrected") {x.score+=50;x.factors.correctedPrecedence=50;} const ranked=direct.filter(x=>/history|original|previous|before/.test(message)||!x.assertionId||!corrected.has(x.assertionId)).sort(order); const directIds=new Set(ranked.slice(0,8).map(x=>x.assertionId).filter(Boolean)); const expansionByAssertion=new Map<string,StructuredCanonicalRetrievalItem>(); let relationshipCandidateCount=0;
 for(const rel of projection.relationships){const endpoint=directIds.has(rel.sourceAssertionId)?rel.targetAssertionId:directIds.has(rel.targetAssertionId)?rel.sourceAssertionId:null;if(!endpoint||directIds.has(endpoint))continue;const target=textItems.find(x=>x.assertionId===endpoint);if(!target)continue;relationshipCandidateCount++;const s=scoreItem(target,query,evidence,sources), prior=expansionByAssertion.get(endpoint);if(prior){prior.relationshipIds.push(rel.id);continue} expansionByAssertion.set(endpoint,canonicalItem(categoryFor(target),target,s.score+9,{...s.factors,relationship:9},false,[rel.id]));}
 const expansions=Array.from(expansionByAssertion.values()).map(x=>({...x,relationshipIds:x.relationshipIds.sort()})).sort(order).slice(0,4); const selected=[...ranked.slice(0,8),...expansions].sort(order).slice(0,12); const selectedEvidence=Array.from(new Set(selected.flatMap(x=>x.evidenceIds))).map(id=>evidence.get(id)).filter((x):x is AssistantProjectionEvidence=>!!x).sort((a,b)=>{const ac=selected.filter(x=>x.evidenceIds.includes(a.id)).length,bc=selected.filter(x=>x.evidenceIds.includes(b.id)).length;return bc-ac||Date.parse(b.capturedAt)-Date.parse(a.capturedAt)||Number(!!b.excerpt)-Number(!!a.excerpt)||a.id.localeCompare(b.id)}).slice(0,12); const selectedSources=Array.from(new Set([...selected.flatMap(x=>x.sourceIds),...selectedEvidence.map(x=>x.canonicalSourceId)])).map(id=>sources.get(id)).filter((x):x is AssistantProjectionSource=>!!x).sort((a,b)=>{const ac=selected.filter(x=>x.sourceIds.includes(a.id)).length,bc=selected.filter(x=>x.sourceIds.includes(b.id)).length;return (quality[b.origin]-quality[a.origin])||bc-ac||Date.parse(b.capturedAt)-Date.parse(a.capturedAt)||a.id.localeCompare(b.id)}).slice(0,12);
 return {engineVersion:STRUCTURED_RETRIEVAL_ENGINE_VERSION,query,items:selected,evidence:selectedEvidence,sources:selectedSources,relationships:projection.relationships.filter(r=>selected.some(x=>x.relationshipIds.includes(r.id))),diagnostics:{retrievalDurationMs:Date.now()-started,totalCandidateCount:direct.length+relationshipCandidateCount,directCandidateCount:ranked.length,relationshipCandidateCount,relationshipExpansionCount:expansions.length,evidenceSelectedCount:selectedEvidence.length,sourceSelectedCount:selectedSources.length,selectedDirectCount:selected.filter(x=>x.direct).length,selectedRelatedCount:selected.filter(x=>!x.direct).length,selectedCategoryCounts:selected.reduce<Record<string,number>>((a,x)=>({...a,[x.category]:(a[x.category]??0)+1}),{}),topScoreBands:selected.slice(0,3).map(x=>Math.round(x.score))}};
}
