import type { AssistantProjection, AssistantProjectionEvidence, AssistantProjectionRelationship, AssistantProjectionSource, AssistantProjectionTextKnowledgeItem } from "../assistant-projection/contracts";
import { validateAssistantProjectionRuntime } from "../assistant-projection/validation";

export const STRUCTURED_RETRIEVAL_ENGINE_VERSION = "10A.1";
export const STRUCTURED_RETRIEVAL_LIMITS = { directMatches: 8, relationshipExpansions: 4, evidence: 12, sources: 12, total: 12 } as const;
/** Named, additive scoring factors. Authority/revision bonuses intentionally exceed bounded recency. */
export const STRUCTURED_RETRIEVAL_WEIGHTS = { term: 8, exactTitle: 40, alias: 32, intent: 40, faqQuestion: 28, authority: { corrected: 18, confirmed: 14, provided: 10, observed: 7, generated: 2 }, confidence: 12, directEvidence: 10, sourceQuality: 8, recency: 4, relationship: 9, restriction: 24, correctedPrecedence: 50 } as const;

type Category = "identity" | "service" | "product" | "pricing" | "policy" | "faq" | "restriction" | "missing_information";
type SelectedItem = AssistantProjectionTextKnowledgeItem | AssistantProjection["restrictions"][number];
export type RetrievalQueryAnalysis = { normalizedTerms: string[]; exactPhrases: string[]; intent: "general" | "service" | "pricing" | "policy" | "restriction" | "relationship"; entityOrAliasTerms: string[] };
export type StructuredCanonicalRetrievalItem = { category: Category; item: SelectedItem; projectionItemId: string; assertionId: string | null; entityId: string | null; predecessorAssertionId: string | null; evidenceIds: string[]; sourceIds: string[]; provenance: AssistantProjectionTextKnowledgeItem["provenance"] | null; score: number; factors: Record<string, number>; relationshipIds: string[]; relatedAssertionIds: string[]; relatedEntityIds: string[]; direct: boolean };
export type StructuredCanonicalRetrievalResult = { engineVersion: typeof STRUCTURED_RETRIEVAL_ENGINE_VERSION; query: RetrievalQueryAnalysis; items: StructuredCanonicalRetrievalItem[]; evidence: AssistantProjectionEvidence[]; sources: AssistantProjectionSource[]; relationships: AssistantProjectionRelationship[]; diagnostics: { directCandidateCount: number; relationshipExpansionCount: number; selectedCategoryCounts: Record<string, number>; topScoreBands: number[] }; };

const tokens = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().split(/\s+/).filter(Boolean);
const quality: Record<string, number> = { user_edit: 1, manual_intake: .85, website: .75, imported_data: .55, generated_qa: .35, generated: .2, system: .1 };
function analyze(message: string, projection: AssistantProjection): RetrievalQueryAnalysis {
 const lower = message.toLowerCase(); const normalizedTerms = tokens(message); const exactPhrases = [message.trim().toLowerCase()].filter(Boolean);
 const intent = /price|pricing|cost|fee|quote|rate/.test(lower) ? "pricing" : /policy|refund|cancel|privacy|terms/.test(lower) ? "policy" : /cannot|can.t|prohibit|restriction|allowed/.test(lower) ? "restriction" : /related|relationship|connect|include/.test(lower) ? "relationship" : /service|offer|provide|product/.test(lower) ? "service" : "general";
 const names = [projection.identity.businessName, ...projection.identity.aliases, ...projection.services.flatMap(x => [x.title, ...x.aliases]), ...projection.pricing.flatMap(x => [x.title, ...x.aliases])].filter((x): x is string => Boolean(x));
 return { normalizedTerms, exactPhrases, intent, entityOrAliasTerms: names.filter(name => lower.includes(name.toLowerCase())) };
}
function sourceScore(ids: string[], sources: Map<string, AssistantProjectionSource>) { return Math.max(0, ...ids.map(id => quality[sources.get(id)?.origin ?? ""] ?? 0)) * STRUCTURED_RETRIEVAL_WEIGHTS.sourceQuality; }
function recency(ids: string[], evidence: Map<string, AssistantProjectionEvidence>, sources: Map<string, AssistantProjectionSource>) { const dates = ids.map(id => evidence.get(id)?.capturedAt ?? sources.get(id)?.capturedAt).map(x => x ? Date.parse(x) : NaN).filter(Number.isFinite); if (!dates.length) return 0; const age = Math.max(0, Date.now() - Math.max(...dates)); return Math.max(0, 1 - age / (365 * 86400000)) * STRUCTURED_RETRIEVAL_WEIGHTS.recency; }
function categoryFor(item: AssistantProjectionTextKnowledgeItem): Category { return item.entityType === "product" ? "product" : item.entityType === "pricing_concept" ? "pricing" : item.entityType as Category; }
function scoreItem(item: AssistantProjectionTextKnowledgeItem, query: RetrievalQueryAnalysis, evidence: Map<string, AssistantProjectionEvidence>, sources: Map<string, AssistantProjectionSource>): { score: number; factors: Record<string, number> } {
 const haystack = `${item.title} ${item.value} ${item.aliases.join(" ")} ${item.tags.join(" ")}`.toLowerCase(); const factors: Record<string, number> = {};
 const matchingTerms = query.normalizedTerms.filter(term => haystack.includes(term)).length; if (matchingTerms) factors.textualRelevance = matchingTerms * STRUCTURED_RETRIEVAL_WEIGHTS.term;
 if (query.exactPhrases.some(phrase => phrase === item.title.toLowerCase())) factors.exactTitle = STRUCTURED_RETRIEVAL_WEIGHTS.exactTitle;
 if (item.aliases.some(alias => query.normalizedTerms.includes(alias.toLowerCase()) || query.exactPhrases.includes(alias.toLowerCase()))) factors.alias = STRUCTURED_RETRIEVAL_WEIGHTS.alias;
 if ((query.intent === "pricing" && item.entityType === "pricing_concept") || (query.intent === "policy" && item.entityType === "policy") || (query.intent === "service" && ["service", "product"].includes(item.entityType))) factors.intent = STRUCTURED_RETRIEVAL_WEIGHTS.intent;
 if (item.entityType === "faq" && (query.exactPhrases.includes(item.title.toLowerCase()) || query.normalizedTerms.filter(term => item.title.toLowerCase().includes(term)).length >= 2)) factors.faqQuestion = STRUCTURED_RETRIEVAL_WEIGHTS.faqQuestion;
 factors.authority = STRUCTURED_RETRIEVAL_WEIGHTS.authority[item.authority]; factors.confidence = Math.max(0, Math.min(1, item.confidence.score)) * STRUCTURED_RETRIEVAL_WEIGHTS.confidence;
 if (item.evidenceIds.length) factors.directEvidence = STRUCTURED_RETRIEVAL_WEIGHTS.directEvidence;
 factors.sourceQuality = sourceScore(item.sourceIds, sources); factors.recency = recency([...item.evidenceIds, ...item.sourceIds], evidence, sources);
 return { score: Object.values(factors).reduce((a,b) => a+b, 0), factors };
}
function canonicalItem(category: Category, item: SelectedItem, score: number, factors: Record<string, number>, direct: boolean, relationshipIds: string[] = []): StructuredCanonicalRetrievalItem {
 const text = "assertionId" in item; return { category, item, projectionItemId: item.id, assertionId: text ? item.assertionId : item.relatedAssertionIds[0] ?? null, entityId: text ? item.entityId : item.relatedEntityIds[0] ?? null, predecessorAssertionId: text ? item.predecessorAssertionId ?? null : null, evidenceIds: [...item.evidenceIds], sourceIds: [...item.sourceIds], provenance: text ? item.provenance ?? null : null, score, factors, relationshipIds, relatedAssertionIds: text ? [item.assertionId] : [...item.relatedAssertionIds], relatedEntityIds: text ? [item.entityId] : [...item.relatedEntityIds], direct };
}
export function retrieveStructuredCanonicalKnowledge(projection: AssistantProjection, message: string): StructuredCanonicalRetrievalResult {
 validateAssistantProjectionRuntime(projection); const query = analyze(message, projection); const evidence = new Map(projection.evidence.map(x => [x.id, x])); const sources = new Map(projection.sources.map(x => [x.id, x]));
 const textItems = [...projection.services, ...projection.pricing, ...projection.policies, ...projection.faqs];
 const direct = textItems.map(item => { const s = scoreItem(item, query, evidence, sources); return canonicalItem(categoryFor(item), item, s.score, s.factors, true); }).filter(x => x.factors.exactTitle || x.factors.alias || x.factors.intent || x.factors.faqQuestion || (x.factors.textualRelevance ?? 0) >= STRUCTURED_RETRIEVAL_WEIGHTS.term * 2);
 if (query.intent === "restriction") for (const item of projection.restrictions) direct.push(canonicalItem("restriction", item, STRUCTURED_RETRIEVAL_WEIGHTS.restriction, { restriction: STRUCTURED_RETRIEVAL_WEIGHTS.restriction }, true));
 if (query.normalizedTerms.some(term => projection.identity.businessName?.toLowerCase().includes(term) || projection.identity.aliases.some(alias => alias.toLowerCase().includes(term)))) direct.push({ category: "identity", item: { id: "identity", type: "behavior_rule", instruction: projection.identity.businessName ?? "Business identity", relatedEntityIds: projection.identity.canonicalEntityId ? [projection.identity.canonicalEntityId] : [], relatedAssertionIds: [], evidenceIds: [], sourceIds: [], reviewState: "approved" }, projectionItemId: "identity", assertionId: null, entityId: projection.identity.canonicalEntityId, predecessorAssertionId: null, evidenceIds: [], sourceIds: [], provenance: null, score: STRUCTURED_RETRIEVAL_WEIGHTS.exactTitle, factors: { entityMatch: STRUCTURED_RETRIEVAL_WEIGHTS.exactTitle }, relationshipIds: [], relatedAssertionIds: [], relatedEntityIds: projection.identity.canonicalEntityId ? [projection.identity.canonicalEntityId] : [], direct: true });
 const correctedPredecessors = new Set(textItems.filter(item => item.reviewState === "corrected" && item.predecessorAssertionId).map(item => item.predecessorAssertionId as string));
 for (const candidate of direct) if (candidate.item && "reviewState" in candidate.item && candidate.item.reviewState === "corrected" && candidate.predecessorAssertionId) { candidate.score += STRUCTURED_RETRIEVAL_WEIGHTS.correctedPrecedence; candidate.factors.correctedPrecedence = STRUCTURED_RETRIEVAL_WEIGHTS.correctedPrecedence; }
 const historyRequested = /history|original|previous|before/.test(message.toLowerCase());
 const rankedDirect = historyRequested ? direct : direct.filter(candidate => !candidate.assertionId || !correctedPredecessors.has(candidate.assertionId));
 rankedDirect.sort((a,b) => b.score-a.score || a.projectionItemId.localeCompare(b.projectionItemId));
 const directIds = new Set(rankedDirect.slice(0, STRUCTURED_RETRIEVAL_LIMITS.directMatches).map(x => x.assertionId).filter(Boolean)); const expansions: StructuredCanonicalRetrievalItem[] = [];
 for (const relationship of projection.relationships) { if (expansions.length >= STRUCTURED_RETRIEVAL_LIMITS.relationshipExpansions) break; const endpoint = directIds.has(relationship.sourceAssertionId) ? relationship.targetAssertionId : directIds.has(relationship.targetAssertionId) ? relationship.sourceAssertionId : null; if (!endpoint || directIds.has(endpoint)) continue; const target = textItems.find(x => x.assertionId === endpoint); if (!target) continue; const s = scoreItem(target, query, evidence, sources); expansions.push(canonicalItem(categoryFor(target), target, s.score + STRUCTURED_RETRIEVAL_WEIGHTS.relationship, { ...s.factors, relationship: STRUCTURED_RETRIEVAL_WEIGHTS.relationship }, false, [relationship.id])); }
 const selected = [...rankedDirect.slice(0, STRUCTURED_RETRIEVAL_LIMITS.directMatches), ...expansions].sort((a,b) => b.score-a.score || a.projectionItemId.localeCompare(b.projectionItemId)).slice(0, STRUCTURED_RETRIEVAL_LIMITS.total);
 const selectedEvidence = Array.from(new Set(selected.flatMap(x => x.evidenceIds))).map(id => evidence.get(id)).filter((x): x is AssistantProjectionEvidence => Boolean(x)).slice(0, STRUCTURED_RETRIEVAL_LIMITS.evidence); const selectedSources = Array.from(new Set(selected.flatMap(x => x.sourceIds).concat(selectedEvidence.map(x => x.canonicalSourceId)))).map(id => sources.get(id)).filter((x): x is AssistantProjectionSource => Boolean(x)).slice(0, STRUCTURED_RETRIEVAL_LIMITS.sources);
 return { engineVersion: STRUCTURED_RETRIEVAL_ENGINE_VERSION, query, items: selected, evidence: selectedEvidence, sources: selectedSources, relationships: projection.relationships.filter(r => selected.some(x => x.relationshipIds.includes(r.id))), diagnostics: { directCandidateCount: rankedDirect.length, relationshipExpansionCount: expansions.length, selectedCategoryCounts: selected.reduce<Record<string, number>>((a,x) => ({...a,[x.category]:(a[x.category]??0)+1}),{}), topScoreBands: selected.slice(0,3).map(x => Math.round(x.score)) } };
}
