import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "@neondatabase/serverless";
import { reconcileTrustedKnowledgeProjectionForProject, TrustedKnowledgeProjectionError } from "../ai-engine/knowledge/trustedKnowledgeProjection";

const databaseUrl = process.env.DATABASE_URL_TEST;
async function setup() { process.env.DATABASE_URL = databaseUrl; const { ensureAiBuilderSchema } = await import("./ai-builder-schema"); await ensureAiBuilderSchema(); const pool = new Pool({ connectionString: databaseUrl }); const client = await pool.connect(); const projectId = `trusted-projection-${randomUUID()}`; await client.query("INSERT INTO ai_builder_projects (id,status,business_name,industry,assistant_configuration,context_counts,governance_revision,trusted_knowledge_revision,created_at,updated_at) VALUES ($1,'review_required','Test','test','{}'::jsonb,'{}'::jsonb,0,0,NOW(),NOW())", [projectId]); return { pool, client, projectId }; }
async function context(client: any, projectId: string, status = "approved", id = `context-${randomUUID()}`, source: unknown = { intakeBlockId: "intake", excerpt: "Excerpt", sourceType: "manual_intake" }) { await client.query("INSERT INTO ai_builder_context_entries (id,project_id,category,title,content,confidence,confidence_score,status,source,metadata,created_at,updated_at) VALUES ($1,$2,'service','Title','Content','high',.9,$3,$4::jsonb,'{}'::jsonb,NOW(),NOW())", [id, projectId, status, JSON.stringify(source)]); return id; }
async function faq(client: any, projectId: string, status = "proposed", ids: string[] = [], id = `faq-${randomUUID()}`) { await client.query("INSERT INTO ai_builder_faq_entries (id,project_id,question,answer,confidence,confidence_score,source_entry_ids,status,metadata,created_at,updated_at) VALUES ($1,$2,'Question?','Answer','high',.9,$3::jsonb,$4,'{}'::jsonb,NOW(),NOW())", [id, projectId, JSON.stringify(ids), status]); return id; }
async function reconcile(client: any, id: string, revision: number) { await client.query("BEGIN"); try { await client.query("SELECT id FROM ai_builder_projects WHERE id=$1 FOR UPDATE", [id]); await reconcileTrustedKnowledgeProjectionForProject(client, id, revision); await client.query("COMMIT"); } catch (e) { await client.query("ROLLBACK"); throw e; } }
async function row(client: any, id: string, kind = "context_entry") { return (await client.query("SELECT * FROM ai_builder_trusted_knowledge_projection WHERE project_id=$1 AND source_item_kind=$2", [id, kind])).rows; }
function db(name: string, fn: () => Promise<void>) { test(name, { skip: databaseUrl ? false : "DATABASE_URL_TEST is not configured" }, fn); }

db("revision-zero approved canonical rows are backfilled without changing governance revision", async () => { const s=await setup(); try { await context(s.client,s.projectId); assert.equal((await row(s.client,s.projectId)).length,0); await reconcile(s.client,s.projectId,0); const p=(await s.client.query("SELECT governance_revision,trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1",[s.projectId])).rows[0]; const r=(await row(s.client,s.projectId))[0]; assert.deepEqual([p.governance_revision,p.trusted_knowledge_revision,r.active,r.review_state,r.governance_revision],[0,0,true,"approved",0]); } finally { await s.client.query("DELETE FROM ai_builder_projects WHERE id=$1",[s.projectId]); s.client.release(); await s.pool.end(); } });
db("context projection preserves one logical row through the full review lifecycle", async () => { const s=await setup(); try { const id=await context(s.client,s.projectId,"proposed"); await reconcile(s.client,s.projectId,0); const first=(await row(s.client,s.projectId))[0]; for (const [state,rev] of [["approved",1],["corrected",2],["archived",3],["approved",4],["proposed",5]] as const) { await s.client.query("UPDATE ai_builder_context_entries SET status=$2,title=CASE WHEN $2='corrected' THEN 'Corrected title' ELSE title END,content=CASE WHEN $2='corrected' THEN 'Corrected content' ELSE content END WHERE id=$1",[id,state]); await s.client.query("UPDATE ai_builder_projects SET governance_revision=$2 WHERE id=$1",[s.projectId,rev]); await reconcile(s.client,s.projectId,rev); const r=(await row(s.client,s.projectId))[0]; assert.equal(r.id,first.id); assert.equal((await row(s.client,s.projectId)).length,1); assert.equal(r.active,state === "approved" || state === "corrected"); assert.equal((await s.client.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1",[s.projectId])).rows[0].trusted_knowledge_revision,rev); } await reconcile(s.client,s.projectId,5); assert.equal((await row(s.client,s.projectId)).length,1); } finally { await s.client.query("DELETE FROM ai_builder_projects WHERE id=$1",[s.projectId]); s.client.release(); await s.pool.end(); } });
db("FAQ projection preserves support IDs and one logical row through the full lifecycle", async () => { const s=await setup(); try { const support=await context(s.client,s.projectId); const id=await faq(s.client,s.projectId,"proposed",[support]); await reconcile(s.client,s.projectId,0); const first=(await row(s.client,s.projectId,"faq"))[0]; for (const [state,rev] of [["approved",1],["corrected",2],["archived",3],["approved",4],["proposed",5]] as const) { await s.client.query("UPDATE ai_builder_faq_entries SET status=$2,question=CASE WHEN $2='corrected' THEN 'Corrected question?' ELSE question END,answer=CASE WHEN $2='corrected' THEN 'Corrected answer' ELSE answer END WHERE id=$1",[id,state]); await s.client.query("UPDATE ai_builder_projects SET governance_revision=$2 WHERE id=$1",[s.projectId,rev]); await reconcile(s.client,s.projectId,rev); const r=(await row(s.client,s.projectId,"faq"))[0]; assert.equal(r.id,first.id); assert.deepEqual(r.source_entry_ids,[support]); assert.equal(r.active,state === "approved" || state === "corrected"); } await reconcile(s.client,s.projectId,5); assert.equal((await row(s.client,s.projectId,"faq")).length,1); } finally { await s.client.query("DELETE FROM ai_builder_projects WHERE id=$1",[s.projectId]); s.client.release(); await s.pool.end(); } });
db("reconciliation deactivates projection rows whose canonical source no longer exists", async () => { const s=await setup(); try { const id=await context(s.client,s.projectId); await reconcile(s.client,s.projectId,0); const before=(await row(s.client,s.projectId))[0]; await s.client.query("DELETE FROM ai_builder_context_entries WHERE id=$1",[id]); await s.client.query("UPDATE ai_builder_projects SET governance_revision=1 WHERE id=$1",[s.projectId]); await reconcile(s.client,s.projectId,1); const after=(await row(s.client,s.projectId))[0]; assert.equal(after.id,before.id); assert.deepEqual([after.active,after.governance_revision],[false,1]); } finally { await s.client.query("DELETE FROM ai_builder_projects WHERE id=$1",[s.projectId]); s.client.release(); await s.pool.end(); } });
db("reconciliation never changes another project's projection or trusted revision", async () => { const a=await setup(), b=await setup(); try { await context(a.client,a.projectId); await context(a.client,b.projectId); await reconcile(a.client,a.projectId,0); await reconcile(a.client,b.projectId,0); const before=(await row(a.client,b.projectId))[0]; await a.client.query("UPDATE ai_builder_context_entries SET content='Changed' WHERE project_id=$1",[a.projectId]); await a.client.query("UPDATE ai_builder_projects SET governance_revision=1 WHERE id=$1",[a.projectId]); await reconcile(a.client,a.projectId,1); const after=(await row(a.client,b.projectId))[0]; assert.deepEqual([after.content,after.active,after.governance_revision],[before.content,before.active,before.governance_revision]); assert.equal((await a.client.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1",[b.projectId])).rows[0].trusted_knowledge_revision,0); } finally { for (const s of [a,b]) { await s.client.query("DELETE FROM ai_builder_projects WHERE id=$1",[s.projectId]); s.client.release(); await s.pool.end(); } } });
async function expectRollback(makeBad: (s:any)=>Promise<void>, code: string) { const s=await setup(); try { await context(s.client,s.projectId); await makeBad(s); await assert.rejects(() => reconcile(s.client,s.projectId,0), (e:any) => e instanceof TrustedKnowledgeProjectionError && e.code === code); assert.equal((await row(s.client,s.projectId)).length,0); assert.equal((await s.client.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1",[s.projectId])).rows[0].trusted_knowledge_revision,0); } finally { await s.client.query("DELETE FROM ai_builder_projects WHERE id=$1",[s.projectId]); s.client.release(); await s.pool.end(); } }
db("invalid canonical review state rolls back all projection writes", () => expectRollback(async s => { await context(s.client,s.projectId,"unknown"); }, "invalid_trusted_projection_source_state"));
db("malformed context source rolls back the entire project reconciliation", () => expectRollback(async s => { await context(s.client,s.projectId,"approved",undefined,null); }, "trusted_knowledge_projection_invalid_source"));
db("malformed FAQ content rolls back the entire project reconciliation", () => expectRollback(async s => { await faq(s.client,s.projectId,"approved",["context-1","context-1"]); }, "trusted_knowledge_projection_invalid_source"));
