import "server-only";
import type { PoolClient } from "@neondatabase/serverless";
import { cutoverEligibilityFailure } from "../assistant-projection/cutover";
type QueryClient = Pick<PoolClient, "query">;
/** Computed read model sourced from the latest durable transitions. */
export async function getOperationalStatus(client: QueryClient, projectId: string) {
  const [project,memory,projection,jobs,latestFailure,latestEvent,latestRetry,latestAttempt,latestReconciliation,unresolved,parity]=await Promise.all([
    client.query("SELECT runtime_authority,migration_state,migration_run_id,migration_revision FROM ai_builder_projects WHERE id=$1",[projectId]),
    client.query("SELECT revision,trusted_knowledge_revision,state_fingerprint FROM ai_builder_business_memory WHERE project_id=$1",[projectId]),
    client.query("SELECT business_memory_fingerprint,invalidation_state,projection_version,schema_version,generated_at FROM ai_builder_assistant_projections WHERE project_id=$1",[projectId]),
    client.query("SELECT status,count(*)::int AS count FROM ai_builder_downstream_synchronization_jobs WHERE project_id=$1 GROUP BY status",[projectId]),
    client.query("SELECT event_type,command_id,error_code,error_message,occurred_at FROM ai_builder_operational_events WHERE project_id=$1 AND event_type IN ('review_command_failed','governance_transaction_failed') ORDER BY occurred_at DESC,id DESC LIMIT 1",[projectId]),
    client.query("SELECT occurred_at FROM ai_builder_operational_events WHERE project_id=$1 ORDER BY occurred_at DESC,id DESC LIMIT 1",[projectId]),
    client.query("SELECT event_type,synchronization_job_id,synchronization_attempt_id,command_id,error_code,metadata,occurred_at FROM ai_builder_operational_events WHERE project_id=$1 AND event_type IN ('retry_scheduled','retry_started','retry_succeeded','retry_failed','dead_letter_entered','dead_letter_reopened','stale_running_recovered') ORDER BY occurred_at DESC,id DESC LIMIT 1",[projectId]),
    client.query("SELECT * FROM ai_builder_downstream_synchronization_attempts WHERE project_id=$1 ORDER BY started_at DESC,id DESC LIMIT 1",[projectId]),
    client.query("SELECT event_type,metadata,occurred_at FROM ai_builder_operational_events WHERE project_id=$1 AND event_type IN ('reconciliation_no_op','reconciliation_repaired','reconciliation_blocked','reconciliation_failed') ORDER BY occurred_at DESC,id DESC LIMIT 1",[projectId]),
    client.query("SELECT e.* FROM ai_builder_operational_events e WHERE e.project_id=$1 AND e.event_type='drift_unresolved' AND NOT EXISTS (SELECT 1 FROM ai_builder_operational_events r WHERE r.project_id=e.project_id AND r.event_type='drift_resolved' AND r.metadata->>'signature'=e.metadata->>'signature' AND (r.occurred_at,r.id)>(e.occurred_at,e.id)) ORDER BY e.occurred_at DESC,e.id DESC LIMIT 1",[projectId]),
    client.query("SELECT status,assistant_projection_version,assistant_projection_schema_version,active_runtime_authority,compared_at,artifact_fingerprint FROM ai_builder_assistant_projection_parity_reports WHERE project_id=$1",[projectId]),
  ]);
  const p:any=project.rows[0]??null,a:any=projection.rows[0]??null,e:any=parity.rows[0]??null;
  const eligibility=a&&p?cutoverEligibilityFailure({runtimeAuthority:"canonical",artifact:{projectionVersion:Number(a.projection_version),schemaVersion:Number(a.schema_version),generatedAt:new Date(a.generated_at).toISOString(),businessMemoryFingerprint:a.business_memory_fingerprint,invalidationState:a.invalidation_state},evidence:e?{status:e.status,projectionVersion:e.assistant_projection_version,schemaVersion:e.assistant_projection_schema_version,activeRuntimeAuthority:e.active_runtime_authority,comparedAt:e.compared_at,artifactFingerprint:e.artifact_fingerprint}:null}):"assistant_projection_runtime_unavailable_missing";
  return {projectId,latestReviewOrGovernanceFailure:latestFailure.rows[0]??null,synchronizationJobCounts:Object.fromEntries(jobs.rows.map((row:any)=>[row.status,Number(row.count)])),latestRetryOrDeadLetter:latestRetry.rows[0]??null,latestAttempt:latestAttempt.rows[0]??null,latestReconciliationResult:latestReconciliation.rows[0]??null,migration:p&&{state:p.migration_state,runId:p.migration_run_id,revision:p.migration_revision},businessMemory:memory.rows[0]??null,projection:a&&{fingerprint:a.business_memory_fingerprint,valid:a.invalidation_state==="valid",version:a.projection_version,schemaVersion:a.schema_version},unresolvedDrift:unresolved.rows[0]??null,parityState:e,runtimeAuthority:p?.runtime_authority??null,cutoverEligible:eligibility===null,cutoverEligibilityFailure:eligibility,latestOperationalEventAt:latestEvent.rows[0]?.occurred_at??null};
}
