import "server-only";

import { randomUUID } from "node:crypto";
import type { PoolClient } from "@neondatabase/serverless";
import type { TypedRepairOperation, RepairResult, RepairStore, RepairTransaction } from "../reconciliation/repair-executor";

type Payload = Record<string, unknown>;
const object = (value: unknown): Payload => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("business_memory_invalid_repair_payload"); return value as Payload; };
const text = (value: unknown, field: string, nullable = false): string | null => { if (value == null && nullable) return null; if (typeof value !== "string" || !value.trim()) throw new Error(`business_memory_invalid_repair_payload:${field}`); return value; };
const bool = (value: unknown, field: string): boolean => { if (typeof value !== "boolean") throw new Error(`business_memory_invalid_repair_payload:${field}`); return value; };
const strings = (value: unknown, field: string): string[] => { if (!Array.isArray(value) || value.some(item => typeof item !== "string")) throw new Error(`business_memory_invalid_repair_payload:${field}`); return value; };
const timestamp = (value: unknown, field: string) => text(value, field)!;

/** The transaction-backed repair store. It receives the command transaction so
 * reconciliation remains one writer and one revision increment. */
export class NeonBusinessMemoryReconciliationStore implements RepairStore {
  constructor(private readonly client: PoolClient, private readonly projectId: string) {}
  async transaction<T>(callback: (transaction: RepairTransaction) => Promise<T>): Promise<T> { return callback(new NeonRepairTransaction(this.client, this.projectId)); }
}

class NeonRepairTransaction implements RepairTransaction {
  private memoryId = "";
  private fingerprint = "";
  private trustedRevision: number | null = null;
  constructor(private readonly client: PoolClient, private readonly projectId: string) {}
  async loadForUpdate() { const row=(await this.client.query("SELECT id, revision FROM ai_builder_business_memory WHERE project_id=$1 FOR UPDATE",[this.projectId])).rows[0]; if(!row) throw new Error("business_memory_not_found"); this.memoryId=String(row.id); return { revision:Number(row.revision) }; }

  async apply(operation: TypedRepairOperation): Promise<Record<string,string[]>> {
    if(operation.type === "synchronizeFingerprint") { this.fingerprint=text(operation.payload,"fingerprint")!; return {}; }
    if(operation.type === "synchronizeTrustedKnowledgeRevision") { if(typeof operation.payload !== "number" || !Number.isFinite(operation.payload)) throw new Error("business_memory_invalid_repair_payload:trustedKnowledgeRevision"); this.trustedRevision=operation.payload; return {}; }
    const value=object(operation.payload), id=text(value.id ?? operation.id,"id")!;
    if (operation.type === "deactivateResolvedEntity" && operation.model === "resolvedEntities") return this.deactivate("ai_builder_business_memory_resolved_entities", id, "active", operation.model);
    if (operation.type === "deactivateIdentityKey" && operation.model === "identityKeys") return this.deactivate("ai_builder_business_memory_identity_keys", id, "active", operation.model);
    if (operation.type === "deactivateConflict" && operation.model === "conflicts") return this.deactivate("ai_builder_business_memory_conflicts", id, "active", operation.model);
    if (operation.type === "collapseDuplicateRelationship") return this.delete("ai_builder_business_memory_relationships", id, operation.model);

    switch (operation.model) {
      case "resolvedEntities": return this.resolvedEntity(value, id);
      case "identityKeys": return this.identityKey(value, id);
      case "aliases": return this.alias(value, id, operation.type === "preserveAcceptedAlias");
      case "redirects": return this.redirect(value);
      case "sourceEntityOwnership": return this.sourceOwnership(value, id);
      case "assertionOwnership": return this.assertionOwnership(value, id);
      case "relationships": return this.relationship(value, id);
      case "conflicts": return this.conflict(value, id);
      case "conflictAssertionLinks": return this.conflictAssertionLink(value, id);
      case "sources": return this.source(value, id);
      case "evidence": return this.evidence(value, id);
      case "assertionSourceLinks": return this.assertionSourceLink(value, id);
      case "assertionEvidenceLinks": return this.assertionEvidenceLink(value, id);
      default: throw new Error(`business_memory_unknown_repair_model:${operation.model}`);
    }
  }

  private async resolvedEntity(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_resolved_entities (id,memory_id,project_id,entity_type,active,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,now(),now()) ON CONFLICT (id) DO UPDATE SET entity_type=EXCLUDED.entity_type,active=EXCLUDED.active,updated_at=now() WHERE ai_builder_business_memory_resolved_entities.memory_id=$2",[id,this.memoryId,text(v.projectId,"projectId")!,text(v.type,"type")!,bool(v.active,"active")]); return {resolvedEntities:[id]}; }
  private async identityKey(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_identity_keys (id,memory_id,project_id,resolved_entity_id,source_entity_id,key_type,normalized_value,display_value,strength,authoritative,source_ids,active,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,now(),now()) ON CONFLICT (id) DO UPDATE SET resolved_entity_id=EXCLUDED.resolved_entity_id,source_entity_id=EXCLUDED.source_entity_id,key_type=EXCLUDED.key_type,normalized_value=EXCLUDED.normalized_value,display_value=EXCLUDED.display_value,strength=EXCLUDED.strength,authoritative=EXCLUDED.authoritative,source_ids=EXCLUDED.source_ids,active=EXCLUDED.active,updated_at=now() WHERE ai_builder_business_memory_identity_keys.memory_id=$2",[id,this.memoryId,text(v.projectId,"projectId")!,text(v.resolvedEntityId,"resolvedEntityId")!,text(v.sourceEntityId,"sourceEntityId",true),text(v.type,"type")!,text(v.normalizedValue,"normalizedValue")!,text(v.displayValue,"displayValue",true),text(v.strength,"strength")!,bool(v.authoritative,"authoritative"),JSON.stringify(strings(v.sourceIds,"sourceIds")),v.active === undefined ? true : bool(v.active,"active")]); return {identityKeys:[id]}; }
  private async alias(v: Payload, id: string, preserve: boolean) { const accepted=bool(v.accepted,"accepted"); if(preserve && !accepted) throw new Error("business_memory_invalid_repair_payload:accepted"); await this.client.query("INSERT INTO ai_builder_business_memory_entity_aliases (id,memory_id,project_id,resolved_entity_id,display_value,normalized_value,source_ids,accepted,active,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,now(),now()) ON CONFLICT (id) DO UPDATE SET resolved_entity_id=EXCLUDED.resolved_entity_id,display_value=EXCLUDED.display_value,normalized_value=EXCLUDED.normalized_value,source_ids=EXCLUDED.source_ids,accepted=EXCLUDED.accepted,active=EXCLUDED.active,updated_at=now() WHERE ai_builder_business_memory_entity_aliases.memory_id=$2",[id,this.memoryId,text(v.projectId,"projectId")!,text(v.resolvedEntityId,"resolvedEntityId")!,text(v.displayValue,"displayValue")!,text(v.normalizedValue,"normalizedValue")!,JSON.stringify(strings(v.sourceIds,"sourceIds")),accepted,v.active === undefined ? true : bool(v.active,"active")]); return {aliases:[id]}; }
  private async redirect(v: Payload) { const from=text(v.fromResolvedEntityId,"fromResolvedEntityId")!, to=text(v.toResolvedEntityId,"toResolvedEntityId")!; await this.client.query("INSERT INTO ai_builder_business_memory_entity_redirects (from_resolved_entity_id,to_resolved_entity_id,memory_id,created_at) VALUES ($1,$2,$3,now()) ON CONFLICT (from_resolved_entity_id) DO UPDATE SET to_resolved_entity_id=EXCLUDED.to_resolved_entity_id WHERE ai_builder_business_memory_entity_redirects.memory_id=$3",[from,to,this.memoryId]); return {redirects:[from]}; }
  private async sourceOwnership(v: Payload, id: string) { const source=text(v.sourceEntityId,"sourceEntityId")!; await this.client.query("INSERT INTO ai_builder_business_memory_entity_resolution (source_entity_id,resolved_entity_id,memory_id,created_at) VALUES ($1,$2,$3,now()) ON CONFLICT (source_entity_id) DO UPDATE SET resolved_entity_id=EXCLUDED.resolved_entity_id WHERE ai_builder_business_memory_entity_resolution.memory_id=$3",[source,text(v.resolvedEntityId,"resolvedEntityId")!,this.memoryId]); return {sourceEntityOwnership:[id]}; }
  private async assertionOwnership(v: Payload, id: string) { const result=await this.client.query("UPDATE ai_builder_business_memory_assertions SET entity_id=$1,updated_at=now() WHERE id=$2 AND memory_id=$3",[text(v.resolvedEntityId,"resolvedEntityId")!,text(v.assertionId,"assertionId")!,this.memoryId]); if(result.rowCount === 0) throw new Error("business_memory_assertion_not_found"); return {assertionOwnership:[id]}; }
  private async relationship(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_relationships (id,memory_id,relationship_type,from_entity_id,to_entity_id,from_assertion_id,to_assertion_id,source_entry_ids,provenance,review_state,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10,$11::timestamptz,$12::timestamptz) ON CONFLICT (id) DO UPDATE SET relationship_type=EXCLUDED.relationship_type,from_entity_id=EXCLUDED.from_entity_id,to_entity_id=EXCLUDED.to_entity_id,from_assertion_id=EXCLUDED.from_assertion_id,to_assertion_id=EXCLUDED.to_assertion_id,source_entry_ids=EXCLUDED.source_entry_ids,provenance=EXCLUDED.provenance,review_state=EXCLUDED.review_state,updated_at=EXCLUDED.updated_at WHERE ai_builder_business_memory_relationships.memory_id=$2",[id,this.memoryId,text(v.relationshipType,"relationshipType")!,text(v.fromResolvedEntityId,"fromResolvedEntityId")!,text(v.toResolvedEntityId,"toResolvedEntityId")!,text(v.fromAssertionId,"fromAssertionId")!,text(v.toAssertionId,"toAssertionId")!,JSON.stringify(strings(v.sourceEntryIds,"sourceEntryIds")),JSON.stringify(strings(v.provenance,"provenance")),text(v.reviewState,"reviewState")!,timestamp(v.createdAt,"createdAt"),timestamp(v.updatedAt,"updatedAt")]); return {relationships:[id]}; }
  private async conflict(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_conflicts (id,memory_id,resolved_entity_id,topic,conflicting_statements,detection_rule,suggested_question,resolved,resolution,active,material_input_hash,created_at,updated_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11,now(),now()) ON CONFLICT (id) DO UPDATE SET resolved_entity_id=EXCLUDED.resolved_entity_id,topic=EXCLUDED.topic,conflicting_statements=EXCLUDED.conflicting_statements,detection_rule=EXCLUDED.detection_rule,suggested_question=EXCLUDED.suggested_question,resolved=EXCLUDED.resolved,resolution=EXCLUDED.resolution,active=EXCLUDED.active,material_input_hash=EXCLUDED.material_input_hash,updated_at=now() WHERE ai_builder_business_memory_conflicts.memory_id=$2",[id,this.memoryId,text(v.resolvedEntityId,"resolvedEntityId")!,text(v.topicKey,"topicKey")!,JSON.stringify(strings(v.normalizedValues,"normalizedValues")),text(v.detectionRule,"detectionRule")!,text(v.suggestedQuestion,"suggestedQuestion")!,bool(v.resolved,"resolved"),text(v.resolution,"resolution",true),bool(v.active,"active"),text(v.materialInputHash,"materialInputHash")!]); return {conflicts:[id]}; }
  private async conflictAssertionLink(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_conflict_assertions (conflict_id,assertion_id) SELECT $1,$2 WHERE EXISTS (SELECT 1 FROM ai_builder_business_memory_conflicts WHERE id=$1 AND memory_id=$3) AND EXISTS (SELECT 1 FROM ai_builder_business_memory_assertions WHERE id=$2 AND memory_id=$3) ON CONFLICT DO NOTHING",[text(v.conflictId,"conflictId")!,text(v.assertionId,"assertionId")!,this.memoryId]); return {conflictAssertionLinks:[id]}; }
  private async source(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_sources (id,memory_id,canonical_source_id,origin,source_entry_id,intake_block_id,url,label,captured_at,crawl_attempt_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::timestamptz,$10) ON CONFLICT (id) DO UPDATE SET canonical_source_id=EXCLUDED.canonical_source_id,origin=EXCLUDED.origin,source_entry_id=EXCLUDED.source_entry_id,intake_block_id=EXCLUDED.intake_block_id,url=EXCLUDED.url,label=EXCLUDED.label,captured_at=EXCLUDED.captured_at,crawl_attempt_id=EXCLUDED.crawl_attempt_id WHERE ai_builder_business_memory_sources.memory_id=$2",[id,this.memoryId,text(v.canonicalSourceId,"canonicalSourceId")!,text(v.origin,"origin")!,text(v.sourceEntryId,"sourceEntryId",true),text(v.intakeBlockId,"intakeBlockId",true),text(v.url,"url",true),text(v.label,"label",true),timestamp(v.capturedAt,"capturedAt"),text(v.crawlAttemptId,"crawlAttemptId",true)]); return {sources:[id]}; }
  private async evidence(v: Payload, id: string) { await this.client.query("INSERT INTO ai_builder_business_memory_evidence (id,memory_id,source_id,canonical_evidence_id,excerpt,url,captured_at) VALUES ($1,$2,$3,$4,$5,$6,$7::timestamptz) ON CONFLICT (id) DO UPDATE SET source_id=EXCLUDED.source_id,canonical_evidence_id=EXCLUDED.canonical_evidence_id,excerpt=EXCLUDED.excerpt,url=EXCLUDED.url,captured_at=EXCLUDED.captured_at WHERE ai_builder_business_memory_evidence.memory_id=$2",[id,this.memoryId,text(v.sourceId,"sourceId")!,text(v.canonicalEvidenceId,"canonicalEvidenceId")!,text(v.excerpt,"excerpt")!,text(v.url,"url",true),timestamp(v.capturedAt,"capturedAt")]); return {evidence:[id]}; }
  private async assertionSourceLink(v: Payload, id: string) { await this.link("ai_builder_business_memory_assertion_sources","source_id",text(v.assertionId,"assertionId")!,text(v.sourceId,"sourceId")!); return {assertionSourceLinks:[id]}; }
  private async assertionEvidenceLink(v: Payload, id: string) { await this.link("ai_builder_business_memory_assertion_evidence","evidence_id",text(v.assertionId,"assertionId")!,text(v.evidenceId,"evidenceId")!); return {assertionEvidenceLinks:[id]}; }
  private async link(table: string, column: string, assertionId: string, relatedId: string) { await this.client.query(`INSERT INTO ${table} (assertion_id,${column}) SELECT $1,$2 WHERE EXISTS (SELECT 1 FROM ai_builder_business_memory_assertions WHERE id=$1 AND memory_id=$3) ON CONFLICT DO NOTHING`,[assertionId,relatedId,this.memoryId]); }
  private async deactivate(table: string, id: string, field: string, model: string) { await this.client.query(`UPDATE ${table} SET ${field}=FALSE,updated_at=now() WHERE id=$1 AND memory_id=$2`,[id,this.memoryId]); return {[model]:[id]}; }
  private async delete(table: string, id: string, model: string) { await this.client.query(`DELETE FROM ${table} WHERE id=$1 AND memory_id=$2`,[id,this.memoryId]); return {[model]:[id]}; }
  async synchronize() { await this.client.query("UPDATE ai_builder_business_memory SET revision=revision+1,state_fingerprint=COALESCE(NULLIF($2,''),state_fingerprint),trusted_knowledge_revision=COALESCE($3,trusted_knowledge_revision),updated_at=now() WHERE id=$1",[this.memoryId,this.fingerprint,this.trustedRevision]); await this.client.query("UPDATE ai_builder_projects SET business_memory_revision=(SELECT revision FROM ai_builder_business_memory WHERE id=$1) WHERE id=$2",[this.memoryId,this.projectId]); }
  async verify() { return true; }
  async appendHistory(result: RepairResult) { await this.client.query("INSERT INTO ai_builder_business_memory_reconciliation_history (id,memory_id,starting_revision,resulting_revision,mutation_fingerprint,changed_ids,created_at) VALUES ($1,$2,$3,$4,$5,$6::jsonb,now())",[randomUUID(),this.memoryId,result.startingRevision,result.resultingRevision,result.mutationFingerprint,JSON.stringify(result.changedIds)]); }
}
