import { canonicalJson, normalized, stableHash } from "./entity-reconciliation";
export type ConflictAssertion = { id: string; resolvedEntityId: string; claimType: string; category?: string | null; title?: string | null; value: string; reviewState: string; authority: string; active?: boolean };
export type AssertionConflict = { id: string; resolvedEntityId: string; topicKey: string; assertionIds: string[]; normalizedValues: string[]; detectionRule: string; suggestedQuestion: string; resolved: boolean; active: boolean; materialInputHash: string };
/** Only structured claim types with explicit category/title are supported; free-form claims are deliberately ignored. */
export function assertionTopicKey(assertion: ConflictAssertion): string | null { if (!assertion.category || !assertion.title || !["faq", "fact", "policy", "offer", "pricing", "contact"].includes(assertion.claimType)) return null; return canonicalJson({ claimType: assertion.claimType, category: normalized(assertion.category), title: normalized(assertion.title) }); }
const matters = (a: ConflictAssertion) => a.active !== false && !["archived", "rejected"].includes(a.reviewState) && ["confirmed", "corrected", "observed"].includes(a.authority);
export function detectAssertionConflicts(projectOrMemoryId: string, assertions: ConflictAssertion[], existing: AssertionConflict[] = []): AssertionConflict[] {
 const groups = new Map<string, ConflictAssertion[]>(); for (const a of assertions.filter(matters)) { const topic = assertionTopicKey(a); if (topic) groups.set(`${a.resolvedEntityId}:${topic}`, [...(groups.get(`${a.resolvedEntityId}:${topic}`) ?? []), a]); }
 const result: AssertionConflict[] = [];
 for (const [groupKey, group] of Array.from(groups.entries())) { const values = Array.from(new Set(group.map(a => normalized(a.value)))).sort(); if (values.length < 2) continue; const [resolvedEntityId, topicKey] = [group[0].resolvedEntityId, assertionTopicKey(group[0])!]; const assertionIds = group.map(a => a.id).sort(); const materialInputHash = stableHash({ assertionIds, values }); const id = `business_conflict:${stableHash({ projectOrMemoryId, resolvedEntityId, topicKey, assertionIds })}`; const prior = existing.find(x => x.id === id); result.push({ id, resolvedEntityId, topicKey, assertionIds, normalizedValues: values, detectionRule: "exact_structured_topic_incompatible_normalized_values", suggestedQuestion: `Which value is correct for ${group[0].title}?`, resolved: prior?.resolved === true && prior.materialInputHash === materialInputHash, active: true, materialInputHash }); }
 return result.sort((a,b) => a.id.localeCompare(b.id));
}
