import { createHash } from "node:crypto";
import type { BusinessRelationship } from "./relationship-rewiring";
import type { AssertionConflict } from "./conflicting-assertions";

/**
 * Model A: source entities remain immutable projection rows.  This module owns a
 * separate resolved-entity layer; redirects only ever point between resolved IDs.
 * It deliberately accepts exact, canonical identifiers only (never text similarity).
 */
export type IdentityKeyType = "source_item" | "canonical_name" | "alias" | "domain" | "website" | "email" | "phone" | "external_id";
export type IdentityStrength = "strong" | "weak";
export type SourceEntity = { id: string; projectId: string; type: string; name: string; logicalKey: string; assertionIds: string[] };
export type ResolvedEntity = { id: string; projectId: string; type: string; active: boolean; sourceEntityIds: string[] };
export type IdentityKey = { id: string; projectId: string; resolvedEntityId: string; sourceEntityId: string | null; type: IdentityKeyType; normalizedValue: string; displayValue: string | null; strength: IdentityStrength; authoritative: boolean; sourceIds: string[]; active?: boolean };
export type EntityAlias = { id: string; projectId: string; resolvedEntityId: string; displayValue: string; normalizedValue: string; sourceIds: string[]; accepted: boolean };
export type Redirect = { fromResolvedEntityId: string; toResolvedEntityId: string };
export type CandidateEvidence = { type: IdentityKeyType; value: string; rule: string };
export type DuplicateCandidate = { id: string; entityIds: string[]; evidence: CandidateEvidence[]; classification: "auto_merge" | "manual_review"; autoMergeEligible: boolean; manualReviewRequired: boolean; incompatibleTypeReason: string | null };
export const canonicalJson = (v: unknown): string => Array.isArray(v) ? `[${v.map(canonicalJson).join(",")}]` : v && typeof v === "object" ? `{${Object.keys(v as object).sort().map(k => `${JSON.stringify(k)}:${canonicalJson((v as Record<string, unknown>)[k])}`).join(",")}}` : JSON.stringify(v);
export const stableHash = (v: unknown) => createHash("sha256").update(canonicalJson(v)).digest("hex");
const canon = canonicalJson;
const hash = stableHash;
export const normalized = (value: string) => value.trim().normalize("NFKC").toLocaleLowerCase("en-US").replace(/\s+/g, " ");
export const stableResolvedEntityId = (projectId: string, sourceLogicalKey: string) => `business_resolved_entity:${hash({ projectId, sourceLogicalKey })}`;
export const stableIdentityKeyId = (projectId: string, type: IdentityKeyType, value: string, sourceEntityId: string | null) => `business_identity_key:${hash({ projectId, type, value, sourceEntityId })}`;
export function normalizeIdentityKey(type: IdentityKeyType, value: string): string | null {
  const v = normalized(value); if (!v) return null;
  if (type === "email") return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v) ? v : null;
  if (type === "phone") { const p = v.replace(/[^0-9+]/g, ""); return /^\+?[0-9]{7,15}$/.test(p) ? p : null; }
  if (type === "domain") return /^(?:[a-z0-9-]+\.)+[a-z]{2,63}$/.test(v) ? v : null;
  if (type === "website") try { const u = new URL(v.includes("://") ? v : `https://${v}`); return u.hostname.toLowerCase().replace(/^www\./, "") + (u.pathname === "/" ? "" : u.pathname.replace(/\/$/, "")); } catch { return null; }
  return v;
}
export function sourceItemKey(entity: SourceEntity): IdentityKey { const value = normalized(entity.logicalKey); return { id: stableIdentityKeyId(entity.projectId, "source_item", value, entity.id), projectId: entity.projectId, resolvedEntityId: stableResolvedEntityId(entity.projectId, entity.logicalKey), sourceEntityId: entity.id, type: "source_item", normalizedValue: value, displayValue: entity.logicalKey, strength: "strong", authoritative: true, sourceIds: [] }; }
export function makeAlias(projectId: string, resolvedEntityId: string, displayValue: string, sourceIds: string[] = [], accepted = true): EntityAlias | null { const value = normalized(displayValue); return value ? { id: `business_alias:${hash({ projectId, resolvedEntityId, value })}`, projectId, resolvedEntityId, displayValue: displayValue.trim(), normalizedValue: value, sourceIds: Array.from(new Set(sourceIds)).sort(), accepted } : null; }
export function resolveRedirect(id: string, redirects: Redirect[]): string { const map = new Map(redirects.map(x => [x.fromResolvedEntityId, x.toResolvedEntityId])); const seen = new Set<string>(); let current = id; while (map.has(current)) { if (seen.has(current)) throw new Error("business_memory_redirect_cycle"); seen.add(current); current = map.get(current)!; } return current; }
export function detectDuplicates(sourceEntities: SourceEntity[], resolved: ResolvedEntity[], keys: IdentityKey[], aliases: EntityAlias[], redirects: Redirect[]): DuplicateCandidate[] {
  const active = new Map(resolved.filter(x => x.active).map(x => [x.id, x])); const candidates = new Map<string, { ids: Set<string>; evidence: CandidateEvidence[] }>();
  const add = (ids: string[], evidence: CandidateEvidence) => { const final = Array.from(new Set(ids.map(x => resolveRedirect(x, redirects)))).filter(x => active.has(x)).sort(); if (final.length < 2) return; const key = final.join("|"); const c = candidates.get(key) ?? { ids: new Set(final), evidence: [] }; if (!c.evidence.some(x => canon(x) === canon(evidence))) c.evidence.push(evidence); candidates.set(key, c); };
  const byKey = new Map<string, IdentityKey[]>(); for (const k of keys.filter(k => k.projectId && k.type !== "source_item")) { const group = byKey.get(`${k.type}:${k.normalizedValue}`) ?? []; group.push(k); byKey.set(`${k.type}:${k.normalizedValue}`, group); }
  for (const group of Array.from(byKey.values())) if (group.length > 1) add(group.map(k => k.resolvedEntityId), { type: group[0].type, value: group[0].normalizedValue, rule: group.some(k => k.strength === "strong" && k.authoritative) ? "authoritative_exact_key" : "exact_weak_key" });
  const names = new Map<string, string[]>(); for (const s of sourceEntities) { const r = resolveRedirect(stableResolvedEntityId(s.projectId, s.logicalKey), redirects); names.set(normalized(s.name), [...(names.get(normalized(s.name)) ?? []), r]); }
  for (const [value, ids] of Array.from(names.entries())) if (ids.length > 1) add(ids, { type: "canonical_name", value, rule: "exact_canonical_name" });
  for (const alias of aliases) { const targets = names.get(alias.normalizedValue) ?? []; if (targets.length) add([alias.resolvedEntityId, ...targets], { type: "alias", value: alias.normalizedValue, rule: "alias_to_name" }); }
  const aliasGroups = new Map<string, EntityAlias[]>(); for (const a of aliases) aliasGroups.set(a.normalizedValue, [...(aliasGroups.get(a.normalizedValue) ?? []), a]); for (const [value, group] of Array.from(aliasGroups.entries())) if (group.length > 1) add(group.map(a => a.resolvedEntityId), { type: "alias", value, rule: "alias_to_alias" });
  return Array.from(candidates.values()).map((c): DuplicateCandidate => { const ids = Array.from(c.ids).sort(); const types = new Set(ids.map(id => active.get(id)!.type)); const auto = types.size === 1 && c.evidence.some(e => e.rule === "authoritative_exact_key" && ["external_id", "email", "phone", "domain", "website"].includes(e.type)); const incompatible = types.size > 1 ? "incompatible_entity_types" : null; const classification = auto ? "auto_merge" : "manual_review"; return { id: `duplicate:${hash({ ids, evidence: c.evidence.sort((a,b) => canon(a).localeCompare(canon(b))) })}`, entityIds: ids, evidence: c.evidence.sort((a,b) => canon(a).localeCompare(canon(b))), classification, autoMergeEligible: auto, manualReviewRequired: !auto, incompatibleTypeReason: incompatible }; }).sort((a,b) => a.id.localeCompare(b.id));
}
export type MergeCommand = { commandId: string; projectId: string; survivorResolvedEntityId: string; mergedResolvedEntityIds: string[]; expectedBusinessMemoryRevision: number; actor: string | null; reason: string | null; evidence: CandidateEvidence[]; requestedAt: string; autoMerge?: boolean };
export function validateMerge(command: MergeCommand, revision: number, entities: ResolvedEntity[], redirects: Redirect[], ledger?: MergeCommand): void { if (ledger && canon(ledger) !== canon(command)) throw new Error("business_memory_merge_command_content_conflict"); if (ledger) return; if (revision !== command.expectedBusinessMemoryRevision) throw new Error("business_memory_stale_revision"); if (!command.mergedResolvedEntityIds.length || new Set(command.mergedResolvedEntityIds).size !== command.mergedResolvedEntityIds.length || command.mergedResolvedEntityIds.includes(command.survivorResolvedEntityId)) throw new Error("business_memory_invalid_merge_members"); const byId = new Map(entities.map(e => [e.id,e])); const survivor = byId.get(resolveRedirect(command.survivorResolvedEntityId, redirects)); if (!survivor || !survivor.active || survivor.projectId !== command.projectId) throw new Error("business_memory_invalid_merge_survivor"); for (const id of command.mergedResolvedEntityIds) { const e = byId.get(resolveRedirect(id, redirects)); if (!e || !e.active || e.projectId !== command.projectId) throw new Error("business_memory_invalid_merge_entity"); if (e.type !== survivor.type) throw new Error("business_memory_incompatible_entity_types"); } if (command.autoMerge && !command.evidence.some(e => e.rule === "authoritative_exact_key")) throw new Error("business_memory_unqualified_auto_merge"); if (!command.autoMerge && (!command.actor?.trim() || !command.reason?.trim())) throw new Error("business_memory_manual_merge_requires_actor_and_reason"); }

export type SourceEntityOwnership = { id: string; sourceEntityId: string; resolvedEntityId: string };
export type AssertionOwnership = { id: string; assertionId: string; resolvedEntityId: string };
export type BusinessMemorySource = { id: string; canonicalSourceId: string; origin: string; sourceEntryId: string | null; intakeBlockId: string | null; url: string | null; label: string | null; capturedAt: string; crawlAttemptId: string | null };
export type BusinessMemoryEvidence = { id: string; sourceId: string; canonicalEvidenceId: string; excerpt: string; url: string | null; capturedAt: string };
export type AssertionSourceLink = { id: string; assertionId: string; sourceId: string };
export type AssertionEvidenceLink = { id: string; assertionId: string; evidenceId: string };
export type ConflictAssertionLink = { id: string; conflictId: string; assertionId: string };
export type ReconciliationState = { sourceEntities: SourceEntity[]; resolvedEntities: ResolvedEntity[]; identityKeys: IdentityKey[]; aliases: EntityAlias[]; redirects: Redirect[]; sourceEntityOwnership: SourceEntityOwnership[]; assertionOwnership: AssertionOwnership[]; relationships: BusinessRelationship[]; conflicts: AssertionConflict[]; conflictAssertionLinks: ConflictAssertionLink[]; sources: BusinessMemorySource[]; evidence: BusinessMemoryEvidence[]; assertionSourceLinks: AssertionSourceLink[]; assertionEvidenceLinks: AssertionEvidenceLink[]; trustedKnowledgeRevision: number; fingerprint: string; revision: number };
export type DriftCategory = "missing_row" | "unexpected_row" | "stale_field" | "wrong_entity_ownership" | "broken_redirect" | "redirect_cycle" | "stale_identity_key" | "conflicting_identity_key_ownership" | "missing_alias" | "stale_alias" | "stale_assertion_owner" | "missing_relationship" | "stale_relationship_endpoint" | "duplicate_relationship" | "missing_conflict" | "stale_conflict" | "source_evidence_lineage_mismatch" | "trusted_knowledge_revision_mismatch" | "revision_fingerprint_mismatch";
export type DriftItem = { id: string; category: DriftCategory; model: string; affectedIds: string[]; expected: unknown; actual: unknown; severity: "error" | "warning"; repairable: boolean; repairAction: string };
const rows = (state: ReconciliationState) => ({ resolvedEntities: state.resolvedEntities, identityKeys: state.identityKeys, aliases: state.aliases, redirects: state.redirects, sourceEntityOwnership: state.sourceEntityOwnership ?? [], assertionOwnership: state.assertionOwnership ?? [], relationships: state.relationships ?? [], conflicts: state.conflicts ?? [], conflictAssertionLinks: state.conflictAssertionLinks ?? [], sources: state.sources ?? [], evidence: state.evidence ?? [], assertionSourceLinks: state.assertionSourceLinks ?? [], assertionEvidenceLinks: state.assertionEvidenceLinks ?? [] });
/** Pure structural drift detector; independently durable accepted aliases are not unexpected. */
export function detectDrift(desired: ReconciliationState, persisted: ReconciliationState): DriftItem[] {
 const output: DriftItem[]=[]; const emit=(category: DriftCategory, model:string, ids:string[], expected:unknown, actual:unknown, repairable=true, action="synchronize") => output.push({id:`drift:${hash({category,model,ids:[...ids].sort(),expected,actual})}`,category,model,affectedIds:[...ids].sort(),expected,actual,severity:repairable?"warning":"error",repairable,repairAction:action});
 const category = (model:string, stale=false): DriftCategory => model === "aliases" ? stale ? "stale_alias" : "missing_alias" : model === "identityKeys" && stale ? "stale_identity_key" : model === "sourceEntityOwnership" ? "wrong_entity_ownership" : model === "assertionOwnership" ? "stale_assertion_owner" : model === "relationships" ? stale ? "stale_relationship_endpoint" : "missing_relationship" : model === "conflicts" ? stale ? "stale_conflict" : "missing_conflict" : ["sources","evidence","assertionSourceLinks","assertionEvidenceLinks","conflictAssertionLinks"].includes(model) ? "source_evidence_lineage_mismatch" : stale ? "stale_field" : "missing_row";
 for (const model of Object.keys(rows(desired)) as Array<keyof ReturnType<typeof rows>>) { const d=(rows(desired)[model] as Array<{id?:string;fromResolvedEntityId?:string}>); const p=(rows(persisted)[model] as Array<{id?:string;fromResolvedEntityId?:string}>); const key=(x: typeof d[number]) => x.id ?? x.fromResolvedEntityId!; const dm=new Map(d.map(x=>[key(x),x])), pm=new Map(p.map(x=>[key(x),x])); for(const [id,x] of Array.from(dm)) { if(!pm.has(id)) emit(category(model),model,[id],x,null,true,"insert"); else if(canon(x)!==canon(pm.get(id))) emit(category(model,true),model,[id],x,pm.get(id),true,"update"); } for(const [id,x] of Array.from(pm)) if(!dm.has(id) && !(model==="aliases" && (x as EntityAlias).accepted)) emit("unexpected_row",model,[id],null,x,true,"deactivate"); }
 for (const redirect of persisted.redirects) { const target = persisted.resolvedEntities.find(x => x.id === redirect.toResolvedEntityId); if (!target || !target.active) emit("broken_redirect", "redirects", [redirect.fromResolvedEntityId], "active resolved entity", redirect.toResolvedEntityId, true, "update"); }
 for(const redirect of persisted.redirects) try { resolveRedirect(redirect.fromResolvedEntityId,persisted.redirects); } catch { emit("redirect_cycle","redirects",[redirect.fromResolvedEntityId],"acyclic",redirect,false,"block"); }
 const strong=new Map<string,string[]>(); for(const key of persisted.identityKeys.filter(k=>k.strength==="strong"&&k.authoritative)) { const k=`${key.type}:${key.normalizedValue}`; strong.set(k,[...(strong.get(k)??[]),key.resolvedEntityId]); } for(const [key,owners] of Array.from(strong)) if(new Set(owners).size>1) emit("conflicting_identity_key_ownership","identityKeys",owners,key,owners,false,"block");
 const relationshipGroups = new Map<string, BusinessRelationship[]>(); for (const relationship of persisted.relationships ?? []) { const key=canon({ relationshipType:relationship.relationshipType, from:relationship.fromResolvedEntityId, to:relationship.toResolvedEntityId, fromAssertionId:relationship.fromAssertionId, toAssertionId:relationship.toAssertionId }); relationshipGroups.set(key,[...(relationshipGroups.get(key)??[]),relationship]); } for (const group of Array.from(relationshipGroups.values())) if(group.length>1) emit("duplicate_relationship","relationships",group.map((x: BusinessRelationship)=>x.id),"one relationship",group,true,"deactivate");
 if(desired.trustedKnowledgeRevision!==persisted.trustedKnowledgeRevision) emit("trusted_knowledge_revision_mismatch","business_memory",[],desired.trustedKnowledgeRevision,persisted.trustedKnowledgeRevision,true,"synchronize_trusted_knowledge_revision");
 if(desired.fingerprint!==persisted.fingerprint) emit("revision_fingerprint_mismatch","business_memory",[],desired.fingerprint,persisted.fingerprint,true,"synchronize_fingerprint"); return output.sort((a,b)=>a.id.localeCompare(b.id));
}
export type RepairOperation = { type: "insert" | "update" | "deactivate" | "synchronize_fingerprint"; model: string; id: string; value?: unknown };
export function planRepair(drift: DriftItem[]): RepairOperation[] { if(drift.some(d=>!d.repairable)) throw new Error("business_memory_unrepairable_drift"); const rank={insert:0,update:1,deactivate:2,synchronize_fingerprint:3}; return drift.map(d=>({type:(d.repairAction === "insert" ? "insert" : d.repairAction === "deactivate" ? "deactivate" : d.repairAction === "synchronize_fingerprint" ? "synchronize_fingerprint" : "update") as RepairOperation["type"],model:d.model,id:d.affectedIds.join("|"),value:d.expected})).sort((a,b)=>rank[a.type]-rank[b.type]||a.model.localeCompare(b.model)||a.id.localeCompare(b.id)); }
