import { canonicalJson, resolveRedirect, validateMerge, type EntityAlias, type IdentityKey, type MergeCommand, type Redirect, type ResolvedEntity } from "./entity-reconciliation";
import { rewireRelationships, type BusinessRelationship } from "./relationship-rewiring";
export type MergeResult = { commandId: string; survivorId: string; mergedIds: string[]; startingRevision: number; resultingRevision: number; changedIds: Record<string, string[]>; redirectsCreated: Redirect[]; conflictsCreatedOrUpdated: string[]; relationshipsRewired: string[]; executedAt: string; disposition: "executed" | "replayed" };
export type MergeState = { projectId: string; revision: number; entities: ResolvedEntity[]; redirects: Redirect[]; aliases: EntityAlias[]; identityKeys: IdentityKey[]; relationships: BusinessRelationship[] };
export interface MergeTransaction { find(commandId: string): Promise<{ command: MergeCommand; result: MergeResult } | null>; load(projectId: string): Promise<MergeState>; save(state: MergeState, result: MergeResult): Promise<void>; }
export interface MergeStore { transaction<T>(commandId: string, callback: (transaction: MergeTransaction) => Promise<T>): Promise<T>; }
export class MergeExecutor { constructor(private readonly store: MergeStore, private readonly now: () => Date = () => new Date()) {} async execute(command: MergeCommand): Promise<MergeResult> { return this.store.transaction(command.commandId, async tx => { const committed = await tx.find(command.commandId); if (committed) { if (canonicalJson(committed.command) !== canonicalJson(command)) throw new Error("business_memory_merge_command_content_conflict"); return { ...committed.result, disposition: "replayed" }; }
 const state = await tx.load(command.projectId); validateMerge(command, state.revision, state.entities, state.redirects); const survivorId = resolveRedirect(command.survivorResolvedEntityId, state.redirects); const mergedIds = Array.from(new Set(command.mergedResolvedEntityIds.map(id => resolveRedirect(id, state.redirects))).values()).filter(id => id !== survivorId).sort();
 const strong = new Map<string, string>(); for (const key of state.identityKeys.filter(k => k.active !== false && k.strength === "strong" && k.authoritative)) { const owner = mergedIds.includes(key.resolvedEntityId) ? survivorId : resolveRedirect(key.resolvedEntityId, state.redirects); const name = `${key.type}:${key.normalizedValue}`; if (strong.has(name) && strong.get(name)! !== owner) throw new Error("business_memory_conflicting_strong_identity_key"); strong.set(name, owner); }
 const redirects = [...state.redirects.filter(x => !mergedIds.includes(x.fromResolvedEntityId)), ...mergedIds.map(fromResolvedEntityId => ({ fromResolvedEntityId, toResolvedEntityId: survivorId }))].sort((a,b) => a.fromResolvedEntityId.localeCompare(b.fromResolvedEntityId));
 const entities = state.entities.map(entity => mergedIds.includes(entity.id) ? { ...entity, active: false } : entity.id === survivorId ? { ...entity, sourceEntityIds: Array.from(new Set(state.entities.filter(x => x.id === survivorId || mergedIds.includes(x.id)).flatMap(x => x.sourceEntityIds))).sort() } : entity);
 const aliases = state.aliases.map(alias => mergedIds.includes(alias.resolvedEntityId) ? { ...alias, resolvedEntityId: survivorId } : alias);
 const identityKeys = state.identityKeys.map(key => mergedIds.includes(key.resolvedEntityId) ? { ...key, resolvedEntityId: survivorId } : key);
 const relationshipResult = rewireRelationships(state.relationships, redirects); const resultingRevision = state.revision + 1; const executedAt = this.now().toISOString(); const result: MergeResult = { commandId: command.commandId, survivorId, mergedIds, startingRevision: state.revision, resultingRevision, changedIds: { resolvedEntities: [survivorId, ...mergedIds].sort(), aliases: aliases.filter((a,i) => a.resolvedEntityId !== state.aliases[i].resolvedEntityId).map(a => a.id).sort(), identityKeys: identityKeys.filter((a,i) => a.resolvedEntityId !== state.identityKeys[i].resolvedEntityId).map(a => a.id).sort(), relationships: relationshipResult.changedIds }, redirectsCreated: redirects.filter(x => mergedIds.includes(x.fromResolvedEntityId)), conflictsCreatedOrUpdated: [], relationshipsRewired: relationshipResult.changedIds, executedAt, disposition: "executed" };
 await tx.save({ ...state, revision: resultingRevision, entities, redirects, aliases, identityKeys, relationships: relationshipResult.relationships }, result); return result; }); } }
