import type { AiBuilderSession } from "@/app/lib/ai-engine/contracts";
import type { PersistedWebsiteKnowledge } from "@/app/lib/ai-engine/knowledge/websiteKnowledge";

type Destination="knowledge"|"sources"|"settings"|"assistant";
type Message={role:"user"|"assistant";createdAt:string};
const date=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

export default function AiBuilderDashboard({session,websiteKnowledge,messages,onNavigate}:{session:AiBuilderSession;websiteKnowledge:PersistedWebsiteKnowledge|null;messages:Message[];onNavigate:(destination:Destination)=>void}){
 const pending=[...session.contextEntries,...session.faqEntries].filter(item=>item.status==="proposed").length;
 const unresolvedConflicts=session.conflicts.filter(item=>!item.resolved).length,missing=session.missingInformation.filter(item=>!item.resolved).length,warnings=websiteKnowledge?.warnings.length??0;
 const attention=[pending?{label:`${pending} item${pending===1?"":"s"} waiting for review`,detail:"Approve, correct, or remove proposed knowledge.",action:"knowledge" as const}:null,unresolvedConflicts?{label:`${unresolvedConflicts} unresolved conflict${unresolvedConflicts===1?"":"s"}`,detail:"Resolve contradictory business information.",action:"knowledge" as const}:null,missing?{label:`${missing} information gap${missing===1?"":"s"}`,detail:"Add details the assistant still needs.",action:"knowledge" as const}:null,warnings?{label:`${warnings} website import warning${warnings===1?"":"s"}`,detail:"Review source coverage and skipped content.",action:"sources" as const}:null,!websiteKnowledge?{label:"No website source connected",detail:"Import a website to broaden the assistant’s source material.",action:"sources" as const}:null,!messages.length?{label:"Assistant has not been tested",detail:"Run a few real customer questions before launch.",action:"assistant" as const}:null].filter((item):item is NonNullable<typeof item>=>Boolean(item));
 const recent=[...session.contextEntries.map(item=>({label:`Knowledge ${item.status}`,detail:item.title,at:item.updatedAt})),...session.faqEntries.map(item=>({label:`Q&A ${item.status}`,detail:item.question,at:item.updatedAt})),...(websiteKnowledge?.imported_at?[{label:"Website imported",detail:`${websiteKnowledge.pages.length} source page${websiteKnowledge.pages.length===1?"":"s"}`,at:websiteKnowledge.imported_at}]:[]),...messages.slice(-3).map(item=>({label:item.role==="user"?"Assistant test question":"Assistant test response",detail:"Demo conversation activity",at:item.createdAt}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,6);
 const sourceCounts=session.contextEntries.reduce<Record<string,number>>((counts,item)=>{const key=item.source.sourceType;counts[key]=(counts[key]??0)+1;return counts;},{});
 return <div className="space-y-6 pb-6">
  <section className="rounded-3xl border border-amber-300/20 bg-black p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Dashboard</p><div className="mt-3 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-3xl font-black tracking-[-.035em] text-white">Your next best actions</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">A working queue of what changed and what needs attention—not another project overview.</p></div><span className={`w-fit rounded-full border px-3 py-1.5 text-xs font-bold ${attention.length?"border-amber-300/25 bg-amber-300/10 text-amber-200":"border-emerald-300/20 bg-emerald-300/10 text-emerald-200"}`}>{attention.length?`${attention.length} area${attention.length===1?"":"s"} to review`:"No outstanding attention items"}</span></div></section>
  <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">Needs attention</h3>{attention.length?<div className="mt-4 divide-y divide-white/[.07]">{attention.map(item=><button key={item.label} type="button" onClick={()=>onNavigate(item.action)} className="group flex w-full items-center justify-between gap-4 py-4 text-left"><div><p className="font-semibold text-white">{item.label}</p><p className="mt-1 text-sm text-slate-500">{item.detail}</p></div><span className="text-amber-300 transition group-hover:translate-x-1">→</span></button>)}</div>:<Empty text="This project has no outstanding review, source, or testing tasks."/>}</section>
  <section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">Knowledge source mix</h3>{Object.keys(sourceCounts).length?<dl className="mt-5 space-y-3">{Object.entries(sourceCounts).sort((a,b)=>b[1]-a[1]).map(([source,count])=><div key={source} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-black px-4 py-3"><dt className="text-sm capitalize text-slate-400">{source.replaceAll("_"," ")}</dt><dd className="font-black text-white">{count}</dd></div>)}</dl>:<Empty text="Source composition will appear after knowledge is generated."/>}<Action onClick={()=>onNavigate("sources")}>Inspect source material</Action></section></div>
  <section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><div className="flex items-center justify-between gap-4"><div><h3 className="text-lg font-bold text-white">Recent project changes</h3><p className="mt-1 text-sm text-slate-500">Latest persisted knowledge, import, and assistant activity.</p></div><Action onClick={()=>onNavigate("settings")}>Project settings</Action></div>{recent.length?<div className="mt-5 divide-y divide-white/[.07]">{recent.map((item,index)=><div key={`${item.label}-${item.at}-${index}`} className="grid gap-1 py-3 sm:grid-cols-[11rem_1fr_auto] sm:items-center sm:gap-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-amber-200">{item.label}</p><p className="truncate text-sm text-slate-300">{item.detail}</p><time className="text-xs text-slate-500">{date(item.at)}</time></div>)}</div>:<Empty text="No project changes have been recorded yet."/>}</section>
 </div>;
}
function Action({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button type="button" onClick={onClick} className="cta-raised mt-5 rounded-xl border border-amber-300/20 bg-black px-4 py-2.5 text-sm font-bold text-white hover:border-amber-300/40">{children}</button>}
function Empty({text}:{text:string}){return <p className="mt-4 rounded-2xl border border-dashed border-white/10 bg-black p-5 text-sm leading-6 text-slate-500">{text}</p>}
