import type { AiBuilderSession } from "@/app/lib/ai-engine/contracts";
export type ProjectDiagnostics={crawls:Array<Record<string,unknown>>;generations:Array<Record<string,unknown>>};
const n=(value:unknown)=>typeof value==="number"?value:null;
const when=(value:unknown)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(value))):null;
export default function AiBuilderProjectInsights({session,diagnostics,messageCount}:{session:AiBuilderSession;diagnostics:ProjectDiagnostics|null;messageCount:number}){const crawl=diagnostics?.crawls[0],generation=diagnostics?.generations[0];return <div className="space-y-6 pb-6"><section className="rounded-3xl border border-amber-300/20 bg-black p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Project insights</p><h2 className="mt-3 text-3xl font-black tracking-[-.035em] text-white">Operations and generation</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Project-owned crawl, generation, and assistant activity. Missing diagnostics are omitted rather than estimated.</p></section>
 <section className="grid gap-6 lg:grid-cols-2"><Panel title="Website crawl" empty={!crawl} emptyText="No crawl history is available yet.">{crawl?<><Status value={crawl.status}/><Grid items={[["Last crawl",when(crawl.completed_at??crawl.started_at)],["Discovered",n(crawl.pages_discovered)],["Processed",n(crawl.pages_processed)],["Skipped",n(crawl.pages_skipped)],["Failed",n(crawl.pages_failed)],["Duration",n(crawl.duration_ms)!=null?`${Math.round(n(crawl.duration_ms)!/1000)}s`:null]]}/>{Array.isArray(crawl.warnings)&&crawl.warnings.length?<p className="mt-4 text-sm text-amber-200">{crawl.warnings.length} crawl warning{crawl.warnings.length===1?"":"s"}</p>:null}</>:null}</Panel>
 <Panel title="Knowledge generation" empty={!generation} emptyText="No generation attempt is available yet.">{generation?<><Status value={generation.status}/><Grid items={[["Last attempt",when(generation.completed_at??generation.started_at)],["Knowledge items",n(generation.knowledge_count)],["Generated Q&A",n(generation.faq_count)],["Model",generation.model?String(generation.model):null],["Tokens",n(generation.total_tokens)],["Duration",n(generation.duration_ms)!=null?`${Math.round(n(generation.duration_ms)!/1000)}s`:null]]}/></>:null}</Panel></section>
 {diagnostics&&(diagnostics.crawls.length>1||diagnostics.generations.length>1)?<section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">Recent attempts</h3><div className="mt-4 divide-y divide-white/[.07]">{[...diagnostics.crawls.slice(0,5).map(item=>({kind:"Website crawl",...item} as Record<string,unknown>&{kind:string})),...diagnostics.generations.slice(0,5).map(item=>({kind:"Knowledge generation",...item} as Record<string,unknown>&{kind:string}))].sort((a,b)=>String(b.started_at).localeCompare(String(a.started_at))).slice(0,6).map((item,index)=><div key={`${item.kind}-${index}`} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-semibold text-slate-200">{item.kind}</p><p className="mt-1 text-xs text-slate-500">{when(item.started_at)}</p></div><Status value={item.status}/></div>)}</div></section>:null}
 <section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">Project activity</h3><Grid items={[["Assistant messages",messageCount||null],["Knowledge records",session.contextEntries.length||null],["Q&A records",session.faqEntries.length||null],["Last project update",when(session.updatedAt)]]}/>{!messageCount&&!session.contextEntries.length&&!session.faqEntries.length?<p className="mt-4 text-sm text-slate-500">Activity will appear as the project is built and tested.</p>:null}</section></div>}
function Panel({title,empty,emptyText,children}:{title:string;empty:boolean;emptyText:string;children:React.ReactNode}){return <section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">{title}</h3>{empty?<p className="mt-4 rounded-2xl border border-dashed border-white/10 bg-black p-5 text-sm text-slate-500">{emptyText}</p>:<div className="mt-4">{children}</div>}</section>}
function Status({value}:{value:unknown}){return <span className="inline-flex rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-1 text-xs font-bold capitalize text-amber-200">{String(value??"Unknown").replaceAll("_"," ")}</span>}
function Grid({items}:{items:Array<[string,unknown]>}){const visible=items.filter(([,value])=>value!==null&&value!==undefined);return <dl className="mt-4 grid gap-px overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.08] sm:grid-cols-2">{visible.map(([label,value])=><div key={label} className="bg-black p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-bold text-white">{String(value)}</dd></div>)}</dl>}
