import type { AiBuilderSession } from "@/app/lib/ai-engine/contracts";
import type { PersistedWebsiteKnowledge } from "@/app/lib/ai-engine/knowledge/websiteKnowledge";

type Destination="knowledge"|"sources"|"settings"|"assistant";
const date=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value));

export default function AiBuilderDashboard({session,businessName,industry,website,websiteKnowledge,messageCount,onNavigate}:{session:AiBuilderSession;businessName:string;industry:string;website:string;websiteKnowledge:PersistedWebsiteKnowledge|null;messageCount:number;onNavigate:(destination:Destination)=>void}){
 const all=[...session.contextEntries,...session.faqEntries],count=(status:string)=>all.filter(item=>item.status===status).length;
 const completed=session.buildProgress.filter(item=>item.completed).length,progress=session.buildProgress.length?Math.round(completed/session.buildProgress.length*100):session.status==="ready"?100:0;
 return <div className="space-y-6 pb-6">
  <section className="rounded-3xl border border-amber-300/20 bg-black p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Project dashboard</p><h2 className="mt-3 text-3xl font-black tracking-[-.035em] text-white">{businessName||"Your AI project"}</h2><p className="mt-2 text-sm text-slate-400">{industry||"Industry not added"} · {website?"Website connected":"No website connected"}</p></div><div className="min-w-[190px]"><div className="flex justify-between text-xs text-slate-400"><span>Workflow readiness</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-amber-300" style={{width:`${progress}%`}} /></div></div></div>
  <div className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 xl:grid-cols-4">{[["Status",session.status.replaceAll("_"," ")],["Business knowledge",String(session.contextEntries.length)],["Generated Q&A",String(session.faqEntries.length)],["Assistant messages",messageCount?String(messageCount):"No messages yet"]].map(([label,value])=><div key={label} className="bg-[#070707] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-bold capitalize text-white">{value}</p></div>)}</div></section>
  <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">Knowledge review</h3><p className="mt-1 text-sm text-slate-400">See what is ready and what still needs attention.</p><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Approved",count("approved")],["Corrected",count("corrected")],["Pending",count("proposed")],["Removed",count("archived")]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/[.08] bg-black p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-2xl font-black text-white">{value}</dd></div>)}</dl><div className="mt-5 flex flex-wrap gap-2"><Action onClick={()=>onNavigate("knowledge")}>Review business knowledge</Action><Action onClick={()=>onNavigate("sources")}>View sources</Action></div></section>
  <section className="rounded-3xl border border-white/10 bg-[#050505] p-6"><h3 className="text-lg font-bold text-white">Project details</h3><dl className="mt-5 space-y-4 text-sm"><Row label="Created" value={date(session.createdAt)}/><Row label="Last updated" value={date(session.updatedAt)}/><Row label="Website source" value={websiteKnowledge?`${websiteKnowledge.pages.length} pages imported`:"Not imported"}/></dl><div className="mt-6 grid gap-2"><Action onClick={()=>onNavigate("assistant")}>Test assistant</Action><Action onClick={()=>onNavigate("settings")}>Open settings</Action></div></section></div>
 </div>;
}
function Action({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button type="button" onClick={onClick} className="cta-raised rounded-xl border border-amber-300/20 bg-black px-4 py-2.5 text-sm font-bold text-white hover:border-amber-300/40">{children}</button>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b border-white/[.07] pb-3"><dt className="text-slate-500">{label}</dt><dd className="text-right font-semibold text-slate-200">{value}</dd></div>}
