/** Canonical, thread-only conversation memory. It is deliberately not business knowledge. */
export const CONVERSATION_MEMORY_SCHEMA_VERSION = 1 as const;
export type ConversationMemoryStatus = "active" | "paused" | "completed";
export type ConversationPreferenceScope = "current_thread" | "current_task";
export type ConversationFollowUpStatus = "open" | "resolved" | "dismissed";
export type ConversationDetail = { id: string; key: string; value: string; confidence: "high" | "medium" | "low"; sourceMessageId: string; createdAt: string; updatedAt: string };
export type ConversationPreference = { id: string; key: string; value: string; scope: ConversationPreferenceScope; sourceMessageId: string; createdAt: string; updatedAt: string };
export type ConversationFollowUp = { id: string; topic: string; question: string; sourceMessageId: string; status: ConversationFollowUpStatus; createdAt: string; resolvedAt: string | null; resolutionMessageId: string | null };
export type SummaryCoverage = { lastSummarizedMessageId: string | null; lastSummarizedMessageAt: string | null; summarizedMessageCount: number; summaryVersion: number; generatedAt: string | null };
export type CanonicalConversationMemory = {
 schemaVersion: typeof CONVERSATION_MEMORY_SCHEMA_VERSION; revision: number; threadId: string; projectId: string; status: ConversationMemoryStatus;
 currentSubject: string | null; primaryGoal: string | null; selectedService: string | null; temporaryContext: string[]; /** legacy read-only compatibility fields; never persisted by this module. */ customerGoal: string | null; collectedDetails: { key: string; value: string }[]; unresolvedQuestions: string[]; userPreferences: ConversationPreference[]; conversationDetails: ConversationDetail[]; unresolvedFollowUps: ConversationFollowUp[]; recentClarifications: string[]; summary: string; summaryCoverage: SummaryCoverage; stickyState: Record<string, unknown>; createdAt: string; updatedAt: string;
};
const text=(v:unknown,n=800)=>typeof v === "string" ? v.replace(/\0/g, "").replace(/\s+/g," ").trim().slice(0,n) : "";
const date=(v:unknown, fallback:string)=> { const d=new Date(typeof v === "string" ? v : fallback); return Number.isNaN(d.getTime()) ? fallback : d.toISOString(); };
const arr=(v:unknown,n:number)=>Array.isArray(v)? Array.from(new Set(v.map(x=>text(x)).filter(Boolean).map(x=>x.toLowerCase()))).slice(0,n):[];
const id=(prefix:string, value:string, i:number)=>`${prefix}_${value.toLowerCase().replace(/[^a-z0-9]+/g,"_").slice(0,48) || i}`;
export function createConversationMemory(threadId:string, projectId:string, now=new Date().toISOString()): CanonicalConversationMemory { return {schemaVersion:1,revision:0,threadId,projectId,status:"active",currentSubject:null,primaryGoal:null,selectedService:null,temporaryContext:[],userPreferences:[],conversationDetails:[],unresolvedFollowUps:[],recentClarifications:[],summary:"Thread not started.",summaryCoverage:{lastSummarizedMessageId:null,lastSummarizedMessageAt:null,summarizedMessageCount:0,summaryVersion:0,generatedAt:null},stickyState:{},customerGoal:null,collectedDetails:[],unresolvedQuestions:[],createdAt:now,updatedAt:now}; }
export function normalizeConversationMemory(raw:unknown, owner:{threadId:string;projectId:string}, now=new Date().toISOString()): {memory:CanonicalConversationMemory; legacyNormalized:boolean; invalid:boolean} {
 const base=createConversationMemory(owner.threadId,owner.projectId,now); if (!raw || typeof raw!=="object" || Array.isArray(raw)) return {memory:base,legacyNormalized:Boolean(raw),invalid:Boolean(raw)};
 const r=raw as Record<string,unknown>; if (typeof r.schemaVersion === "number" && r.schemaVersion !== 1) return {memory:base,legacyNormalized:false,invalid:true};
 const legacy= r.schemaVersion !== 1; const sourceDetails=Array.isArray(r.conversationDetails)?r.conversationDetails:Array.isArray(r.collectedDetails)?r.collectedDetails:[];
 const details=sourceDetails.map((x,i): Record<string, unknown>=> typeof x === "object" && x ? x as Record<string,unknown> : {key:`detail_${i}`,value:x}).map((x,i)=>({id:text(x.id)||id("detail",text(x.key)||`detail_${i}`,i),key:text(x.key)||`detail_${i}`,value:text(x.value),confidence:(x.confidence==="high"||x.confidence==="low"?x.confidence:"medium") as "high" | "medium" | "low",sourceMessageId:text(x.sourceMessageId)||text(x.sourceTurnId)||"legacy",createdAt:date(x.createdAt,now),updatedAt:date(x.updatedAt,now)})).filter(x=>x.value).sort((a,b)=>a.id.localeCompare(b.id)).filter((x,i,a)=>!i||a[i-1].id!==x.id).slice(0,40);
 const prefs=(Array.isArray(r.userPreferences)?r.userPreferences:[]).map((x,i)=>x as Record<string,unknown>).map((x,i)=>({id:text(x.id)||id("preference",text(x.key),i),key:text(x.key),value:text(x.value),scope:x.scope==="current_task"?"current_task" as const:"current_thread" as const,sourceMessageId:text(x.sourceMessageId)||"legacy",createdAt:date(x.createdAt,now),updatedAt:date(x.updatedAt,now)})).filter(x=>x.key&&x.value).sort((a,b)=>a.id.localeCompare(b.id)).filter((x,i,a)=>!i||a[i-1].id!==x.id).slice(0,20);
 const follow=(Array.isArray(r.unresolvedFollowUps)?r.unresolvedFollowUps:Array.isArray(r.unresolvedQuestions)?r.unresolvedQuestions:[]).map((x,i): Record<string, unknown>=>typeof x === "object"&&x?x as Record<string,unknown>:{question:x}).map((x,i)=>({id:text(x.id)||id("followup",text(x.question),i),topic:text(x.topic)||"conversation",question:text(x.question),sourceMessageId:text(x.sourceMessageId)||"legacy",status:x.status==="resolved"||x.status==="dismissed"?x.status:"open" as ConversationFollowUpStatus,createdAt:date(x.createdAt,now),resolvedAt:x.resolvedAt?date(x.resolvedAt,now):null,resolutionMessageId:text(x.resolutionMessageId)||null})).filter(x=>x.question).sort((a,b)=>a.id.localeCompare(b.id)).filter((x,i,a)=>!i||a[i-1].id!==x.id).slice(0,20);
 const coverage=(r.summaryCoverage&&typeof r.summaryCoverage==="object"?r.summaryCoverage:{}) as Record<string,unknown>;
 return {memory:{...base,revision:Number.isInteger(r.revision)&&Number(r.revision)>=0?Number(r.revision):0,status:r.status==="paused"||r.status==="completed"?r.status:"active",currentSubject:text(r.currentSubject)||null,primaryGoal:text(r.primaryGoal)||text(r.customerGoal)||null,selectedService:text(r.selectedService)||null,temporaryContext:arr(r.temporaryContext ?? r.activeConstraints,12),customerGoal:text(r.primaryGoal)||text(r.customerGoal)||null,collectedDetails:details.map(({key,value})=>({key,value})),unresolvedQuestions:follow.filter(x=>x.status === "open").map(x=>x.question),userPreferences:prefs,conversationDetails:details,unresolvedFollowUps:follow,recentClarifications:arr(r.recentClarifications,12),summary:text(r.summary,3000)||base.summary,summaryCoverage:{lastSummarizedMessageId:text(coverage.lastSummarizedMessageId)||null,lastSummarizedMessageAt:coverage.lastSummarizedMessageAt?date(coverage.lastSummarizedMessageAt,now):null,summarizedMessageCount:Number.isInteger(coverage.summarizedMessageCount)&&Number(coverage.summarizedMessageCount)>=0?Number(coverage.summarizedMessageCount):0,summaryVersion:Number.isInteger(coverage.summaryVersion)&&Number(coverage.summaryVersion)>=0?Number(coverage.summaryVersion):0,generatedAt:coverage.generatedAt?date(coverage.generatedAt,now):null},stickyState:r.stickyState&&typeof r.stickyState==="object"&&!Array.isArray(r.stickyState)?r.stickyState as Record<string, unknown>:{},createdAt:date(r.createdAt ?? r.lastUpdatedAt,now),updatedAt:date(r.updatedAt ?? r.lastUpdatedAt,now)},legacyNormalized:legacy,invalid:false};
}
export type MemoryMessage={id:string;role:string;content:string;createdAt:string};
/** Deterministic bounded summary: no business stores, projection, or configuration are accepted. */
export function updateConversationSummary(memory:CanonicalConversationMemory,messages:MemoryMessage[],now=new Date().toISOString()): CanonicalConversationMemory { const fresh=messages.filter(m=>m.id!==memory.summaryCoverage.lastSummarizedMessageId).slice(-12); if(!fresh.length)return memory; const tail=fresh.map(m=>`${m.role}: ${text(m.content,500)}`).join(" ").slice(0,3000); return {...memory,summary:text(`${memory.summary === "Thread not started." ? "" : memory.summary} ${tail}`,3000),summaryCoverage:{lastSummarizedMessageId:fresh.at(-1)!.id,lastSummarizedMessageAt:date(fresh.at(-1)!.createdAt,now),summarizedMessageCount:memory.summaryCoverage.summarizedMessageCount+fresh.length,summaryVersion:memory.summaryCoverage.summaryVersion+1,generatedAt:now},updatedAt:now}; }
