/** Canonical, thread-only conversation memory. It is deliberately not business knowledge. */
export const CONVERSATION_MEMORY_SCHEMA_VERSION = 1 as const;
export type ConversationMemoryStatus = "active" | "paused" | "completed";
export type ConversationPreferenceScope = "current_thread" | "current_task";
export type ConversationFollowUpStatus = "open" | "resolved" | "dismissed";
export type ConversationDetail = { id:string; key:string; value:string; confidence:"high"|"medium"|"low"; sourceMessageId:string; createdAt:string; updatedAt:string };
export type ConversationPreference = { id:string; key:string; value:string; scope:ConversationPreferenceScope; sourceMessageId:string; createdAt:string; updatedAt:string };
export type ConversationFollowUp = { id:string; topic:string; question:string; sourceMessageId:string; status:ConversationFollowUpStatus; createdAt:string; resolvedAt:string|null; resolutionMessageId:string|null };
export type SummaryCoverage = { lastSummarizedMessageId:string|null; lastSummarizedMessageAt:string|null; summarizedMessageCount:number; summaryVersion:number; generatedAt:string|null };
export type CanonicalConversationMemory = { schemaVersion:typeof CONVERSATION_MEMORY_SCHEMA_VERSION; revision:number; threadId:string; projectId:string; status:ConversationMemoryStatus; currentSubject:string|null; primaryGoal:string|null; selectedService:string|null; temporaryContext:string[]; userPreferences:ConversationPreference[]; conversationDetails:ConversationDetail[]; unresolvedFollowUps:ConversationFollowUp[]; recentClarifications:string[]; summary:string; summaryCoverage:SummaryCoverage; stickyState:Record<string,unknown>; /** Input compatibility only; persistence strips these aliases. */ customerGoal:string|null; collectedDetails:{key:string;value:string}[]; unresolvedQuestions:string[]; createdAt:string; updatedAt:string };
type LegacyMemory = CanonicalConversationMemory & { customerGoal?:string|null; collectedDetails?:unknown[]; unresolvedQuestions?:unknown[] };
const clean=(v:unknown,n=800)=>typeof v === "string" ? v.replace(/\0/g,"").replace(/\s+/g," ").trim().slice(0,n) : "";
const when=(v:unknown,fallback:string)=>{const d=new Date(typeof v === "string"?v:fallback);return Number.isNaN(d.getTime())?fallback:d.toISOString();};
const strings=(v:unknown,n:number)=>Array.isArray(v)?Array.from(new Set(v.map(x=>clean(x)).filter(Boolean))).slice(0,n):[];
const keyId=(prefix:string,value:string,i:number)=>`${prefix}_${value.toLowerCase().replace(/[^a-z0-9]+/g,"_").slice(0,48)||i}`;
export function createConversationMemory(threadId:string,projectId:string,now=new Date().toISOString()):CanonicalConversationMemory{return {schemaVersion:1,revision:0,threadId,projectId,status:"active",currentSubject:null,primaryGoal:null,selectedService:null,temporaryContext:[],userPreferences:[],conversationDetails:[],unresolvedFollowUps:[],recentClarifications:[],summary:"Thread not started.",summaryCoverage:{lastSummarizedMessageId:null,lastSummarizedMessageAt:null,summarizedMessageCount:0,summaryVersion:0,generatedAt:null},stickyState:{},customerGoal:null,collectedDetails:[],unresolvedQuestions:[],createdAt:now,updatedAt:now};}
export function normalizeConversationMemory(raw:unknown,owner:{threadId:string;projectId:string},now=new Date().toISOString()):{memory:CanonicalConversationMemory;legacyNormalized:boolean;invalid:boolean}{
 const base=createConversationMemory(owner.threadId,owner.projectId,now); if(!raw||typeof raw!=="object"||Array.isArray(raw))return {memory:base,legacyNormalized:Boolean(raw),invalid:Boolean(raw)};
 const r=raw as Record<string,unknown>; if((typeof r.schemaVersion==="number"&&r.schemaVersion!==1)||(r.schemaVersion===1&&(r.threadId!==owner.threadId||r.projectId!==owner.projectId)))return {memory:base,legacyNormalized:false,invalid:true};
 const legacy=r.schemaVersion!==1; const old=r as LegacyMemory; const detailInput=Array.isArray(r.conversationDetails)?r.conversationDetails:Array.isArray(old.collectedDetails)?old.collectedDetails:[];
 const details=detailInput.map((v,i)=>{const x:Record<string,unknown>=typeof v==="object"&&v?v as Record<string,unknown>:{value:v};const k=clean(x.key)||`detail_${i}`;return {id:clean(x.id)||keyId("detail",k,i),key:k,value:clean(x.value),confidence:(x.confidence==="high"||x.confidence==="low"?x.confidence:"medium") as ConversationDetail["confidence"],sourceMessageId:clean(x.sourceMessageId)||"legacy",createdAt:when(x.createdAt,now),updatedAt:when(x.updatedAt,now)}}).filter(x=>x.value).slice(0,40);
 const preferences=Array.from((Array.isArray(r.userPreferences)?r.userPreferences:[]).reduce<Map<string,ConversationPreference>>((byId,v)=>{if(!v||typeof v!=="object"||Array.isArray(v))return byId;const x=v as Record<string,unknown>;const id=clean(x.id);const key=clean(x.key);const value=clean(x.value);if(!id||!key||!value||(x.scope!=="current_thread"&&x.scope!=="current_task"))return byId;const preference={id,key,value,scope:x.scope as ConversationPreferenceScope,sourceMessageId:clean(x.sourceMessageId)||"legacy",createdAt:when(x.createdAt,now),updatedAt:when(x.updatedAt,now)};const existing=byId.get(id);const rank=(p:ConversationPreference)=>`${p.updatedAt}\u0000${p.createdAt}\u0000${p.key}\u0000${p.value}\u0000${p.scope}\u0000${p.sourceMessageId}`;if(!existing||rank(preference)>rank(existing))byId.set(id,preference);return byId;},new Map<string,ConversationPreference>()).values()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.updatedAt.localeCompare(b.updatedAt)||a.id.localeCompare(b.id)).slice(-20);
 const followInput=Array.isArray(r.unresolvedFollowUps)?r.unresolvedFollowUps:Array.isArray(old.unresolvedQuestions)?old.unresolvedQuestions:[];
 const follows=followInput.map((v,i)=>{const x:Record<string,unknown>=typeof v==="object"&&v?v as Record<string,unknown>:{question:v};const q=clean(x.question);return {id:clean(x.id)||keyId("followup",q,i),topic:clean(x.topic)||"conversation",question:q,sourceMessageId:clean(x.sourceMessageId)||"legacy",status:x.status==="resolved"||x.status==="dismissed"?x.status:"open" as ConversationFollowUpStatus,createdAt:when(x.createdAt,now),resolvedAt:x.resolvedAt?when(x.resolvedAt,now):null,resolutionMessageId:clean(x.resolutionMessageId)||null}}).filter(x=>x.question).slice(0,20);
 const c=(r.summaryCoverage&&typeof r.summaryCoverage==="object"?r.summaryCoverage:{}) as Record<string,unknown>;
 return {memory:{...base,revision:Number.isInteger(r.revision)&&Number(r.revision)>=0?Number(r.revision):0,status:r.status==="paused"||r.status==="completed"?r.status:"active",currentSubject:clean(r.currentSubject)||null,primaryGoal:clean(r.primaryGoal)||clean(old.customerGoal)||null,selectedService:clean(r.selectedService)||null,temporaryContext:strings(r.temporaryContext??r.activeConstraints,12),customerGoal:clean(r.primaryGoal)||clean(old.customerGoal)||null,collectedDetails:details.map(({key,value})=>({key,value})),unresolvedQuestions:follows.filter(x=>x.status==="open").map(x=>x.question),userPreferences:preferences,conversationDetails:details,unresolvedFollowUps:follows,recentClarifications:strings(r.recentClarifications,12),summary:clean(r.summary,1800)||base.summary,summaryCoverage:{lastSummarizedMessageId:clean(c.lastSummarizedMessageId)||null,lastSummarizedMessageAt:c.lastSummarizedMessageAt?when(c.lastSummarizedMessageAt,now):null,summarizedMessageCount:Number.isInteger(c.summarizedMessageCount)&&Number(c.summarizedMessageCount)>=0?Number(c.summarizedMessageCount):0,summaryVersion:Number.isInteger(c.summaryVersion)&&Number(c.summaryVersion)>=0?Number(c.summaryVersion):0,generatedAt:c.generatedAt?when(c.generatedAt,now):null},stickyState:r.stickyState&&typeof r.stickyState==="object"&&!Array.isArray(r.stickyState)?r.stickyState as Record<string,unknown>:{},createdAt:when(r.createdAt,now),updatedAt:when(r.updatedAt,now)},legacyNormalized:legacy,invalid:false};
}
export type MemoryMessage={id:string;role:string;content:string;createdAt:string};
/** Produces a bounded state summary, never a transcript. */
export function updateConversationSummary(memory:CanonicalConversationMemory,messages:MemoryMessage[],now=new Date().toISOString()):CanonicalConversationMemory{
 const ordered=[...messages].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id)); const marker=memory.summaryCoverage.lastSummarizedMessageId; const start=marker?ordered.findIndex(m=>m.id===marker)+1:0; const fresh=(start<0?[]:ordered.slice(start)).slice(0,12); if(!fresh.length)return memory;
 const newUser=fresh.filter(m=>m.role==="user").map(m=>clean(m.content,180)).slice(-3); const parts=[memory.primaryGoal&&`Goal: ${memory.primaryGoal}`,memory.currentSubject&&`Subject: ${memory.currentSubject}`,memory.selectedService&&`Service: ${memory.selectedService}`,memory.temporaryContext.length&&`Context: ${memory.temporaryContext.join("; ")}`,memory.recentClarifications.length&&`Clarifications: ${memory.recentClarifications.join("; ")}`,memory.unresolvedFollowUps.filter(x=>x.status==="open").length&&`Open: ${memory.unresolvedFollowUps.filter(x=>x.status==="open").map(x=>x.question).join("; ")}`,newUser.length&&`Recent user updates: ${newUser.join("; ")}`].filter(Boolean).join(". ");
 return {...memory,summary:clean(parts||memory.summary,1800),summaryCoverage:{lastSummarizedMessageId:fresh.at(-1)!.id,lastSummarizedMessageAt:when(fresh.at(-1)!.createdAt,now),summarizedMessageCount:memory.summaryCoverage.summarizedMessageCount+fresh.length,summaryVersion:memory.summaryCoverage.summaryVersion+1,generatedAt:now},updatedAt:now};
}
/** Small deterministic extraction retains thread intent without writing business truth. */
export function updateStructuredConversationMemory(memory:CanonicalConversationMemory,messages:MemoryMessage[],now=new Date().toISOString()):CanonicalConversationMemory { const user=messages.filter(m=>m.role==="user").at(-1); if(!user)return memory; const value=clean(user.content,500); const low=value.toLowerCase(); let next={...memory}; if(/\b(start over|reset)\b/.test(low)) next={...createConversationMemory(memory.threadId,memory.projectId,now),revision:memory.revision,createdAt:memory.createdAt}; else { if(/\b(back to|resume|continue)\b/.test(low)) next.status="active"; if(/\b(pause|hold)\b/.test(low))next.status="paused"; const subject=(value.match(/(?:about|for)\s+([^?.!]+)/i)?.[1]||"").trim(); if(subject)next.currentSubject=subject; if(/\b(i need|i want|help me|goal is)\b/i.test(value))next.primaryGoal=value; const service=value.match(/(?:service|package)\s*(?:is|:)?\s*([^?.!]+)/i)?.[1]?.trim(); if(service)next.selectedService=service; if(/\?\s*$/.test(value)){const f={id:keyId("followup",value,0),topic:next.currentSubject||"conversation",question:value,sourceMessageId:user.id,status:"open" as const,createdAt:now,resolvedAt:null,resolutionMessageId:null};next.unresolvedFollowUps=[...next.unresolvedFollowUps.filter(x=>x.question!==value),f].slice(-20);} if(/\bactually|instead|clarif/i.test(low))next.recentClarifications=[...next.recentClarifications,value].slice(-12); if(/\b(today|tomorrow|budget|deadline|prefer)\b/.test(low))next.temporaryContext=[...next.temporaryContext,value].slice(-12); if(/\bprefer\b/.test(low)){const preference={id:keyId("preference",value,0),key:"preference",value,scope:"current_thread" as const,sourceMessageId:user.id,createdAt:now,updatedAt:now};next.userPreferences=[...next.userPreferences.filter(x=>x.id!==preference.id),preference].slice(-20);} if(value){const detail={id:keyId("detail",value,0),key:"recent_input",value,confidence:"medium" as const,sourceMessageId:user.id,createdAt:now,updatedAt:now};next.conversationDetails=[...next.conversationDetails.filter(x=>x.id!==detail.id),detail].slice(-40);} } return {...next,updatedAt:now}; }
