import Link from "next/link";
import { requireAdmin } from "@/app/lib/admin/auth";
import { listAdminProjects } from "@/app/lib/admin/repository";
import { Badge, EmptyState, PageHeader, Pagination, SearchBar, card, formatDate, td, th } from "../_components/AdminUi";

export default async function AdminProjectsPage({ searchParams }: { searchParams: { q?: string; status?: string; sort?: string; owner?: string; page?: string } }) {
  await requireAdmin(); const q=(searchParams.q||"").toLowerCase(), status=searchParams.status||"all", sort=searchParams.sort||"updated";
  let rows=(await listAdminProjects()).filter(p => (!q || [p.businessName,p.ownerName||"",p.ownerEmail||"",p.industry].some(v=>v.toLowerCase().includes(q))) && (status==="all" || p.status===status) && (!searchParams.owner || p.clerkUserId===searchParams.owner));
  rows.sort((a,b)=>sort==="business"?a.businessName.localeCompare(b.businessName):sort==="created"?+new Date(b.createdAt)-+new Date(a.createdAt):+new Date(b.updatedAt)-+new Date(a.updatedAt));
  const size=25,pages=Math.max(1,Math.ceil(rows.length/size)),page=Math.min(pages,Math.max(1,Number(searchParams.page)||1)); rows=rows.slice((page-1)*size,page*size);
  return <div className="space-y-8"><PageHeader eyebrow="AI Builder" title="Projects" description="Every active AI Builder project, its workflow state, knowledge, and purchase intent." />
    <SearchBar placeholder="Search business, owner, email, or industry" defaultValue={searchParams.q} extras={<><select name="status" defaultValue={status} className="rounded-xl border border-amber-300/15 bg-[#020611] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-amber-300/50"><option value="all">All statuses</option><option value="draft">Draft</option><option value="extracting">Extracting</option><option value="review_required">Review required</option><option value="ready">Ready</option><option value="failed">Failed</option><option value="expired">Expired</option></select><select name="sort" defaultValue={sort} className="rounded-xl border border-amber-300/15 bg-[#020611] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-amber-300/50"><option value="updated">Recently updated</option><option value="created">Recently created</option><option value="business">Business name</option></select>{searchParams.owner&&<input type="hidden" name="owner" value={searchParams.owner}/>}</>} />
    {!rows.length?<EmptyState title="No projects found" detail="Adjust the search or filter to see other projects."/>:<div className={`${card} overflow-x-auto`}><table className="w-full min-w-[1150px]"><thead className="border-b border-amber-300/10 bg-amber-300/[.025]"><tr>{["Business","Owner","Workflow","Website","Knowledge","Generated Q&A","Purchase","Created","Updated"].map(x=><th key={x} className={th}>{x}</th>)}</tr></thead><tbody className="divide-y divide-amber-300/[.07]">{rows.map(p=><tr key={p.id} className="transition hover:bg-amber-300/[.025]"><td className={`${td} font-bold text-white`}><Link href={`/admin/projects/${p.id}`} className="hover:text-amber-300">{p.businessName}</Link><p className="mt-1 text-xs font-normal text-slate-500">{p.industry}</p></td><td className={td}>{p.ownerName||"Anonymous"}<p className="text-xs text-slate-500">{p.ownerEmail||"No account"}</p></td><td className={td}><Badge tone={p.status==="ready"?"good":"neutral"}>{p.status}</Badge></td><td className={td}><Badge tone={p.website?"good":"neutral"}>{p.website?"Connected":"Not connected"}</Badge></td><td className={td}>{p.knowledgeCount}</td><td className={td}>{p.faqCount}</td><td className={td}><Badge tone={p.purchaseRequested?"gold":"neutral"}>{p.purchaseRequested?"Requested":"No"}</Badge></td><td className={td}>{formatDate(p.createdAt)}</td><td className={td}>{formatDate(p.updatedAt)}</td></tr>)}</tbody></table></div>}
    <Pagination page={page} pages={pages} params={{q:searchParams.q,status,sort,owner:searchParams.owner}} /></div>;
}
