import "server-only";

import type { PoolClient } from "@neondatabase/serverless";
import type { AiBuilderProvenanceClassification } from "@/app/lib/ai-engine/provenance";
import type { KnowledgeFact, KnowledgeFaq, KnowledgePack, KnowledgeProvenance } from "./contracts";

export const REVIEW_STATES = ["proposed", "approved", "corrected", "archived"] as const;
type ReviewState = (typeof REVIEW_STATES)[number];
type SourceKind = "context_entry" | "faq";
type QueryClient = Pick<PoolClient, "query">;

export class TrustedKnowledgeProjectionError extends Error {
  readonly code: "invalid_trusted_projection_source_state" | "trusted_knowledge_projection_invalid_source" | "trusted_knowledge_projection_reconciliation_failed" | "trusted_knowledge_projection_stale";
  readonly details?: Record<string, unknown>;
  constructor(code: TrustedKnowledgeProjectionError["code"], message: string, details?: Record<string, unknown>) { super(message); this.code = code; this.details = details; }
}

type ContextSource = { intakeBlockId: string; excerpt: string; sourceType: string; sourceUrl?: string | null };
type ContextRow = { id: unknown; category: unknown; title: unknown; content: unknown; confidence: unknown; confidence_score: unknown; status: unknown; source: unknown; metadata: unknown; created_at: unknown; updated_at: unknown };
type FaqRow = { id: unknown; question: unknown; answer: unknown; confidence: unknown; confidence_score: unknown; source_entry_ids: unknown; status: unknown; metadata: unknown; created_at: unknown; updated_at: unknown };
export type TrustedKnowledgeProjectionRow = { source_item_id: unknown; source_item_kind: unknown; review_state: unknown; content: unknown; provenance: unknown; source_entry_ids: unknown; governance_revision: unknown };

function fail(code: TrustedKnowledgeProjectionError["code"], message: string, details?: Record<string, unknown>): never { throw new TrustedKnowledgeProjectionError(code, message, details); }
function parseId(value: unknown, kind: SourceKind): string { if (typeof value !== "string" || !value.trim()) return fail("trusted_knowledge_projection_invalid_source", "Trusted Knowledge source ID is invalid.", { kind, sourceItemId: value }); return value; }
function parseReviewState(value: unknown, kind: SourceKind, id: unknown): ReviewState { if (typeof value === "string" && (REVIEW_STATES as readonly string[]).includes(value)) return value as ReviewState; return fail("invalid_trusted_projection_source_state", "Trusted Knowledge source has an invalid review state.", { kind, sourceItemId: id, status: value }); }
function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function stringArray(value: unknown, field: string, kind: SourceKind, id: string): string[] { if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item.trim())) return fail("trusted_knowledge_projection_invalid_source", `Trusted Knowledge ${field} is invalid.`, { kind, sourceItemId: id, field }); return value; }
function iso(value: unknown, field: string, kind: SourceKind, id: string): string { if (value instanceof Date) return value.toISOString(); if (typeof value === "string" && value) return value; return fail("trusted_knowledge_projection_invalid_source", `Trusted Knowledge ${field} is invalid.`, { kind, sourceItemId: id, field }); }
function number(value: unknown, field: string, kind: SourceKind, id: string): number { const result = Number(value); if (!Number.isFinite(result)) return fail("trusted_knowledge_projection_invalid_source", `Trusted Knowledge ${field} is invalid.`, { kind, sourceItemId: id, field }); return result; }
function active(state: ReviewState): state is "approved" | "corrected" { return state === "approved" || state === "corrected"; }

async function loadCanonicalProjectionSources(client: QueryClient, projectId: string): Promise<{ contexts: ContextRow[]; faqs: FaqRow[] }> {
  const [contexts, faqs] = await Promise.all([client.query("SELECT id, category, title, content, confidence, confidence_score, status, source, metadata, created_at, updated_at FROM ai_builder_context_entries WHERE project_id = $1 ORDER BY id", [projectId]), client.query("SELECT id, question, answer, confidence, confidence_score, source_entry_ids, status, metadata, created_at, updated_at FROM ai_builder_faq_entries WHERE project_id = $1 ORDER BY id", [projectId])]);
  return { contexts: contexts.rows as ContextRow[], faqs: faqs.rows as FaqRow[] };
}

async function upsertContextProjectionRow(client: QueryClient, projectId: string, row: ContextRow, governanceRevision: number): Promise<string> {
  const id = parseId(row.id, "context_entry"); const state = parseReviewState(row.status, "context_entry", id);
  const metadata = object(row.metadata); const source = object(row.source);
  await client.query(`INSERT INTO ai_builder_trusted_knowledge_projection (project_id, source_item_id, source_item_kind, review_state, active, content, provenance, source_entry_ids, governance_revision, created_at, updated_at) VALUES ($1,$2,'context_entry',$3,$4,$5::jsonb,$6::jsonb,'[]'::jsonb,$7,$8::timestamptz,$9::timestamptz) ON CONFLICT (project_id, source_item_kind, source_item_id) DO UPDATE SET review_state=EXCLUDED.review_state,active=EXCLUDED.active,content=EXCLUDED.content,provenance=EXCLUDED.provenance,governance_revision=EXCLUDED.governance_revision,updated_at=EXCLUDED.updated_at`, [projectId, id, state, active(state), JSON.stringify({ category: row.category, title: row.title, content: row.content, confidence: row.confidence, confidenceScore: number(row.confidence_score, "confidenceScore", "context_entry", id), source, metadata }), JSON.stringify(metadata), governanceRevision, iso(row.created_at, "createdAt", "context_entry", id), iso(row.updated_at, "updatedAt", "context_entry", id)]);
  return `context_entry:${id}`;
}

async function upsertFaqProjectionRow(client: QueryClient, projectId: string, row: FaqRow, governanceRevision: number): Promise<string> {
  const id = parseId(row.id, "faq"); const state = parseReviewState(row.status, "faq", id); const sourceEntryIds = stringArray(row.source_entry_ids, "sourceEntryIds", "faq", id); const metadata = object(row.metadata);
  await client.query(`INSERT INTO ai_builder_trusted_knowledge_projection (project_id, source_item_id, source_item_kind, review_state, active, content, provenance, source_entry_ids, governance_revision, created_at, updated_at) VALUES ($1,$2,'faq',$3,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8,$9::timestamptz,$10::timestamptz) ON CONFLICT (project_id, source_item_kind, source_item_id) DO UPDATE SET review_state=EXCLUDED.review_state,active=EXCLUDED.active,content=EXCLUDED.content,provenance=EXCLUDED.provenance,source_entry_ids=EXCLUDED.source_entry_ids,governance_revision=EXCLUDED.governance_revision,updated_at=EXCLUDED.updated_at`, [projectId, id, state, active(state), JSON.stringify({ question: row.question, answer: row.answer, confidence: row.confidence, confidenceScore: number(row.confidence_score, "confidenceScore", "faq", id), metadata }), JSON.stringify(metadata), JSON.stringify(sourceEntryIds), governanceRevision, iso(row.created_at, "createdAt", "faq", id), iso(row.updated_at, "updatedAt", "faq", id)]);
  return `faq:${id}`;
}

async function deactivateMissingProjectionRows(client: QueryClient, projectId: string, sourceKeys: string[], governanceRevision: number): Promise<void> { if (sourceKeys.length) await client.query("UPDATE ai_builder_trusted_knowledge_projection SET active=FALSE, governance_revision=$2, updated_at=NOW() WHERE project_id=$1 AND (source_item_kind || ':' || source_item_id) <> ALL($3::text[])", [projectId, governanceRevision, sourceKeys]); else await client.query("UPDATE ai_builder_trusted_knowledge_projection SET active=FALSE, governance_revision=$2, updated_at=NOW() WHERE project_id=$1", [projectId, governanceRevision]); }
async function updateProjectionRevision(client: QueryClient, projectId: string, governanceRevision: number): Promise<void> { await client.query("UPDATE ai_builder_projects SET trusted_knowledge_revision=$2 WHERE id=$1", [projectId, governanceRevision]); }

/** Reconciles derived Trusted Knowledge without mutating canonical review authority. Caller owns the transaction. */
export async function reconcileTrustedKnowledgeProjectionForProject(client: QueryClient, projectId: string, governanceRevision: number): Promise<void> {
  try { const sources = await loadCanonicalProjectionSources(client, projectId); for (const row of sources.contexts) { const id = parseId(row.id, "context_entry"); parseReviewState(row.status, "context_entry", id); number(row.confidence_score, "confidenceScore", "context_entry", id); iso(row.created_at, "createdAt", "context_entry", id); iso(row.updated_at, "updatedAt", "context_entry", id); } for (const row of sources.faqs) { const id = parseId(row.id, "faq"); parseReviewState(row.status, "faq", id); stringArray(row.source_entry_ids, "sourceEntryIds", "faq", id); number(row.confidence_score, "confidenceScore", "faq", id); iso(row.created_at, "createdAt", "faq", id); iso(row.updated_at, "updatedAt", "faq", id); } const keys = [...await Promise.all(sources.contexts.map((row) => upsertContextProjectionRow(client, projectId, row, governanceRevision))), ...await Promise.all(sources.faqs.map((row) => upsertFaqProjectionRow(client, projectId, row, governanceRevision)))]; await deactivateMissingProjectionRows(client, projectId, keys, governanceRevision); await updateProjectionRevision(client, projectId, governanceRevision); }
  catch (error) { if (error instanceof TrustedKnowledgeProjectionError) throw error; throw new TrustedKnowledgeProjectionError("trusted_knowledge_projection_reconciliation_failed", "Trusted Knowledge reconciliation failed.", { projectId }); }
}
export const rebuildTrustedKnowledgeProjection = reconcileTrustedKnowledgeProjectionForProject;

function nullableClassification(value: unknown): AiBuilderProvenanceClassification | null { return typeof value === "string" ? value as AiBuilderProvenanceClassification : null; }
function nullableString(value: unknown): string | null { return typeof value === "string" && value ? value : null; }
function provenance(value: unknown): KnowledgeProvenance { const metadata = object(value); const correction = object(metadata.correction); const actor = object(correction.actor); return { classification: nullableClassification(metadata.provenanceClassification), predecessorClassification: nullableClassification(metadata.predecessorProvenanceClassification), originalClassification: nullableClassification(metadata.originalProvenanceClassification), correctedByClerkUserId: nullableString(actor.clerkUserId), correctedByDisplayName: nullableString(actor.displayName), correctedByEmail: nullableString(actor.email), correctedAt: nullableString(correction.correctedAt) }; }
function runtimeState(value: unknown): "approved" | "corrected" { const state = parseReviewState(value, "context_entry", "runtime"); if (!active(state)) return fail("trusted_knowledge_projection_invalid_source", "Inactive Trusted Knowledge was supplied to runtime mapping.", { reviewState: state }); return state; }

/** Maps active persisted Trusted Knowledge to the existing retrieval contract; provenance remains citation/diagnostic metadata only. */
export function buildKnowledgePackFromTrustedRows(input: { projectId: string; assistantConfiguration: { name: string; purpose: string; tone: string; primaryAudience: string | null }; rows: TrustedKnowledgeProjectionRow[] }): KnowledgePack {
  const facts: KnowledgeFact[] = []; const faq: KnowledgeFaq[] = []; const behaviorRules: KnowledgeFact[] = []; const prohibitedClaims: KnowledgeFact[] = [];
  for (const row of input.rows) { const kind = row.source_item_kind; const id = parseId(row.source_item_id, kind === "faq" ? "faq" : "context_entry"); const state = runtimeState(row.review_state); const content = object(row.content); const runtimeProvenance = provenance(row.provenance); const revision = number(row.governance_revision, "governanceRevision", kind === "faq" ? "faq" : "context_entry", id); if (kind === "faq") { faq.push({ id: `knowledge_${id}`, question: String(content.question ?? ""), answer: String(content.answer ?? ""), confidence: content.confidence as KnowledgeFaq["confidence"], confidenceScore: Number(content.confidenceScore), sourceEntryIds: stringArray(row.source_entry_ids, "sourceEntryIds", "faq", id), provenance: runtimeProvenance, reviewState: state, governanceRevision: revision }); continue; } if (kind !== "context_entry") fail("trusted_knowledge_projection_invalid_source", "Trusted Knowledge source kind is invalid.", { sourceItemKind: kind, sourceItemId: id }); const source = object(content.source) as ContextSource; const metadata = object(content.metadata); const fact: KnowledgeFact = { id: `knowledge_${id}`, category: content.category as KnowledgeFact["category"], title: String(content.title ?? ""), content: String(content.content ?? ""), confidence: content.confidence as KnowledgeFact["confidence"], confidenceScore: Number(content.confidenceScore), sourceEntryId: id, sourceExcerpt: String(source.excerpt ?? ""), sourceType: String(source.sourceType ?? ""), sourceUrl: typeof source.sourceUrl === "string" ? source.sourceUrl : null, tags: Array.isArray(metadata.tags) ? metadata.tags.filter((tag): tag is string => typeof tag === "string") : [], provenance: runtimeProvenance, reviewState: state, governanceRevision: revision }; if (fact.category === "behavior_rule") behaviorRules.push(fact); else if (fact.category === "prohibited_claim") prohibitedClaims.push(fact); else facts.push(fact); }
  const sort = <T extends { id: string }>(items: T[]) => items.sort((a, b) => a.id.localeCompare(b.id)); return { sessionId: input.projectId, assistantName: input.assistantConfiguration.name || "Business AI Assistant", assistantPurpose: input.assistantConfiguration.purpose || "Answer questions using approved business knowledge.", assistantTone: input.assistantConfiguration.tone || "Professional and helpful", primaryAudience: input.assistantConfiguration.primaryAudience, facts: sort(facts), faq: sort(faq), behaviorRules: sort(behaviorRules), prohibitedClaims: sort(prohibitedClaims), builtAt: new Date().toISOString(), version: 1 };
}
