import { createNoteAction, deleteNoteAction, saveProjectAction, updateNoteAction } from "../../actions";
import DeleteNoteButton from "../../_components/DeleteNoteButton";
import { Badge, card, formatDateTime } from "../../_components/AdminUi";

type Row=Record<string,unknown>;
const v=(r:Row,k:string)=>String(r[k]??"");
const date=(x:unknown)=>x?formatDateTime(new Date(String(x)).toISOString()):"Unavailable";
const input="w-full rounded-xl border border-amber-300/15 bg-[#020611] px-3 py-2.5 text-sm text-white outline-none transition focus:border-amber-300/50 focus:ring-4 focus:ring-amber-300/[.05]";
const label="space-y-1 text-xs font-bold text-slate-400";
const button="cta-raised rounded-xl border border-amber-300/20 bg-[#101936] px-4 py-2.5 text-sm font-black text-white hover:border-amber-300/40";

function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className={`${card} overflow-hidden`}><div className="border-b border-amber-300/10 px-6 py-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-amber-300/55">Operations</p><h2 className="mt-1 text-lg font-semibold text-white">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div><div className="p-5 sm:p-6">{children}</div></section>}

export function CustomerEditor({project}:{project:{id:string;businessName:string;ownerName:string|null;ownerEmail:string|null;website:string|null;internalStatus:string|null;internalFields:unknown}}){
  const fields=(project.internalFields&&typeof project.internalFields==="object"?project.internalFields:{}) as {summary?:string};
  return <Panel title="Customer & internal metadata" subtitle="Administrative changes update the existing project record."><form action={saveProjectAction} className="grid gap-4 lg:grid-cols-2"><input type="hidden" name="projectId" value={project.id}/><label className={label}>Business name<input required name="businessName" defaultValue={project.businessName} className={input}/></label><label className={label}>Owner name<input name="ownerName" defaultValue={project.ownerName||""} className={input}/></label><label className={label}>Email<input type="email" name="ownerEmail" defaultValue={project.ownerEmail||""} className={input}/></label><label className={label}>Website<input type="url" name="website" defaultValue={project.website||""} className={input}/></label><label className={label}>Internal status<input name="internalStatus" defaultValue={project.internalStatus||""} placeholder="e.g. priority account" className={input}/></label><label className={`${label} lg:col-span-2`}>Internal summary<textarea name="internalSummary" defaultValue={fields.summary||""} rows={4} className={input}/></label><div className="lg:col-span-2"><button className={button}>Save customer details</button></div></form></Panel>;
}

export function InternalNotes({projectId,notes}:{projectId:string;notes:Row[]}){return <Panel title="Internal notes" subtitle="Private to administrators; never returned by customer APIs."><form action={createNoteAction} className="flex flex-col gap-3 sm:flex-row"><input type="hidden" name="projectId" value={projectId}/><textarea required name="content" rows={2} placeholder="Add an internal note…" className={`${input} flex-1`}/><button className={button}>Add note</button></form><div className="mt-5 space-y-3">{notes.length?notes.map(n=><article key={v(n,"id")} className="rounded-xl border border-white/[.07] bg-[#030713] p-4"><form action={updateNoteAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="noteId" value={v(n,"id")}/><textarea required name="content" defaultValue={v(n,"content")} rows={3} className={input}/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">{v(n,"author_email")} · {date(n.created_at)}{String(n.updated_at)!==String(n.created_at)?" · edited":""}</p><div className="flex gap-2"><button className={button}>Save note</button><DeleteNoteButton noteId={v(n,"id")} projectId={projectId} action={deleteNoteAction}/></div></div></form></article>):<p className="py-5 text-center text-sm text-slate-500">No internal notes yet.</p>}</div></Panel>}

export function Diagnostics({crawlAttempts,generationAttempts}:{crawlAttempts:Row[];generationAttempts:Row[]}){
  const crawl=crawlAttempts[0],generation=generationAttempts[0];
  const count=(x:unknown)=>Array.isArray(x)?x.length:"Not recorded"; const shown=(x:unknown,fallback="Not recorded")=>x===null||x===undefined||x===""?fallback:String(x);
  const Metric=({name,value}:{name:string;value:string|number})=><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><dt className="text-xs text-slate-500">{name}</dt><dd className="mt-1 text-sm font-bold text-white">{value}</dd></div>;
  const History=({title,rows}:{title:string;rows:Row[]})=><details className="mt-4 rounded-xl border border-white/[.07] bg-[#030713] p-4"><summary className="cursor-pointer text-sm font-bold text-white">{title} ({rows.length})</summary><div className="mt-3 space-y-2">{rows.map(r=><div key={v(r,"id")} className="grid gap-2 border-t border-white/[.05] pt-3 text-xs text-slate-400 sm:grid-cols-4"><span>Attempt {v(r,"attempt_number")}</span><span className="capitalize">{v(r,"status")}</span><span>{date(r.started_at)}</span><span>{r.duration_ms==null?"Duration not recorded":`${r.duration_ms} ms`}</span></div>)}</div></details>;
  const successful=crawlAttempts.find(r=>["completed","partial"].includes(v(r,"status")));
  return <div className="grid gap-6 xl:grid-cols-2"><Panel title="Website crawl diagnostics" subtitle="Persisted crawler telemetry">{crawl?<><dl className="grid gap-3 sm:grid-cols-2"><Metric name="Status" value={shown(crawl.status)}/><Metric name="Start time" value={date(crawl.started_at)}/><Metric name="Completion time" value={date(crawl.completed_at)}/><Metric name="Actual duration" value={crawl.duration_ms==null?"Not recorded":`${crawl.duration_ms} ms`}/><Metric name="Pages discovered" value={shown(crawl.pages_discovered)}/><Metric name="Pages processed" value={shown(crawl.pages_processed)}/><Metric name="Pages skipped" value={shown(crawl.pages_skipped)}/><Metric name="Pages failed" value={shown(crawl.pages_failed)}/><Metric name="Warning count" value={count(crawl.warnings)}/><Metric name="Error count" value={count(crawl.errors)}/><Metric name="Last successful crawl" value={successful?date(successful.completed_at):"No successful crawl"}/></dl><History title="Crawl attempt history" rows={crawlAttempts}/></>:<p className="py-8 text-center text-sm text-slate-500">No crawl attempt. Detailed telemetry was not recorded for historical projects.</p>}</Panel><Panel title="AI generation diagnostics" subtitle="Persisted provider and generation telemetry">{generation?<><dl className="grid gap-3 sm:grid-cols-2"><Metric name="Status" value={shown(generation.status)}/><Metric name="Start time" value={date(generation.started_at)}/><Metric name="Completion time" value={date(generation.completed_at)}/><Metric name="Actual generation duration" value={generation.duration_ms==null?"Not recorded":`${generation.duration_ms} ms`}/><Metric name="Model" value={shown(generation.model)}/><Metric name="Knowledge generated" value={shown(generation.knowledge_count)}/><Metric name="Generated Q&A" value={shown(generation.faq_count)}/><Metric name="Retry count" value={generation.retry_count==null?"Not recorded":String(generation.retry_count)}/><Metric name="Token usage" value={generation.total_tokens==null?"Provider did not return usage":`${generation.total_tokens} total (${shown(generation.input_tokens)} in / ${shown(generation.output_tokens)} out)`}/><Metric name="Cost" value={generation.cost_micros==null?"Not recorded":`$${(Number(generation.cost_micros)/1_000_000).toFixed(6)}`}/><Metric name="Warning count" value={count(generation.warnings)}/><Metric name="Error count" value={count(generation.errors)}/></dl><History title="Generation attempt history" rows={generationAttempts}/></>:<p className="py-8 text-center text-sm text-slate-500">No generation attempt. Detailed telemetry was not recorded for historical projects.</p>}</Panel></div>;
}

export function Communications({rows}:{rows:Row[]}){return <Panel title="Communication history" subtitle="Prepared for future Resend event ingestion">{rows.length?<div className="space-y-3">{rows.map(r=><div key={v(r,"id")} className="grid gap-2 rounded-xl border border-white/[.07] p-4 sm:grid-cols-4"><p className="text-sm font-bold text-white">{v(r,"email_type")}</p><p className="text-sm text-slate-400">{v(r,"recipient_email")||"No recipient"}</p><Badge>{v(r,"delivery_status")}</Badge><time className="text-xs text-slate-500">{date(r.sent_at)}</time></div>)}</div>:<div className="py-8 text-center"><p className="font-bold text-white">No emails recorded</p><p className="mt-2 text-sm text-slate-500">Communication events will appear here after Resend is connected.</p></div>}</Panel>}

export function ImpersonationPanel({customer,reason}:{customer:string;reason:string}){return <Panel title="Customer impersonation" subtitle="Uses verified Clerk server-side session capabilities only"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-white">Customer: {customer}</p><p className="mt-1 text-xs text-slate-500">{reason}</p></div><button disabled className={`${button} cursor-not-allowed opacity-45`}>Impersonate customer</button></div></Panel>}
