import { createNoteAction, deleteNoteAction, saveProjectAction, updateNoteAction } from "../../actions";
import DeleteNoteButton from "../../_components/DeleteNoteButton";
import { Badge, card, formatDateTime } from "../../_components/AdminUi";

type Row=Record<string,unknown>;
const v=(r:Row,k:string)=>String(r[k]??"");
const date=(x:unknown)=>x?formatDateTime(new Date(String(x)).toISOString()):"Unavailable";
const input="w-full rounded-xl border border-white/10 bg-[#020611] px-3 py-2.5 text-sm text-white outline-none focus:border-amber-300/40";
const label="space-y-1 text-xs font-bold text-slate-400";
const button="cta-raised rounded-xl border border-amber-300/20 bg-[#101936] px-4 py-2.5 text-sm font-black text-white hover:border-amber-300/40";

function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className={`${card} overflow-hidden`}><div className="border-b border-white/[.06] px-5 py-4"><h2 className="font-black text-white">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div><div className="p-5">{children}</div></section>}

export function CustomerEditor({project}:{project:{id:string;businessName:string;ownerName:string|null;ownerEmail:string|null;website:string|null;internalStatus:string|null;internalFields:unknown}}){
  const fields=(project.internalFields&&typeof project.internalFields==="object"?project.internalFields:{}) as {summary?:string};
  return <Panel title="Customer & internal metadata" subtitle="Administrative changes update the existing project record."><form action={saveProjectAction} className="grid gap-4 lg:grid-cols-2"><input type="hidden" name="projectId" value={project.id}/><label className={label}>Business name<input required name="businessName" defaultValue={project.businessName} className={input}/></label><label className={label}>Owner name<input name="ownerName" defaultValue={project.ownerName||""} className={input}/></label><label className={label}>Email<input type="email" name="ownerEmail" defaultValue={project.ownerEmail||""} className={input}/></label><label className={label}>Website<input type="url" name="website" defaultValue={project.website||""} className={input}/></label><label className={label}>Internal status<input name="internalStatus" defaultValue={project.internalStatus||""} placeholder="e.g. priority account" className={input}/></label><label className={`${label} lg:col-span-2`}>Internal summary<textarea name="internalSummary" defaultValue={fields.summary||""} rows={4} className={input}/></label><div className="lg:col-span-2"><button className={button}>Save customer details</button></div></form></Panel>;
}

export function InternalNotes({projectId,notes}:{projectId:string;notes:Row[]}){return <Panel title="Internal notes" subtitle="Private to administrators; never returned by customer APIs."><form action={createNoteAction} className="flex flex-col gap-3 sm:flex-row"><input type="hidden" name="projectId" value={projectId}/><textarea required name="content" rows={2} placeholder="Add an internal note…" className={`${input} flex-1`}/><button className={button}>Add note</button></form><div className="mt-5 space-y-3">{notes.length?notes.map(n=><article key={v(n,"id")} className="rounded-xl border border-white/[.07] bg-[#030713] p-4"><form action={updateNoteAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="noteId" value={v(n,"id")}/><textarea required name="content" defaultValue={v(n,"content")} rows={3} className={input}/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">{v(n,"author_email")} · {date(n.created_at)}{String(n.updated_at)!==String(n.created_at)?" · edited":""}</p><div className="flex gap-2"><button className={button}>Save note</button><DeleteNoteButton noteId={v(n,"id")} projectId={projectId} action={deleteNoteAction}/></div></div></form></article>):<p className="py-5 text-center text-sm text-slate-500">No internal notes yet.</p>}</div></Panel>}

export function Diagnostics({project,progress,intake,knowledgeCount,faqCount}:{project:{status:string;createdAt:string;updatedAt:string;website:string|null};progress:Row[];intake:Row[];knowledgeCount:number;faqCount:number}){
  const times=progress.map(r=>new Date(String(r.created_at)).getTime()).filter(Number.isFinite),start=times.length?new Date(Math.min(...times)).toISOString():null,end=times.length?new Date(Math.max(...times)).toISOString():null;
  const imported=intake.find(r=>v(r,"label").startsWith("WEBSITE KNOWLEDGE: Public")); const importedAt=v(imported||{},"content").match(/Imported at:\s*(.+)/)?.[1];
  const duration=start&&end?Math.max(0,new Date(end).getTime()-new Date(start).getTime()):null;
  const Metric=({name,value}:{name:string;value:string|number})=><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><dt className="text-xs text-slate-500">{name}</dt><dd className="mt-1 text-sm font-bold text-white">{value}</dd></div>;
  return <div className="grid gap-6 xl:grid-cols-2"><Panel title="Website crawl diagnostics" subtitle="Available persisted import information"><dl className="grid gap-3 sm:grid-cols-2"><Metric name="Crawl start" value={importedAt?date(importedAt):"Unavailable"}/><Metric name="Crawl finish" value={importedAt?date(importedAt):"Unavailable"}/><Metric name="Pages discovered" value="Not persisted"/><Metric name="Pages processed" value="Not persisted"/><Metric name="Warnings" value="Not persisted"/><Metric name="Errors" value={project.website?"None recorded":"No crawl recorded"}/><Metric name="Last crawl" value={importedAt?date(importedAt):"Unavailable"}/></dl></Panel><Panel title="AI generation diagnostics" subtitle="Derived from existing workflow events"><dl className="grid gap-3 sm:grid-cols-2"><Metric name="Generation started" value={start?date(start):"Unavailable"}/><Metric name="Generation completed" value={project.status==="ready"?date(project.updatedAt):end?date(end):"Incomplete"}/><Metric name="Recorded workflow duration" value={duration===null?"Unavailable":`${duration} ms`}/><Metric name="Knowledge generated" value={knowledgeCount}/><Metric name="Generated Q&A" value={faqCount}/><Metric name="Warnings" value={progress.filter(r=>/warn/i.test(v(r,"message"))).length}/><Metric name="Errors" value={project.status==="failed"?"Generation failed":"None recorded"}/></dl></Panel></div>;
}

export function Communications({rows}:{rows:Row[]}){return <Panel title="Communication history" subtitle="Prepared for future Resend event ingestion">{rows.length?<div className="space-y-3">{rows.map(r=><div key={v(r,"id")} className="grid gap-2 rounded-xl border border-white/[.07] p-4 sm:grid-cols-4"><p className="text-sm font-bold text-white">{v(r,"email_type")}</p><p className="text-sm text-slate-400">{v(r,"recipient_email")||"No recipient"}</p><Badge>{v(r,"delivery_status")}</Badge><time className="text-xs text-slate-500">{date(r.sent_at)}</time></div>)}</div>:<div className="py-8 text-center"><p className="font-bold text-white">No emails recorded</p><p className="mt-2 text-sm text-slate-500">Communication events will appear here after Resend is connected.</p></div>}</Panel>}

export function ImpersonationPanel({customer,reason}:{customer:string;reason:string}){return <Panel title="Customer impersonation" subtitle="Uses verified Clerk server-side session capabilities only"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-white">Customer: {customer}</p><p className="mt-1 text-xs text-slate-500">{reason}</p></div><button disabled className={`${button} cursor-not-allowed opacity-45`}>Impersonate customer</button></div></Panel>}
