import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "@neondatabase/serverless";
import { ensureAiBuilderSchema } from "@/app/lib/db/ai-builder-schema";
import { rebuildPersistedBusinessMemoryFromTrustedKnowledge } from "@/app/lib/ai-engine/business-memory/persistence/rebuild-persisted-business-memory";
import { ASSISTANT_PROJECTION_SCHEMA_VERSION, ASSISTANT_PROJECTION_VERSION } from "@/app/lib/ai-engine/assistant-projection/contracts";
import { getPersistedAssistantProjection, loadPersistedBusinessMemory } from "@/app/lib/ai-engine/assistant-projection/persistence";
import { rebuildAssistantProjectionInTransaction } from "@/app/lib/ai-engine/assistant-projection/lifecycle";
import { buildAssistantProjection } from "@/app/lib/ai-engine/assistant-projection/buildAssistantProjection";
import { classifySynchronizationFailure, type SynchronizationFailureClass } from "./failure-classification";
import { MAX_SYNCHRONIZATION_ATTEMPTS, retryDelaySeconds, shouldRetryFailure } from "./retry-policy";

type Mode = "incremental" | "full_rebuild";
type Status = "pending" | "running" | "retry_scheduled" | "succeeded" | "failed" | "dead_letter";
type Trigger = "initial" | "automatic_retry" | "manual_retry" | "stale_running_recovery" | "deterministic_repair";
export type DownstreamSynchronizationJob = { id:string; projectId:string; mode:Mode; status:Status; requestedTrustedKnowledgeRevision:number; requestedBusinessMemoryRevision:number|null; completedTrustedKnowledgeRevision:number|null; completedBusinessMemoryRevision:number|null; completedAssistantProjectionFingerprint:string|null; currentStep:string; createdAt:string; startedAt:string|null; completedAt:string|null; updatedAt:string; lastErrorCode:string|null; lastErrorMessage:string|null; attemptCount:number; maxAttempts:number; nextAttemptAt:string|null; lastAttemptAt:string|null; lastFailureClass:SynchronizationFailureClass|null; deadLetteredAt:string|null; recoveryRevision:number; claimExpiresAt:string|null };
export type SynchronizationAttempt = { id:string; jobId:string; projectId:string; attemptNumber:number; triggerType:Trigger; startingStatus:string; startingStep:string; executionStage:string; workStarted:boolean; executionToken:string|null; result:string|null; failureClass:SynchronizationFailureClass|null; errorCode:string|null; errorMessage:string|null; startedAt:string; finishedAt:string|null; completedTrustedKnowledgeRevision:number|null; completedBusinessMemoryRevision:number|null; completedAssistantProjectionFingerprint:string|null; actorType:string; actorId:string|null; recoveryCommandId:string|null; reason:string|null };
let pool: Pool | null = null; const database=()=>pool??=new Pool({connectionString:process.env.DATABASE_URL});
const jobId=(p:string,m:Mode,r:number)=>`downstream_sync:${createHash("sha256").update(`${p}\0${m}\0${r}`).digest("hex")}`;
const safeText=(e:unknown)=>(e instanceof Error?e.message:"downstream synchronization failed").replace(/\0/g,"").split(/\r?\n/)[0]!.slice(0,500)||"downstream synchronization failed";
const errorCode=(e:unknown)=>{const v=e instanceof Error?e.message:"";return /^[a-zA-Z0-9_:-]{1,120}$/.test(v)?v:"downstream_synchronization_failed";};
const iso=(v:unknown)=>v==null?null:new Date(v as string).toISOString();
const parse=(r:Record<string,unknown>):DownstreamSynchronizationJob=>({id:String(r.id),projectId:String(r.project_id),mode:r.mode as Mode,status:r.status as Status,requestedTrustedKnowledgeRevision:Number(r.requested_trusted_knowledge_revision),requestedBusinessMemoryRevision:r.requested_business_memory_revision==null?null:Number(r.requested_business_memory_revision),completedTrustedKnowledgeRevision:r.completed_trusted_knowledge_revision==null?null:Number(r.completed_trusted_knowledge_revision),completedBusinessMemoryRevision:r.completed_business_memory_revision==null?null:Number(r.completed_business_memory_revision),completedAssistantProjectionFingerprint:r.completed_assistant_projection_fingerprint==null?null:String(r.completed_assistant_projection_fingerprint),currentStep:String(r.current_step),createdAt:iso(r.created_at)!,startedAt:iso(r.started_at),completedAt:iso(r.completed_at),updatedAt:iso(r.updated_at)!,lastErrorCode:r.last_error_code==null?null:String(r.last_error_code),lastErrorMessage:r.last_error_message==null?null:String(r.last_error_message),attemptCount:Number(r.attempt_count??0),maxAttempts:Number(r.max_attempts??MAX_SYNCHRONIZATION_ATTEMPTS),nextAttemptAt:iso(r.next_attempt_at),lastAttemptAt:iso(r.last_attempt_at),lastFailureClass:r.last_failure_class as SynchronizationFailureClass|null,deadLetteredAt:iso(r.dead_lettered_at),recoveryRevision:Number(r.recovery_revision??0),claimExpiresAt:iso(r.claim_expires_at)});

export async function enqueueIncrementalSynchronizationForCommittedRevision(client:Pick<PoolClient,"query">,projectId:string,revision:number){const result=await client.query(`INSERT INTO ai_builder_downstream_synchronization_jobs (id,project_id,mode,status,requested_trusted_knowledge_revision,current_step) VALUES ($1,$2,'incremental','pending',$3,'pending') ON CONFLICT (project_id,mode,requested_trusted_knowledge_revision) DO UPDATE SET updated_at=NOW() RETURNING *`,[jobId(projectId,"incremental",revision),projectId,revision]);return parse(result.rows[0]);}
export async function enqueueIncrementalSynchronizationForProject(projectId:string){await ensureAiBuilderSchema();const c=await database().connect();try{await c.query("BEGIN");const p=(await c.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1 FOR UPDATE",[projectId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found");const j=await enqueueIncrementalSynchronizationForCommittedRevision(c,projectId,Number(p.trusted_knowledge_revision));await c.query("COMMIT");return j;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
export async function enqueueFullDownstreamRebuildForOwnedProject(input:{projectId:string;clerkUserId:string;commandId:string}){await ensureAiBuilderSchema();const c=await database().connect();try{await c.query("BEGIN");const p=(await c.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1 AND clerk_user_id=$2 AND archived_at IS NULL FOR UPDATE",[input.projectId,input.clerkUserId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found_or_archived");const r=Number(p.trusted_knowledge_revision),result=await c.query(`INSERT INTO ai_builder_downstream_synchronization_jobs (id,project_id,mode,status,requested_trusted_knowledge_revision,current_step) VALUES ($1,$2,'full_rebuild','pending',$3,'pending') ON CONFLICT (project_id,mode,requested_trusted_knowledge_revision) DO UPDATE SET updated_at=NOW() RETURNING *`,[jobId(input.projectId,"full_rebuild",r),input.projectId,r]);await c.query("COMMIT");return parse(result.rows[0]);}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
export async function getDownstreamSynchronizationJob(id:string){await ensureAiBuilderSchema();const r=(await database().query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE id=$1",[id])).rows[0];return r?parse(r):null;}
export async function getDownstreamSynchronizationAttempts(id:string):Promise<SynchronizationAttempt[]>{await ensureAiBuilderSchema();return (await database().query("SELECT * FROM ai_builder_downstream_synchronization_attempts WHERE job_id=$1 ORDER BY attempt_number,id",[id])).rows.map((r:Record<string,unknown>)=>({id:String(r.id),jobId:String(r.job_id),projectId:String(r.project_id),attemptNumber:Number(r.attempt_number),triggerType:r.trigger_type as Trigger,startingStatus:String(r.starting_status),startingStep:String(r.starting_step),executionStage:String(r.execution_stage??"claimed"),workStarted:Boolean(r.work_started),executionToken:r.execution_token==null?null:String(r.execution_token),result:r.result==null?null:String(r.result),failureClass:r.failure_class as SynchronizationFailureClass|null,errorCode:r.error_code==null?null:String(r.error_code),errorMessage:r.error_message==null?null:String(r.error_message),startedAt:iso(r.started_at)!,finishedAt:iso(r.finished_at),completedTrustedKnowledgeRevision:r.completed_trusted_knowledge_revision==null?null:Number(r.completed_trusted_knowledge_revision),completedBusinessMemoryRevision:r.completed_business_memory_revision==null?null:Number(r.completed_business_memory_revision),completedAssistantProjectionFingerprint:r.completed_assistant_projection_fingerprint==null?null:String(r.completed_assistant_projection_fingerprint),actorType:String(r.actor_type),actorId:r.actor_id==null?null:String(r.actor_id),recoveryCommandId:r.recovery_command_id==null?null:String(r.recovery_command_id),reason:r.reason==null?null:String(r.reason)}));}

async function stage(attempt:string, executionStage:string, workStarted=false){await database().query("UPDATE ai_builder_downstream_synchronization_attempts SET execution_stage=$2,work_started=work_started OR $3 WHERE id=$1",[attempt,executionStage,workStarted]);}
export async function verifyPersistedDownstreamState(client:Pick<PoolClient,"query">, j:DownstreamSynchronizationJob){
 const row=(await client.query("SELECT p.business_memory_revision,m.revision,m.trusted_knowledge_revision FROM ai_builder_projects p LEFT JOIN ai_builder_business_memory m ON m.project_id=p.id WHERE p.id=$1",[j.projectId])).rows[0];
 const memory=await loadPersistedBusinessMemory(client as PoolClient,j.projectId); const projection=await getPersistedAssistantProjection(client as PoolClient,j.projectId);
 const memoryValid=!!row&&!!memory&&row.revision!=null&&Number(row.trusted_knowledge_revision)>=j.requestedTrustedKnowledgeRevision&&Number(row.business_memory_revision)===Number(row.revision);
 const expected=memory?buildAssistantProjection(memory).businessMemoryFingerprint:null;
 const projectionValid=memoryValid&&!!projection&&projection.businessMemoryFingerprint===expected&&projection.projectionVersion===ASSISTANT_PROJECTION_VERSION&&projection.schemaVersion===ASSISTANT_PROJECTION_SCHEMA_VERSION&&projection.invalidationState==="valid";
 return {memoryValid,projectionValid,memoryRevision:memoryValid?Number(row.revision):null,fingerprint:projectionValid?projection!.businessMemoryFingerprint:null};
}
async function checkpointMemory(j:DownstreamSynchronizationJob,r:number){await database().query("UPDATE ai_builder_downstream_synchronization_jobs SET requested_business_memory_revision=$2,completed_trusted_knowledge_revision=$3,completed_business_memory_revision=$2,current_step='assistant_projection',updated_at=NOW() WHERE id=$1",[j.id,r,j.requestedTrustedKnowledgeRevision]);}
async function checkpointProjection(j:DownstreamSynchronizationJob,f:string){await database().query("UPDATE ai_builder_downstream_synchronization_jobs SET completed_assistant_projection_fingerprint=$2,current_step='completed',updated_at=NOW() WHERE id=$1",[j.id,f]);}
export type ExecutionClaim={job:DownstreamSynchronizationJob;attemptId:string;token:string};
export async function claimDownstreamSynchronizationJob(id:string, options:{trigger?:Trigger;actorType?:string;actorId?:string;commandId?:string;reason?:string}={}, client?:PoolClient):Promise<ExecutionClaim>{
 const c=client??await database().connect();try{if(!client)await c.query("BEGIN");const row=(await c.query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!row)throw new Error("downstream_synchronization_job_not_found");const j=parse(row);if(j.status==="succeeded")throw new Error("downstream_synchronization_invalid_state");if(j.status==="dead_letter"||j.status==="running")throw new Error("downstream_synchronization_invalid_state");const p=(await c.query("SELECT id FROM ai_builder_projects WHERE id=$1 FOR UPDATE",[j.projectId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found");const token=randomUUID(),attemptId=randomUUID();await c.query("UPDATE ai_builder_downstream_synchronization_jobs SET status='running',attempt_count=attempt_count+1,last_attempt_at=NOW(),started_at=COALESCE(started_at,NOW()),execution_token=$2,claim_expires_at=NOW()+INTERVAL '15 minutes',next_attempt_at=NULL,pending_trigger_type=NULL,pending_actor_type=NULL,pending_actor_id=NULL,pending_command_id=NULL,pending_reason=NULL,updated_at=NOW() WHERE id=$1",[id,token]);await c.query("INSERT INTO ai_builder_downstream_synchronization_attempts (id,job_id,project_id,attempt_number,trigger_type,starting_status,starting_step,execution_token,execution_stage,work_started,actor_type,actor_id,recovery_command_id,reason) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'claimed',false,$9,$10,$11,$12)",[attemptId,id,j.projectId,j.attemptCount+1,options.trigger??row.pending_trigger_type??"initial",j.status,j.currentStep,token,options.actorType??row.pending_actor_type??"system",options.actorId??row.pending_actor_id??null,options.commandId??row.pending_command_id??null,options.reason??row.pending_reason??null]);if(!client)await c.query("COMMIT");return {job:{...j,status:"running",attemptCount:j.attemptCount+1},attemptId,token};}catch(e){if(!client)await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{if(!client)c.release();}}
async function finishFailure(j:DownstreamSynchronizationJob,attempt:string,e:unknown){const c=await database().connect(),ec=errorCode(e),fc=classifySynchronizationFailure(ec);try{await c.query("BEGIN");const a=(await c.query("SELECT work_started FROM ai_builder_downstream_synchronization_attempts WHERE id=$1 FOR UPDATE",[attempt])).rows[0];const retry=shouldRetryFailure(fc,j.attemptCount,Boolean(a?.work_started));await c.query("UPDATE ai_builder_downstream_synchronization_attempts SET finished_at=NOW(),result='failed',failure_class=$2,error_code=$3,error_message=$4 WHERE id=$1",[attempt,fc,ec,safeText(e)]);const status=retry?"retry_scheduled":fc==="permanent"||j.attemptCount>=j.maxAttempts?"dead_letter":"failed";await c.query("UPDATE ai_builder_downstream_synchronization_jobs SET status=$2,last_error_code=$3,last_error_message=$4,last_failure_class=$5,next_attempt_at=CASE WHEN $2='retry_scheduled' THEN NOW()+($6::text||' seconds')::interval ELSE NULL END,dead_lettered_at=CASE WHEN $2='dead_letter' THEN NOW() ELSE dead_lettered_at END,execution_token=NULL,claim_expires_at=NULL,updated_at=NOW() WHERE id=$1",[j.id,status,ec,safeText(e),fc,retryDelaySeconds(j.attemptCount)]);await c.query("COMMIT");}catch(x){await c.query("ROLLBACK");throw x;}finally{c.release();}}
/** Executes either a freshly claimed job or an already durable canonical claim. */
export async function executeDownstreamSynchronizationJob(id:string, options:{trigger?:Trigger;actorType?:string;actorId?:string;commandId?:string;reason?:string;forceBusiness?:boolean;projectionOnly?:boolean;forceProjection?:boolean;claim?:ExecutionClaim}={}){await ensureAiBuilderSchema();const claim=options.claim??await claimDownstreamSynchronizationJob(id,options);const j=claim.job,attempt=claim.attemptId;try{if(!options.projectionOnly){await stage(attempt,"business_memory_started",true);const x=await database().connect();try{await x.query("BEGIN");const p=(await x.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1 FOR UPDATE",[j.projectId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found");if(Number(p.trusted_knowledge_revision)<j.requestedTrustedKnowledgeRevision)throw new Error("downstream_synchronization_trusted_knowledge_revision_not_ready");await rebuildPersistedBusinessMemoryFromTrustedKnowledge(x,j.projectId,Number(p.trusted_knowledge_revision),{forceReconstruction:options.forceBusiness||j.mode==="full_rebuild"});const v=await verifyPersistedDownstreamState(x,j);if(!v.memoryValid)throw new Error("business_memory_synchronization_verification_failed");await x.query("COMMIT");await checkpointMemory(j,v.memoryRevision!);await stage(attempt,"business_memory_verified",true);}catch(e){await x.query("ROLLBACK").catch(()=>undefined);throw e;}finally{x.release();}}else {const x=await database().connect();try{const v=await verifyPersistedDownstreamState(x,j);if(!v.memoryValid)throw new Error("downstream_synchronization_projection_only_business_memory_invalid");await checkpointMemory(j,v.memoryRevision!);}finally{x.release();}}
await stage(attempt,"projection_started",true);const x=await database().connect();let v;try{await x.query("BEGIN");await rebuildAssistantProjectionInTransaction({client:x,projectId:j.projectId,forceRebuild:Boolean(options.forceProjection)||j.mode==="full_rebuild"});v=await verifyPersistedDownstreamState(x,j);if(!v.projectionValid)throw new Error("assistant_projection_synchronization_verification_failed");await x.query("COMMIT");}catch(e){await x.query("ROLLBACK").catch(()=>undefined);throw e;}finally{x.release();}await checkpointProjection(j,v!.fingerprint!);await stage(attempt,"projection_verified",true);const final=await database().connect();try{await final.query("BEGIN");await final.query("UPDATE ai_builder_downstream_synchronization_attempts SET finished_at=NOW(),result='succeeded',execution_stage='completed',completed_trusted_knowledge_revision=$2,completed_business_memory_revision=(SELECT completed_business_memory_revision FROM ai_builder_downstream_synchronization_jobs WHERE id=$1),completed_assistant_projection_fingerprint=$3 WHERE id=$4",[id,j.requestedTrustedKnowledgeRevision,v!.fingerprint,attempt]);await final.query("UPDATE ai_builder_downstream_synchronization_jobs SET status='succeeded',completed_at=NOW(),execution_token=NULL,claim_expires_at=NULL,last_error_code=NULL,last_error_message=NULL,last_failure_class=NULL,updated_at=NOW() WHERE id=$1",[id]);await final.query("COMMIT");}finally{final.release();}return (await getDownstreamSynchronizationJob(id))!;}catch(e){await finishFailure(j,attempt,e);throw e;}}
