import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "@neondatabase/serverless";
import { ensureAiBuilderSchema } from "@/app/lib/db/ai-builder-schema";
import { rebuildPersistedBusinessMemoryFromTrustedKnowledge } from "@/app/lib/ai-engine/business-memory/persistence/rebuild-persisted-business-memory";
import { ASSISTANT_PROJECTION_SCHEMA_VERSION, ASSISTANT_PROJECTION_VERSION } from "@/app/lib/ai-engine/assistant-projection/contracts";
import { getPersistedAssistantProjection, loadPersistedBusinessMemory } from "@/app/lib/ai-engine/assistant-projection/persistence";
import { rebuildAssistantProjectionInTransaction } from "@/app/lib/ai-engine/assistant-projection/lifecycle";
import { buildAssistantProjection } from "@/app/lib/ai-engine/assistant-projection/buildAssistantProjection";
import { classifySynchronizationFailure, type SynchronizationFailureClass } from "./failure-classification";
import { MAX_SYNCHRONIZATION_ATTEMPTS, retryDelaySeconds, shouldRetryFailure } from "./retry-policy";

type Mode = "incremental" | "full_rebuild";
type Status = "pending" | "running" | "retry_scheduled" | "succeeded" | "failed" | "dead_letter";
type Trigger = "initial" | "automatic_retry" | "manual_retry" | "stale_running_recovery" | "deterministic_repair";
export type DownstreamSynchronizationJob = { id:string; projectId:string; mode:Mode; status:Status; requestedTrustedKnowledgeRevision:number; requestedBusinessMemoryRevision:number|null; completedTrustedKnowledgeRevision:number|null; completedBusinessMemoryRevision:number|null; completedAssistantProjectionFingerprint:string|null; currentStep:string; createdAt:string; startedAt:string|null; completedAt:string|null; updatedAt:string; lastErrorCode:string|null; lastErrorMessage:string|null; attemptCount:number; maxAttempts:number; nextAttemptAt:string|null; lastAttemptAt:string|null; lastFailureClass:SynchronizationFailureClass|null; deadLetteredAt:string|null; recoveryRevision:number; claimExpiresAt:string|null };
export type SynchronizationAttempt = { id:string; jobId:string; attemptNumber:number; triggerType:Trigger; result:string|null; failureClass:SynchronizationFailureClass|null; errorCode:string|null; errorMessage:string|null; startedAt:string; finishedAt:string|null };
let pool: Pool | null = null; const database=()=>pool??=new Pool({connectionString:process.env.DATABASE_URL});
const jobId=(p:string,m:Mode,r:number)=>`downstream_sync:${createHash("sha256").update(`${p}\0${m}\0${r}`).digest("hex")}`;
const safeText=(e:unknown)=>(e instanceof Error?e.message:"downstream synchronization failed").replace(/\0/g,"").split(/\r?\n/)[0]!.slice(0,500)||"downstream synchronization failed";
const errorCode=(e:unknown)=>{const v=e instanceof Error?e.message:"";return /^[a-zA-Z0-9_:-]{1,120}$/.test(v)?v:"downstream_synchronization_failed";};
const iso=(v:unknown)=>v==null?null:new Date(v as string).toISOString();
const parse=(r:Record<string,unknown>):DownstreamSynchronizationJob=>({id:String(r.id),projectId:String(r.project_id),mode:r.mode as Mode,status:r.status as Status,requestedTrustedKnowledgeRevision:Number(r.requested_trusted_knowledge_revision),requestedBusinessMemoryRevision:r.requested_business_memory_revision==null?null:Number(r.requested_business_memory_revision),completedTrustedKnowledgeRevision:r.completed_trusted_knowledge_revision==null?null:Number(r.completed_trusted_knowledge_revision),completedBusinessMemoryRevision:r.completed_business_memory_revision==null?null:Number(r.completed_business_memory_revision),completedAssistantProjectionFingerprint:r.completed_assistant_projection_fingerprint==null?null:String(r.completed_assistant_projection_fingerprint),currentStep:String(r.current_step),createdAt:iso(r.created_at)!,startedAt:iso(r.started_at),completedAt:iso(r.completed_at),updatedAt:iso(r.updated_at)!,lastErrorCode:r.last_error_code==null?null:String(r.last_error_code),lastErrorMessage:r.last_error_message==null?null:String(r.last_error_message),attemptCount:Number(r.attempt_count??0),maxAttempts:Number(r.max_attempts??MAX_SYNCHRONIZATION_ATTEMPTS),nextAttemptAt:iso(r.next_attempt_at),lastAttemptAt:iso(r.last_attempt_at),lastFailureClass:r.last_failure_class as SynchronizationFailureClass|null,deadLetteredAt:iso(r.dead_lettered_at),recoveryRevision:Number(r.recovery_revision??0),claimExpiresAt:iso(r.claim_expires_at)});

export async function enqueueIncrementalSynchronizationForCommittedRevision(client:Pick<PoolClient,"query">,projectId:string,revision:number){const result=await client.query(`INSERT INTO ai_builder_downstream_synchronization_jobs (id,project_id,mode,status,requested_trusted_knowledge_revision,current_step) VALUES ($1,$2,'incremental','pending',$3,'pending') ON CONFLICT (project_id,mode,requested_trusted_knowledge_revision) DO UPDATE SET updated_at=NOW() RETURNING *`,[jobId(projectId,"incremental",revision),projectId,revision]);return parse(result.rows[0]);}
export async function enqueueIncrementalSynchronizationForProject(projectId:string){await ensureAiBuilderSchema();const c=await database().connect();try{await c.query("BEGIN");const p=(await c.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1 FOR UPDATE",[projectId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found");const j=await enqueueIncrementalSynchronizationForCommittedRevision(c,projectId,Number(p.trusted_knowledge_revision));await c.query("COMMIT");return j;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
export async function enqueueFullDownstreamRebuildForOwnedProject(input:{projectId:string;clerkUserId:string;commandId:string}){await ensureAiBuilderSchema();const c=await database().connect();try{await c.query("BEGIN");const p=(await c.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1 AND clerk_user_id=$2 AND archived_at IS NULL FOR UPDATE",[input.projectId,input.clerkUserId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found_or_archived");const r=Number(p.trusted_knowledge_revision),result=await c.query(`INSERT INTO ai_builder_downstream_synchronization_jobs (id,project_id,mode,status,requested_trusted_knowledge_revision,current_step) VALUES ($1,$2,'full_rebuild','pending',$3,'pending') ON CONFLICT (project_id,mode,requested_trusted_knowledge_revision) DO UPDATE SET updated_at=NOW() RETURNING *`,[jobId(input.projectId,"full_rebuild",r),input.projectId,r]);await c.query("COMMIT");return parse(result.rows[0]);}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
export async function getDownstreamSynchronizationJob(id:string){await ensureAiBuilderSchema();const r=(await database().query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE id=$1",[id])).rows[0];return r?parse(r):null;}
export async function getDownstreamSynchronizationAttempts(id:string):Promise<SynchronizationAttempt[]>{await ensureAiBuilderSchema();return (await database().query("SELECT * FROM ai_builder_downstream_synchronization_attempts WHERE job_id=$1 ORDER BY attempt_number,id",[id])).rows.map((r:Record<string,unknown>)=>({id:String(r.id),jobId:String(r.job_id),attemptNumber:Number(r.attempt_number),triggerType:r.trigger_type as Trigger,result:r.result==null?null:String(r.result),failureClass:r.failure_class as SynchronizationFailureClass|null,errorCode:r.error_code==null?null:String(r.error_code),errorMessage:r.error_message==null?null:String(r.error_message),startedAt:iso(r.started_at)!,finishedAt:iso(r.finished_at)}));}

async function checkpointMemory(j:DownstreamSynchronizationJob,r:number){await database().query("UPDATE ai_builder_downstream_synchronization_jobs SET requested_business_memory_revision=$2,completed_trusted_knowledge_revision=$3,completed_business_memory_revision=$2,current_step='assistant_projection',updated_at=NOW() WHERE id=$1",[j.id,r,j.requestedTrustedKnowledgeRevision]);}
async function checkpointProjection(j:DownstreamSynchronizationJob,f:string){await database().query("UPDATE ai_builder_downstream_synchronization_jobs SET completed_assistant_projection_fingerprint=$2,current_step='completed',updated_at=NOW() WHERE id=$1",[j.id,f]);}
async function finishFailure(j:DownstreamSynchronizationJob,attempt:string,e:unknown){const c=await database().connect(),ec=errorCode(e),fc=classifySynchronizationFailure(ec),retry=shouldRetryFailure(fc,j.attemptCount,true);try{await c.query("BEGIN");await c.query("UPDATE ai_builder_downstream_synchronization_attempts SET finished_at=NOW(),result='failed',failure_class=$2,error_code=$3,error_message=$4 WHERE id=$1",[attempt,fc,ec,safeText(e)]);const status=retry?"retry_scheduled":fc==="permanent"||j.attemptCount>=j.maxAttempts?"dead_letter":"failed";await c.query(`UPDATE ai_builder_downstream_synchronization_jobs SET status=$2,last_error_code=$3,last_error_message=$4,last_failure_class=$5,next_attempt_at=CASE WHEN $2='retry_scheduled' THEN NOW()+($6::text||' seconds')::interval ELSE NULL END,dead_lettered_at=CASE WHEN $2='dead_letter' THEN NOW() ELSE dead_lettered_at END,execution_token=NULL,claim_expires_at=NULL,updated_at=NOW() WHERE id=$1`,[j.id,status,ec,safeText(e),fc,retryDelaySeconds(j.attemptCount)]);await c.query("COMMIT");}catch(x){await c.query("ROLLBACK");throw x;}finally{c.release();}}

/** Canonical 12A work wrapped in a leased, append-only attempt protocol. */
export async function executeDownstreamSynchronizationJob(id:string, options:{trigger?:Trigger;actorType?:string;actorId?:string;commandId?:string;forceBusiness?:boolean;projectionOnly?:boolean}={}){await ensureAiBuilderSchema();const c=await database().connect();let j:DownstreamSynchronizationJob,attempt:string;const token=randomUUID();try{await c.query("BEGIN");const row=(await c.query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!row)throw new Error("downstream_synchronization_job_not_found");j=parse(row);if(j.status==="succeeded") {await c.query("COMMIT");return j;}if(j.status==="dead_letter"||j.status==="running")throw new Error("downstream_synchronization_invalid_state");const p=(await c.query("SELECT id FROM ai_builder_projects WHERE id=$1 FOR UPDATE",[j.projectId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found");attempt=randomUUID();await c.query("UPDATE ai_builder_downstream_synchronization_jobs SET status='running',attempt_count=attempt_count+1,last_attempt_at=NOW(),execution_token=$2,claim_expires_at=NOW()+INTERVAL '15 minutes',next_attempt_at=NULL,updated_at=NOW() WHERE id=$1",[id,token]);await c.query("INSERT INTO ai_builder_downstream_synchronization_attempts (id,job_id,project_id,attempt_number,trigger_type,starting_status,starting_step,execution_token,actor_type,actor_id,recovery_command_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[attempt,id,j.projectId,j.attemptCount+1,options.trigger??"initial",j.status,j.currentStep,token,options.actorType??"system",options.actorId??null,options.commandId??null]);await c.query("COMMIT");j={...j,attemptCount:j.attemptCount+1};}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}
try{if(!options.projectionOnly){const x=await database().connect();try{await x.query("BEGIN");const p=(await x.query("SELECT trusted_knowledge_revision FROM ai_builder_projects WHERE id=$1 FOR UPDATE",[j.projectId])).rows[0];if(!p)throw new Error("downstream_synchronization_project_not_found");if(Number(p.trusted_knowledge_revision)<j.requestedTrustedKnowledgeRevision)throw new Error("downstream_synchronization_trusted_knowledge_revision_not_ready");await rebuildPersistedBusinessMemoryFromTrustedKnowledge(x,j.projectId,Number(p.trusted_knowledge_revision),{forceReconstruction:options.forceBusiness||j.mode==="full_rebuild"});const v=(await x.query("SELECT memory.revision,memory.trusted_knowledge_revision,project.business_memory_revision FROM ai_builder_projects project LEFT JOIN ai_builder_business_memory memory ON memory.project_id=project.id WHERE project.id=$1",[j.projectId])).rows[0];if(!v||v.revision==null||Number(v.trusted_knowledge_revision)<j.requestedTrustedKnowledgeRevision||Number(v.business_memory_revision)!==Number(v.revision))throw new Error("business_memory_synchronization_verification_failed");await x.query("COMMIT");await checkpointMemory(j,Number(v.revision));}catch(e){await x.query("ROLLBACK").catch(()=>undefined);throw e;}finally{x.release();}}
const x=await database().connect();let f:string;try{await x.query("BEGIN");await rebuildAssistantProjectionInTransaction({client:x,projectId:j.projectId,forceRebuild:j.mode==="full_rebuild"});const m=await loadPersistedBusinessMemory(x,j.projectId),p=await getPersistedAssistantProjection(x,j.projectId),expected=m?buildAssistantProjection(m).businessMemoryFingerprint:null;if(!m||!p||p.businessMemoryFingerprint!==expected||p.projectionVersion!==ASSISTANT_PROJECTION_VERSION||p.schemaVersion!==ASSISTANT_PROJECTION_SCHEMA_VERSION||p.invalidationState!=="valid")throw new Error("assistant_projection_synchronization_verification_failed");f=p.businessMemoryFingerprint;await x.query("COMMIT");}catch(e){await x.query("ROLLBACK").catch(()=>undefined);throw e;}finally{x.release();}await checkpointProjection(j,f!);const final=await database().connect();try{await final.query("BEGIN");await final.query("UPDATE ai_builder_downstream_synchronization_attempts SET finished_at=NOW(),result='succeeded',completed_trusted_knowledge_revision=$2,completed_business_memory_revision=(SELECT completed_business_memory_revision FROM ai_builder_downstream_synchronization_jobs WHERE id=$1),completed_assistant_projection_fingerprint=$3 WHERE id=$4",[id,j.requestedTrustedKnowledgeRevision,f,attempt]);await final.query("UPDATE ai_builder_downstream_synchronization_jobs SET status='succeeded',completed_at=NOW(),execution_token=NULL,claim_expires_at=NULL,last_error_code=NULL,last_error_message=NULL,last_failure_class=NULL,updated_at=NOW() WHERE id=$1",[id]);await final.query("COMMIT");}finally{final.release();}return (await getDownstreamSynchronizationJob(id))!;}catch(e){await finishFailure(j,attempt!,e);throw e;}}
