import "server-only";
import { createHash } from "node:crypto";
import { Pool } from "@neondatabase/serverless";
import { ensureAiBuilderSchema } from "@/app/lib/db/ai-builder-schema";
import { executeDownstreamSynchronizationJob, getDownstreamSynchronizationJob } from "./downstream-synchronization";
import { MAX_SYNCHRONIZATION_ATTEMPTS } from "./retry-policy";
let pool: Pool | null = null; const db=()=>pool??=new Pool({connectionString:process.env.DATABASE_URL});
const fingerprint=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");

export async function getRetryableSynchronizationJobs(){await ensureAiBuilderSchema();return (await db().query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE status='retry_scheduled' AND next_attempt_at<=NOW() ORDER BY next_attempt_at")).rows;}
export async function getDeadLetterSynchronizationJobs(){await ensureAiBuilderSchema();return (await db().query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE status='dead_letter' ORDER BY dead_lettered_at DESC")).rows;}
export async function getStaleRunningSynchronizationJobs(){await ensureAiBuilderSchema();return (await db().query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE status='running' AND claim_expires_at<NOW()")).rows;}

/** Claims rows in one transaction; canonical execution retains the lease. */
export async function executeEligibleSynchronizationRetries(limit=10){await ensureAiBuilderSchema();const c=await db().connect();let ids:string[]=[];try{await c.query("BEGIN");ids=(await c.query("SELECT id FROM ai_builder_downstream_synchronization_jobs WHERE status='retry_scheduled' AND next_attempt_at<=NOW() AND (claim_expires_at IS NULL OR claim_expires_at<NOW()) ORDER BY next_attempt_at FOR UPDATE SKIP LOCKED LIMIT $1",[Math.min(Math.max(limit,1),100)])).rows.map((x:{id:string})=>x.id);for(const id of ids) await c.query("UPDATE ai_builder_downstream_synchronization_jobs SET status='pending', updated_at=NOW() WHERE id=$1",[id]);await c.query("COMMIT");}finally{c.release();}const results=[];for(const id of ids){try{results.push(await executeDownstreamSynchronizationJob(id,{trigger:"automatic_retry"}));}catch{ /* one bad job never starves later eligible work */ }}return results;}

export async function recoverStaleRunningSynchronizationJobs(limit=10){await ensureAiBuilderSchema();const c=await db().connect();try{await c.query("BEGIN");const rows=(await c.query("SELECT * FROM ai_builder_downstream_synchronization_jobs WHERE status='running' AND claim_expires_at<NOW() ORDER BY claim_expires_at FOR UPDATE SKIP LOCKED LIMIT $1",[Math.min(Math.max(limit,1),100)])).rows;for(const j of rows){const dead=Number(j.attempt_count)>=Number(j.max_attempts??MAX_SYNCHRONIZATION_ATTEMPTS);await c.query("INSERT INTO ai_builder_downstream_synchronization_attempts (id,job_id,project_id,attempt_number,trigger_type,starting_status,starting_step,result,failure_class,error_code,error_message,finished_at) VALUES (md5(random()::text||clock_timestamp()::text),$1,$2,$3,'stale_running_recovery','running',$4,'failed','transient','downstream_synchronization_stale_claim','expired execution claim recovered',NOW())",[j.id,j.project_id,j.attempt_count,j.current_step]);await c.query("UPDATE ai_builder_downstream_synchronization_jobs SET status=$2,recovery_revision=recovery_revision+1,execution_token=NULL,claim_expires_at=NULL,next_attempt_at=CASE WHEN $2='retry_scheduled' THEN NOW()+INTERVAL '1 minute' ELSE NULL END,dead_lettered_at=CASE WHEN $2='dead_letter' THEN NOW() ELSE dead_lettered_at END,last_error_code='downstream_synchronization_stale_claim',last_error_message='expired execution claim recovered',last_failure_class='transient',updated_at=NOW() WHERE id=$1",[j.id,dead?"dead_letter":"retry_scheduled"]);}await c.query("COMMIT");return rows.length;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}

export async function manuallyRetryDownstreamSynchronization(input:{projectId:string;jobId:string;commandId:string;clerkUserId:string;reason?:string}){await ensureAiBuilderSchema();const c=await db().connect(), request={jobId:input.jobId,reason:input.reason??"",type:"manual_retry"};try{await c.query("BEGIN");const old=(await c.query("SELECT * FROM ai_builder_downstream_synchronization_commands WHERE command_id=$1 FOR UPDATE",[input.commandId])).rows[0];if(old){if(old.request_fingerprint!==fingerprint(request))throw new Error("downstream_synchronization_command_input_mismatch");await c.query("COMMIT");return old.result;}const j=(await c.query("SELECT j.* FROM ai_builder_downstream_synchronization_jobs j JOIN ai_builder_projects p ON p.id=j.project_id WHERE j.id=$1 AND j.project_id=$2 AND p.clerk_user_id=$3 AND p.archived_at IS NULL FOR UPDATE",[input.jobId,input.projectId,input.clerkUserId])).rows[0];if(!j)throw new Error("downstream_synchronization_project_not_found_or_archived");if(!["failed","retry_scheduled","dead_letter"].includes(j.status))throw new Error("downstream_synchronization_invalid_state");await c.query("UPDATE ai_builder_downstream_synchronization_jobs SET status='pending',next_attempt_at=NULL,execution_token=NULL,claim_expires_at=NULL,last_error_code=NULL,last_error_message=NULL,last_failure_class=NULL,last_recovery_command_id=$2,updated_at=NOW() WHERE id=$1",[input.jobId,input.commandId]);const result={jobId:input.jobId,status:"pending"};await c.query("INSERT INTO ai_builder_downstream_synchronization_commands (command_id,project_id,job_id,command_type,request_fingerprint,result) VALUES ($1,$2,$3,'manual_retry',$4,$5)",[input.commandId,input.projectId,input.jobId,fingerprint(request),JSON.stringify(result)]);await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}}

export async function getManualRetryCommandResult(commandId:string){await ensureAiBuilderSchema();return (await db().query("SELECT result FROM ai_builder_downstream_synchronization_commands WHERE command_id=$1 AND command_type='manual_retry'",[commandId])).rows[0]?.result??null;}
