import assert from "node:assert/strict";
import test from "node:test";
import type { AssistantProjection } from "./contracts";
import { compareAssistantProjectionParity } from "./parity";
import { AssistantProjectionRuntimeValidationError } from "./validation";

const source = (id: string, origin: AssistantProjection["sources"][number]["origin"]) => ({ id, origin, url: null, label: null, capturedAt: "2026-01-01T00:00:00.000Z", crawlAttemptId: null });
const projection = (overrides: Partial<AssistantProjection> = {}): AssistantProjection => ({ projectId: "project", businessMemoryFingerprint: "business_memory_abcdef0123456789abcdef01", projectionVersion: 1, schemaVersion: 1, identity: { status: "missing", canonicalEntityId: null, businessName: null, aliases: [], mergedEntityIds: [], redirectedEntityIds: [], contactEntityIds: [] }, assistant: { name: "Ava", purpose: "Help", tone: "warm", responseStyle: "brief", primaryAudience: null, escalationInstructions: [] }, services: [], pricing: [], policies: [], faqs: [], restrictions: [], relationships: [], sources: [source("website", "website")], evidence: [], missingInformation: [], ...overrides });
const fact = (title: string, content: string, extra: Record<string, unknown> = {}) => ({ id: `legacy-${title}-${content}`, category: "service" as const, title, content, confidence: "high" as const, confidenceScore: .9, sourceEntryId: "website", sourceExcerpt: "", sourceType: "website", sourceUrl: null, tags: [], provenance: { classification: "website" as const, predecessorClassification: null, originalClassification: null, correctedByClerkUserId: null, correctedByDisplayName: null, correctedByEmail: null, correctedAt: null }, reviewState: "approved" as const, governanceRevision: 1, ...extra });
const canonicalFact = (title: string, value: string, extra: Record<string, unknown> = {}) => ({ id: `canonical-${title}-${value}`, entityId: "entity", assertionId: "assertion", entityType: "service" as const, title, value, aliases: [], tags: [], confidence: { level: "high" as const, score: .9 }, authority: "confirmed" as const, reviewState: "approved" as const, evidenceIds: [], sourceIds: ["website"], ...extra });
const faq = (question: string, answer: string, extra: Record<string, unknown> = {}) => ({ id: `legacy-${question}-${answer}`, question, answer, confidence: "high" as const, confidenceScore: .9, sourceEntryIds: ["website"], provenance: { ...fact("x", "x").provenance }, reviewState: "approved" as const, governanceRevision: 1, ...extra });
const canonicalFaq = (question: string, answer: string, extra: Record<string, unknown> = {}) => ({ ...canonicalFact(question, answer, extra), entityType: "faq" as const, question, answer });
const report = (legacy: ReturnType<typeof pack>, canonical: AssistantProjection) => compareAssistantProjectionParity({ projectId: "project", legacy, canonicalProjection: canonical, comparedAt: "2026-01-01T00:00:00.000Z" });
const pack = (facts: ReturnType<typeof fact>[] = [], faqs: ReturnType<typeof faq>[] = []) => ({ sessionId: "project", assistantName: "Ava", assistantPurpose: "Help", assistantTone: "warm", primaryAudience: null, builtAt: "", version: 7, behaviorRules: [], prohibitedClaims: [], facts, faq: faqs });

test("exact match has no differences", () => { const r = report(pack([fact("Planning", "Plan")], [faq("What?", "Answer")]), projection({ services: [canonicalFact("Planning", "Plan")], faqs: [canonicalFaq("What?", "Answer")] })); assert.equal(r.status, "MATCH"); assert.equal(r.mismatchSummary.total, 0); });
test("formatting-only difference is minor", () => { const r = report(pack([fact("Planning", "hello\nworld")]), projection({ services: [canonicalFact(" Planning ", "hello world")] })); assert.equal(r.status, "MINOR_DIFFERENCE"); assert.equal(r.categories.formattingDifferences.length, 1); });
test("substantive fact content is explicit major mismatch", () => { const r = report(pack([fact("Planning", "Legacy")]), projection({ services: [canonicalFact("Planning", "Canonical")] })); assert.equal(r.status, "MAJOR_DIFFERENCE"); assert.deepEqual(r.categories.factContentMismatches[0], { key: "service:planning", legacy: "Legacy", canonical: "Canonical" }); });
test("canonical parity rejects archived projection knowledge rather than treating it as runtime data", () => { const archived = { reviewState: "archived" } as unknown as Record<string, unknown>; assert.throws(() => report(pack([fact("Old", "Old", archived)]), projection({ services: [canonicalFact("Old", "Old", archived)] })), (error: unknown) => error instanceof AssistantProjectionRuntimeValidationError && error.code === "assistant_projection_runtime_non_authoritative_knowledge"); });
test("duplicate fact titles are compared as a multiset", () => { const r = report(pack([fact("Same", "one"), fact("Same", "two")]), projection({ services: [canonicalFact("Same", "one"), canonicalFact("Same", "changed")] })); assert.equal(r.categories.factContentMismatches.length, 1); assert.equal(r.categories.missingKnowledge.length, 0); assert.equal(r.categories.extraKnowledge.length, 0); });
test("duplicate FAQ questions are compared as a multiset", () => { const r = report(pack([], [faq("Same?", "one"), faq("Same?", "two")]), projection({ faqs: [canonicalFaq("Same?", "one"), canonicalFaq("Same?", "changed")] })); assert.equal(r.categories.faq.contentMismatches.length, 1); assert.equal(r.categories.faq.missing.length, 0); assert.equal(r.categories.faq.extra.length, 0); });
test("multiple sources are deterministic and provenance loss explains origins", () => { const r = report(pack([fact("Plan", "Text", { sourceEntryId: "website" })]), projection({ services: [canonicalFact("Plan", "Text", { sourceIds: ["manual", "website"] })], sources: [source("website", "website"), source("manual", "manual_intake")] })); assert.equal(r.status, "MINOR_DIFFERENCE"); assert.match(r.categories.provenanceDifferences[0].canonical!, /mixed\(manual_intake,website\)/); assert.match(r.categories.provenanceDifferences[0].canonical!, /sourceIds=manual,website/); });
