import Link from "next/link";
import { requireAdmin } from "@/app/lib/admin/auth";
import { listAdminPurchases, PURCHASE_STAGES } from "@/app/lib/admin/repository";
import { savePurchaseAction } from "../actions";
import { EmptyState, PageHeader, Pagination, SearchBar, card, formatDateTime, td, th } from "../_components/AdminUi";

export default async function AdminPurchasesPage({ searchParams }: { searchParams: { q?: string; status?: string; sort?: string; page?: string } }) {
  await requireAdmin(); const q=(searchParams.q||"").toLowerCase(),status=searchParams.status||"all",sort=searchParams.sort||"newest";
  let rows=(await listAdminPurchases()).filter(r=>(!q||[r.businessName,r.ownerName||"",r.email||"",r.projectId].some(v=>v.toLowerCase().includes(q)))&&(status==="all"||r.status===status));
  rows.sort((a,b)=>sort==="oldest"?+new Date(a.createdAt)-+new Date(b.createdAt):+new Date(b.createdAt)-+new Date(a.createdAt));
  const size=25,pages=Math.max(1,Math.ceil(rows.length/size)),page=Math.min(pages,Math.max(1,Number(searchParams.page)||1));rows=rows.slice((page-1)*size,page*size);
  return <div className="space-y-6"><PageHeader eyebrow="Sales queue" title="Purchase requests" description="Read-only purchase intent submitted from completed AI Builder demos." />
    <SearchBar placeholder="Search business, owner, email, or project" defaultValue={searchParams.q} extras={<><select name="status" defaultValue={status} className="rounded-xl border border-white/10 bg-[#020611] px-3 py-2.5 text-sm text-slate-300"><option value="all">All statuses</option>{PURCHASE_STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select><select name="sort" defaultValue={sort} className="rounded-xl border border-white/10 bg-[#020611] px-3 py-2.5 text-sm text-slate-300"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></>} />
    {!rows.length?<EmptyState title="No purchase requests found" detail="New requests will appear here as soon as they are submitted."/>:<div className={`${card} overflow-x-auto`}><table className="w-full min-w-[1450px]"><thead className="border-b border-white/[.06]"><tr>{["Business","Owner","Email","Submitted","Project","Status","Follow-up stage","Internal comments",""].map(x=><th key={x||"actions"} className={th}>{x}</th>)}</tr></thead><tbody className="divide-y divide-white/[.05]">{rows.map(r=><tr key={r.id} className="hover:bg-white/[.025]"><td className={`${td} font-bold text-white`}>{r.businessName}</td><td className={td}>{r.ownerName||"Anonymous"}</td><td className={td}>{r.email||"Not collected"}</td><td className={td}>{formatDateTime(r.createdAt)}</td><td className={td}><Link href={`/admin/projects/${r.projectId}`} className="font-bold text-amber-300 hover:text-amber-200">Review project</Link></td><td className={td} colSpan={4}><form action={savePurchaseAction} className="grid grid-cols-[150px_190px_minmax(260px,1fr)_auto] items-center gap-3"><input type="hidden" name="purchaseId" value={r.id}/><input type="hidden" name="projectId" value={r.projectId}/><select name="status" defaultValue={r.status} className="rounded-lg border border-white/10 bg-[#020611] px-3 py-2 text-xs capitalize text-slate-300">{PURCHASE_STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select><select name="followUpStage" defaultValue={r.followUpStage} className="rounded-lg border border-white/10 bg-[#020611] px-3 py-2 text-xs capitalize text-slate-300">{PURCHASE_STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select><input name="internalComments" defaultValue={r.internalComments||""} placeholder="Private follow-up comments" className="rounded-lg border border-white/10 bg-[#020611] px-3 py-2 text-xs text-white"/><button className="cta-raised rounded-lg border border-amber-300/20 bg-[#101936] px-3 py-2 text-xs font-black text-white">Save</button></form></td></tr>)}</tbody></table></div>}
    <Pagination page={page} pages={pages} params={{q:searchParams.q,status,sort}} /></div>;
}
