import Link from "next/link";
import { requireAdmin } from "@/app/lib/admin/auth";
import { listAdminPurchases, PURCHASE_STAGES } from "@/app/lib/admin/repository";
import { savePurchaseAction } from "../actions";
import { EmptyState, PageHeader, Pagination, SearchBar, card, formatDateTime } from "../_components/AdminUi";

export default async function AdminPurchasesPage({ searchParams }: { searchParams: { q?: string; status?: string; sort?: string; page?: string } }) {
  await requireAdmin(); const q=(searchParams.q||"").toLowerCase(),status=searchParams.status||"all",sort=searchParams.sort||"newest";
  let rows=(await listAdminPurchases()).filter(r=>(!q||[r.businessName,r.ownerName||"",r.email||"",r.projectId].some(v=>v.toLowerCase().includes(q)))&&(status==="all"||r.status===status));
  rows.sort((a,b)=>sort==="oldest"?+new Date(a.createdAt)-+new Date(b.createdAt):+new Date(b.createdAt)-+new Date(a.createdAt));
  const size=25,pages=Math.max(1,Math.ceil(rows.length/size)),page=Math.min(pages,Math.max(1,Number(searchParams.page)||1));rows=rows.slice((page-1)*size,page*size);
  return <div className="space-y-8"><PageHeader eyebrow="Sales queue" title="Purchase requests" description="Read-only purchase intent submitted from completed AI Builder demos." />
    <SearchBar placeholder="Search business, owner, email, or project" defaultValue={searchParams.q} extras={<><select name="status" defaultValue={status} className="rounded-xl border border-amber-300/15 bg-[#020611] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-amber-300/50"><option value="all">All statuses</option>{PURCHASE_STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select><select name="sort" defaultValue={sort} className="rounded-xl border border-amber-300/15 bg-[#020611] px-3 py-2.5 text-sm text-slate-300 outline-none focus:border-amber-300/50"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></>} />
    {!rows.length?<EmptyState title="No purchase requests found" detail="New requests will appear here as soon as they are submitted."/>:<div className="grid items-start gap-4 xl:grid-cols-2">{rows.map(r=><article key={r.id} className={`${card} overflow-hidden`}><div className="flex flex-wrap items-start justify-between gap-3 bg-amber-300/[.025] px-5 py-4"><div><h2 className="font-bold text-white">{r.businessName}</h2><p className="mt-1 text-xs text-slate-500">{r.ownerName||"Anonymous"} · {r.email||"Email not collected"}</p></div><div className="text-right"><p className="text-xs text-slate-500">{formatDateTime(r.createdAt)}</p><Link href={`/admin/projects/${r.projectId}`} className="mt-1 inline-block text-xs font-bold text-amber-300 hover:text-amber-200">Review project →</Link></div></div><form action={savePurchaseAction} className="grid gap-3 p-5 sm:grid-cols-2"><input type="hidden" name="purchaseId" value={r.id}/><input type="hidden" name="projectId" value={r.projectId}/><label className="space-y-1 text-xs font-bold text-slate-400">Status<select name="status" defaultValue={r.status} className="block w-full rounded-lg border border-amber-300/10 bg-[#020611] px-3 py-2 text-xs capitalize text-slate-300">{PURCHASE_STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select></label><label className="space-y-1 text-xs font-bold text-slate-400">Follow-up<select name="followUpStage" defaultValue={r.followUpStage} className="block w-full rounded-lg border border-amber-300/10 bg-[#020611] px-3 py-2 text-xs capitalize text-slate-300">{PURCHASE_STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select></label><label className="space-y-1 text-xs font-bold text-slate-400 sm:col-span-2">Internal comments<input name="internalComments" defaultValue={r.internalComments||""} placeholder="Private follow-up comments" className="block w-full rounded-lg border border-amber-300/10 bg-[#020611] px-3 py-2 text-xs text-white"/></label><div className="sm:col-span-2"><button className="cta-raised rounded-lg border border-amber-300/15 bg-[#081226] px-4 py-2 text-xs font-black text-white">Save changes</button></div></form></article>)}</div>}
    <Pagination page={page} pages={pages} params={{q:searchParams.q,status,sort}} /></div>;
}
