import type { AiBuilderSession, BusinessContextCategory } from "../contracts";
import type { DeterministicBrain, DeterministicSource } from "./contracts";
import { buildDeterministicBrain } from "./pipeline";
const CATEGORY:Record<string,BusinessContextCategory>={company_overview:"business_profile",industry_served:"audience",product:"service",service:"service",customer_segment:"audience",policy:"policy",competitive_differentiator:"differentiator",additional_business_knowledge:"business_profile",contact_information:"business_profile",location_service_area:"business_profile",pricing_plan:"pricing",support_onboarding:"process",faq:"faq"};
const hash=(value:string)=>{let h=2166136261;for(const c of value){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(16);};
export function assembleDeterministicSession(params:{sessionId:string;sources:DeterministicSource[];businessName:string;tone:string;createdAt?:string}):{session:AiBuilderSession;brain:DeterministicBrain}{
 const now=params.createdAt??new Date().toISOString(),brain=buildDeterministicBrain(params.sources);const entries=brain.facts.filter((f)=>f.category!=="faq").map((fact)=>{const source=fact.evidence[0],isOwner=source.url.startsWith("owner://");return {id:`det_${hash(`${fact.category}\0${fact.value}`)}`,sessionId:params.sessionId,category:CATEGORY[fact.category]??"business_profile",title:fact.title,content:fact.value,confidence:fact.confidence,confidenceScore:fact.confidence==="high"?.95:fact.confidence==="medium"?.75:.55,status:"proposed" as const,source:{intakeBlockId:isOwner?source.url.slice(8):"website_knowledge",excerpt:source.excerpt,sourceType:isOwner?"manual_intake" as const:"website" as const,sourceUrl:isOwner?null:source.url},metadata:{generated:!isOwner,userEdited:isOwner,conflictingEntryIds:[],tags:[fact.category],provenanceClassification:isOwner?"manual" as const:"website" as const},createdAt:now,updatedAt:now};});
 const faqs=brain.facts.filter((f)=>f.category==="faq"&&f.value.includes("?")).flatMap((fact)=>{const [question,...answer]=fact.value.split("?");if(!answer.join("?").trim())return [];return [{id:`faq_${hash(fact.value)}`,sessionId:params.sessionId,question:`${question.trim()}?`,answer:answer.join("?").trim(),confidence:fact.confidence,confidenceScore:fact.confidence==="high"?.95:.75,sourceEntryIds:[],status:"proposed" as const,createdAt:now,updatedAt:now}];});
 const byCategory:AiBuilderSession["contextCounts"]["byCategory"]={};entries.forEach((e)=>byCategory[e.category]=(byCategory[e.category]??0)+1);
 return {brain,session:{id:params.sessionId,status:"review_required",intakeBlocks:params.sources.filter((s)=>s.type==="owner").map((s)=>({id:s.id,label:s.title,content:s.text,createdAt:now,updatedAt:now})),assistantConfiguration:{name:`${params.businessName} AI`,purpose:`Represent ${params.businessName} accurately`,tone:params.tone,responseStyle:"Clear and source-aware",primaryAudience:null,escalationInstructions:[]},contextEntries:entries,faqEntries:faqs,conflicts:brain.conflicts.map((c)=>({id:c.id,topic:c.topic,firstStatement:c.preferredFact.value,secondStatement:c.conflictingFacts[0]?.value??"",sourceExcerpts:[...c.preferredFact.evidence,...c.conflictingFacts.flatMap((f)=>f.evidence)].map((e)=>e.excerpt),suggestedQuestion:`Which ${c.topic.replaceAll("_"," ")} is current?`,resolved:false})),missingInformation:brain.missingCategories.map((topic)=>({id:`missing:${topic}`,topic,reason:"No supported information was found.",suggestedQuestion:`Add ${topic.replaceAll("_"," ")} information.`,resolved:false})),contextCounts:{total:entries.length+faqs.length,approved:0,proposed:entries.length+faqs.length,archived:0,byCategory},buildProgress:[{stage:"complete",message:"Business Brain ready for review",completed:true,count:entries.length+faqs.length,createdAt:now}],createdAt:now,updatedAt:now,expiresAt:null}};
}
