import type { AiBuilderSession } from "../contracts";
import type { WebsiteSourceBlockRecord, WebsiteSourceDocumentRecord } from "../crawler/websiteSourceRecords";
import type { WebsiteKnowledgeCoverage, WebsiteKnowledgeFact, WebsiteKnowledgePage } from "../knowledge/websiteKnowledge";
export type KnowledgeProvenance = "owner" | "website";
export type DeterministicSourceType = "owner" | "html" | "rendered_html" | "pdf" | "structured_data";
export type ClassifiedPageType = "home" | "about" | "products" | "services" | "pricing" | "faq" | "policies" | "contact" | "locations" | "industries" | "use_cases" | "case_studies" | "testimonials" | "integrations" | "security" | "compliance" | "technical" | "onboarding" | "support" | "partnerships" | "certifications" | "other";
export type DeterministicPage = WebsiteKnowledgePage & {
    text?: string;
    headings?: string[];
    structuredMetadata?: Record<string, unknown>;
    crawlAttemptId?: string;
};
export type OwnerKnowledge = {
    businessName?: string;
    industry?: string;
    productsServices?: string;
    idealCustomers?: string;
    additionalKnowledge?: string;
    policiesOperations?: string;
    caseStudiesTestimonials?: string;
    tone?: string;
};
export type DeterministicEngineInput = {
    pages?: readonly DeterministicPage[];
    sourceDocuments?: readonly WebsiteSourceDocumentRecord[];
    sourceBlocks?: readonly WebsiteSourceBlockRecord[];
    owner?: OwnerKnowledge;
    now?: string;
    sessionId?: string;
};
export type NormalizedEvidence = {
    url: string;
    excerpt: string;
    sourceDocumentId?: string;
    sourceBlockId?: string;
    crawlAttemptId?: string;
    heading?: string;
    pageTitle?: string;
    pageType: ClassifiedPageType;
    sourceType: DeterministicSourceType;
    provenance: KnowledgeProvenance;
    structured: boolean;
};
export type NormalizedSourceBlock = {
    id: string;
    text: string;
    type: WebsiteSourceBlockRecord["type"] | "owner" | "page_text";
    evidence: NormalizedEvidence;
    pageType: ClassifiedPageType;
    heading?: string;
    previousBlockId?: string;
    nextBlockId?: string;
};
export type DeterministicFact = Omit<WebsiteKnowledgeFact, "evidence"> & {
    id: string;
    topicKey: string;
    confidenceScore: number;
    provenance: KnowledgeProvenance;
    evidence: NormalizedEvidence[];
    explicit: boolean;
};
export type DuplicateGroup = {
    id: string;
    topicKey: string;
    factIds: string[];
    mergedFactId: string;
};
export type MaterialConflict = {
    id: string;
    topicKey: string;
    factIds: string[];
    preferredFactId: string;
    websiteFactIds: string[];
    sessionEntryIds: string[];
    reason: string;
};
export type DeterministicFaq = {
    id: string;
    question: string;
    answer: string;
    confidence: WebsiteKnowledgeFact["confidence"];
    confidenceScore: number;
    evidence: NormalizedEvidence[];
    sourceFactIds: string[];
};
export type ConceptHealthStatus = "strong" | "review_recommended" | "needs_attention";
export type ConceptReviewPriority = "low" | "medium" | "high";
export type ConceptHealth = {
    status: ConceptHealthStatus;
    score: number;
    confidence: WebsiteKnowledgeFact["confidence"];
    supportingFactCount: number;
    supportingSourceCount: number;
    ownerSupported: boolean;
    websiteSupported: boolean;
    mixedSourceSupport: boolean;
    conflictCount: number;
    hasConflicts: boolean;
    unresolvedConflictIds: string[];
    reviewPriority: ConceptReviewPriority;
    reasons: string[];
    missingSignals: string[];
};
export type ConceptImportanceLevel = "critical" | "high" | "medium" | "low";
export type ConceptImportanceRisk = "severe" | "high" | "moderate" | "low";
export type ConceptImportance = {
    level: ConceptImportanceLevel;
    score: number;
    reasons: string[];
    businessCriticality: ConceptImportanceLevel;
    assistantCriticality: ConceptImportanceLevel;
    customerImpact: ConceptImportanceLevel;
    riskIfWrong: ConceptImportanceRisk;
};
export type BusinessConcept = {
    id: string;
    canonicalTopicIdentity: string;
    category: WebsiteKnowledgeFact["category"];
    displayName: string;
    supportingFactIds: string[];
    supportingEvidence: NormalizedEvidence[];
    overallConfidence: WebsiteKnowledgeFact["confidence"];
    confidenceScore: number;
    supportingSourceCount: number;
    firstSeenSource: NormalizedEvidence | null;
    lastSeenSource: NormalizedEvidence | null;
    ownerKnowledgeContributes: boolean;
    websiteKnowledgeContributes: boolean;
    health: ConceptHealth;
    importance: ConceptImportance;
};
export type ConceptRelationshipType = "includes" | "belongs_to" | "integrates_with" | "applies_to" | "serves" | "supports" | "contact_for" | "available_in";
export type ConceptRelationshipReasonCode = "explicit_inclusion" | "explicit_plan_membership" | "explicit_integration" | "explicit_policy_scope" | "explicit_customer_segment" | "explicit_support_purpose" | "explicit_service_area" | "owner_supported" | "website_supported" | "multi_source_support" | "affected_by_conflict";
export type ConceptRelationship = {
    id: string;
    type: ConceptRelationshipType;
    sourceConceptId: string;
    targetConceptId: string;
    sourceTopicIdentity: string;
    targetTopicIdentity: string;
    supportingFactIds: string[];
    supportingEvidence: NormalizedEvidence[];
    confidence: WebsiteKnowledgeFact["confidence"];
    confidenceScore: number;
    explicit: true;
    reasonCodes: ConceptRelationshipReasonCode[];
};
export type MissingInformationSignal = {
    id: string;
    topic: string;
    reason: string;
    suggestedQuestion: string;
};
export type DeterministicEngineResult = {
    facts: DeterministicFact[];
    concepts: BusinessConcept[];
    relationships: ConceptRelationship[];
    categories: WebsiteKnowledgeFact["category"][];
    duplicateGroups: DuplicateGroup[];
    conflicts: MaterialConflict[];
    coverage: WebsiteKnowledgeCoverage;
    missingInformation: MissingInformationSignal[];
    faqs: DeterministicFaq[];
    normalizedBlocks: NormalizedSourceBlock[];
    websiteKnowledge: {
        facts: WebsiteKnowledgeFact[];
        coverage: WebsiteKnowledgeCoverage;
        unresolvedQuestions: string[];
    };
    session?: AiBuilderSession;
    executionTimeMs: number;
};
